### ISSUE TITLE
Contribution by adding a variant written on Ext JS 5

### ISSUE THREAD

**Issue by PFazel** [tastejs/todomvc#1001]
Hi,

Sencha has recently released Ext JS 5, which supports two way data binding. It is also responsive, so I thought it would be nice to have an example of todoMVC on top it.
what do you think?

Cheers,
Parham

**Comment by arthurvr** [comment]
Hey @parham-fazel, still interested in picking this up?

**Comment by arthurvr** [comment]
Nobody in the community ever did the PR and this has been open for a while. Time to close this?

**Comment by samccone** [comment]
:jack_o_lantern: :closed_book:
