### ISSUE TITLE
Tooltips not appearing in Firefox and Safari

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#1010]
Missed this when reviewing #984

Reproduce: Hover over one of the links in the `Examples` section in Firefox or Safari. Works in Chrome.

// @passy

**Comment by EduardoLopes** [comment]
I guess this is fixed already? at least is working on Firefox 42.0 (Lubuntu 14.04.3 LTS)

**Comment by passy** [comment]
Thanks, @EduardoLopes! Yes, I reckon the recent update has fixed it.
