### ISSUE TITLE
Optimize vanilla dart build artifacts

### ISSUE THREAD

**Issue by passy** [tastejs/todomvc#1039]
/cc @MathieuLorber 

With #1038 the build output for the vanilla dart package has increased quite a bit and it seems like `browser/dart` is now required for the app to run in a normal browser. Is it still possible to combine the two through `pub build` like it was before and bundle the complete runtime with the output?

**Comment by MathieuLorber** [comment]
No time dedicated to this in last months, sorry. I'm looking at it next week.

**Comment by passy** [comment]
@MathieuLorber Thanks!

**Comment by MathieuLorber** [comment]
See https://github.com/tastejs/todomvc/pull/1206

BTW, I'm not sure to have understood your initial problem with the browser lib dependency.

**Comment by MathieuLorber** [comment]
The issue can be closed. Need help for AngularDart ?

**Comment by samccone** [comment]
:+1: would welcome any help if you want to lend a hand @MathieuLorber thanks!
