### ISSUE TITLE
Spaghetti implementation based on Angular + TypeScript?

### ISSUE THREAD

**Issue by lptr** [tastejs/todomvc#1061]
We are working on [Spaghetti](http://github.com/prezi/spaghetti), a framework that allows modules written in different compile-to-JS languages to communicate in a type-safe fashion. We'd like to take the AngularJS + TypeScript implementation, and rewrite the model part in Kotlin JS to show how a TypeScript and a Kotlin module can interact in a type-safe way. Would you be interested in showing this among the examples?

**Comment by arthurvr** [comment]
Hey there! Thanks for the suggestion and sorry for the late reply. We discussed this and decided to close this. We already have a bunch of Angular apps and Spaghetti doesn't have a really big userbase or community yet. When you feel like its userbase and community grew a bit feel free to ping us again and we can reconsider this :) 

Thanks again!
