### ISSUE TITLE
IE 10 Polymer Implmementation

### ISSUE THREAD

**Issue by daver208** [tastejs/todomvc#1062]
Testing todomvc 1.3.0 in a Windows 8 Guest (Build 9200) in virtualbox from https://www.modern.ie/en-us/virtualization-tools served up from an ubuntu host by python -m SimpleHTTPServer

When testing with a fresh VM in IE 10 I can only add one task.  At some point I was able to add multiple tasks in IE, but I couldn't pin down what needed to be done for it to work.  Deleting the browsing history would cause it to go back to the mode where I could only add 1 task. In either mode the menu pane on the left did not show up in IE.  Tested vs chrome 38.0.2125.111 m.   No real problem for me, but wanted to give feedback.

![ie10_nojre_vs_chrome](https://cloud.githubusercontent.com/assets/3308163/4938188/9b0bad5a-65c9-11e4-9be8-9cea9cab84c4.jpg)

**Comment by arthurvr** [comment]
Yes, I was able to confirm this, but, as you can see on [the Polymer website](https://www.polymer-project.org/0.5/resources/compatibility.html) IE10 does not support any web components feature natively. As the webcomponents.js polyfill does only support IE10 flaky, I don't think we should really care about this.

@addyosmani Thoughts?

**Comment by addyosmani** [comment]
We (Polymer & Web Component polyfills) have limited support for IE10. I would say we shouldn't really care about trying to get this right there given the number of platform oddities needed to work around to get this high-fidelity are probably not worth it for TodoMVC.

**Comment by arthurvr** [comment]
> I would say we shouldn't really care about trying to get this right there given the number of platform oddities needed to work around to get this high-fidelity are probably not worth it for TodoMVC.

I can totally agree with that. For me this issue is good to be closed.

**Comment by addyosmani** [comment]
:+1:
