### ISSUE TITLE
Link broken in knockoutjs and knockoutjs_require readme.md

### ISSUE THREAD

**Issue by herrmannplatz** [tastejs/todomvc#1064]
Following the [Getting Started with Knockout.js](http://www.adobe.com/devnet/html5/articles/getting-started-with-knockoutjs.html) link results in an 404 Error. Furthermore it seems like that this article is no longer available on the adobe site.

**Comment by arthurvr** [comment]
Seems like these are [perfectly working] (http://www.downforeveryoneorjustme.com/http://www.adobe.com/devnet/html5/articles/getting-started-with-knockoutjs.html). Might have been something temporary.
