### ISSUE TITLE
Application.js get cleaned up when building project with Visual Studio

### ISSUE THREAD

**Issue by TristanSoftware** [tastejs/todomvc#1079]
I have download the sample typescript-angular and I try to get it working under a VS2013 Web Application empty template.
I add all the file of the sample, I launch the website by IIS, it works fine.

But when I build the project (without modifying anything) the only lines that remain are :

```
/// <reference path='_all.ts' />
/**
* The main TodoMVC app module.
*
* @type {angular.Module}
*/
var todos;
(function (todos) {
    'use strict';

    var todomvc = angular.module('todomvc', []).controller('todoCtrl', todos.TodoCtrl).directive('todoBlur', todos.todoBlur).directive('todoFocus', todos.todoFocus).service('todoStorage', todos.TodoStorage);
})(todos || (todos = {}));
```

When I try to run the website I have the following error :

```
http://localhost/WebAppTodoMvc/bower_components/angular/angular.js

0x800a139e - Erreur d’exécution JavaScript: [$injector:modulerr] Failed to instantiate module todomvc due to
Error: [ng:areq] Argument 'directiveFactory' is required
```

**Comment by Rian0702** [comment]
Same Problem here

**Comment by svcondor** [comment]
index.html includes a script tag for js/Application.js. It is expecting all of the .ts files to be compiled into the single  application.js.   Either include script tags for all the .js files or change your compile task to combine the .js files. It works on VS 2015 with typescript 1.5.0-beta

**Comment by samccone** [comment]
If anyone would like to open a pr and add readme docs around how to run this in visual studio it would be very welcome. Thanks @svcondor

**Comment by svcondor** [comment]
@samccone  I'll give it a try. Should I add a file called VisualStudio.md?

**Comment by samccone** [comment]
I think it could go under a new sub heading in the markdown file for this app. Thanks!
