### ISSUE TITLE
Proposal: LiquidLava framework

### ISSUE THREAD

**Issue by kogarashisan** [tastejs/todomvc#1084]
Hello!
May I propose my own framework - LiquidLava:
http://www.lava-framework.com/

Here is the ToDo app:
http://www.lava-framework.com/todo_app/index.html#/all
Source:
https://github.com/kogarashisan/LavaSite/tree/gh-pages/todo_app

Demo passes JSHint, but it's not compatible with your unit tests and CSS,
as it uses auto-generated ID attributes on elements.
Also I prefer "is_completed" property name over "completed", and if You don't mind - I want to leave it as is.
Also, there is an issue with focus in Safari, will fix soon.

About:
I guarantee, that this framework differs a lot from anything you have seen or used before.
It was designed to cut-off development costs of large and complex web-applications,
but it's architecture easily allows it to be used for most tiny tasks and widgets.
Feature-rich and completely transparent, debuggable, easy to learn.
I offer you to have a look at tutorials on project's site.

**Comment by kogarashisan** [comment]
Hello everyone!

Since this issue was opened - I continued development of my framework
- Documentation is now 95% complete (it lacks some articles about specific widgets, but core is documented well).
- Fixed some bugs in core (hope it were final bugs)
- Added some new [examples](http://www.lava-framework.com/www/examples.html#FilteredTree) and functionality

Site still lacks distinctive design (I know that default bootstrap theme looks like crap),
and there are no unit tests in the framework yet (which is compensated by numerous debug checks).

But... Lava is already powerful enough to be comparable with top of the market frameworks.
So, my question is: may I count on you and expect to be included in next update of TodoMVC?

When you are not famous - it's very hard to spread the word about your product,
no matter how good it is. Inclusion in your list would save me alot of time and efforts.

P.S.
If something depends on me - then just notify me and I will do the job.

**Comment by arthurvr** [comment]
Closing for the same reason the PR was closed: https://github.com/tastejs/todomvc/pull/1133.
