### ISSUE TITLE
Thorax Architecture Example Page 404

### ISSUE THREAD

**Issue by osiris43** [tastejs/todomvc#1099]
http://addyosmani.github.io/todomvc/labs/architecture-examples/thorax/

Trying to figure out why the thorax generator on my machine doesn't seem to work properly but can't find a working example to compare it too.

**Comment by sindresorhus** [comment]
Where are you seeing that link?

The correct one and one being used on the website is: http://todomvc.com/examples/thorax/

**Comment by osiris43** [comment]
It's on the Thorax Getting Started page.  None of the TodoMVC links are valid.

http://thoraxjs.org/start.html

**Comment by passy** [comment]
Could you open an issue in their end then?

**Comment by osiris43** [comment]
Sorry, thought this was one and the same.  Your example links to the Getting Started page so I got confused.  I'll open it there.

**Comment by passy** [comment]
No worries and thanks!
