### ISSUE TITLE
Proposal: Pajama.js

### ISSUE THREAD

**Issue by theninj4** [tastejs/todomvc#1100]
# Pajama.js

Website: http://www.pajamajs.com/

## Foreword

I've been considering suggesting this for a while now. I re-read `contributing.md` a few days ago and a few sentences caught my attention: `we're always open to looking at novel ways to solve existing problems` and `we care about bold ideas that bring something truly new to the table`. 

I think this framework fits the bill, however, it is NOT production ready nor would I recommend anyone use it for a serious project. If it inspires people to think about web application development differently then my work here is done. This might be a case of you guys take a look at my implementation and judge for yourselves? 

My Branch: https://github.com/theninj4/todomvc/compare/pajama
Hosted App: http://www.pajamajs.com/todo-mvc/

## What does it do differently?

* It's all Javascript and JSON - there are only 13 lines of markup (the strange looking div in the body is to allow `base.js` to inject the side-panel without interfering with the app):
```
<!doctype html>
<html lang="en" data-framework="pajama">
  <head>
    <script type="text/javascript" src="bower_compontents/todomvc-common/base.js"></script>
    <link rel="stylesheet" type="text/css" href="bower_compontents/todomvc-common/base.css" />

    <script type="text/javascript" src="browser.pajama.js"></script>
    <script type="text/javascript" src="routes.js"></script>
  </head>
  <body>
    <div />
  </body>
</html>
```
* No need for DOM selectors, JQuery, or any other library
* Elegant syntax for handling data binding
* Models expose properties and functions, which are bound directly to attributes and events in the DOM. Testing an element's class toggles in a given situation is a simple case of firing the event by invoking the model's function and asserting against the resulting property.

There is a list of design goals on the website (http://www.pajamajs.com/).

## Automation

Running `jshint` against my implementation using your `.jshintrc`:
```
$ jshint ./Controller/* ./Model/* ./View/* ./routes.js
$
```

Running the automated browser tests against my implementation with Chrome:
```
$ mocha allTests.js --no-timeouts --reporter spec --framework=pajama


  TodoMVC - pajama
    When page is initially opened
      ✓ should focus on the todo input field (57ms)
    No Todos
      ✓ should hide #main and #footer (224ms)
    New Todo
      ✓ should allow me to add todo items (629ms)
      ✓ should clear text input field when an item is added (278ms)
      ✓ should append new items to the bottom of the list (752ms)
      ✓ should trim text input (315ms)
      ✓ should show #main and #footer when items added (410ms)
    Mark all as completed
      ✓ should allow me to mark all items as completed (834ms)
      ✓ should allow me to clear the completion state of all items (896ms)
      ✓ complete all checkbox should update state when items are completed / cleared (1044ms)
    Item
      ✓ should allow me to mark items as complete (844ms)
      ✓ should allow me to un-mark items as complete (827ms)
      ✓ should allow me to edit an item (1176ms)
      ✓ should show the remove button on hover 
    Editing
      ✓ should hide other controls when editing (756ms)
      ✓ should save edits on enter (1189ms)
      ✓ should save edits on blur (1315ms)
      ✓ should trim entered text (1183ms)
      ✓ should remove the item if an empty text string was entered (1070ms)
      ✓ should cancel edits on escape (1096ms)
    Counter
      ✓ should display the current number of todo items (478ms)
    Clear completed button
      ✓ should display the number of completed items (936ms)
      ✓ should remove completed items when clicked (978ms)
      ✓ should be hidden when there are no items that are completed (918ms)
    Routing
      ✓ should allow me to display active items (971ms)
      ✓ should respect the back button (1379ms)
      ✓ should allow me to display completed items (939ms)
      ✓ should allow me to display all items (1042ms)
      ✓ should highlight the currently applied filter (1049ms)


  29 passing (47s)
```

**Comment by arthurvr** [comment]
Hey @theninj4! Thanks for working on this. We discussed it and are going to pass for now. We'll see how the framework matures, and reconsider it when that's appropriate.

**Comment by theninj4** [comment]
Ok, thanks for taking the time to consider it :+1:
