### ISSUE TITLE
Upgrade Angular+Firebase Example to latest version of Firebase + AngularFire

### ISSUE THREAD

**Issue by davideast** [tastejs/todomvc#1102]
The current version of the Angular+Firebase example is on AngularFire 0.5.0 while the current version is 0.9.0. There have been many changes to the API since that release so the example isn't very useful it its current state. 

I'd like to get it updated to latest version if that's alright with you guys.

**Comment by sindresorhus** [comment]
:+1: Much alright :)

**Comment by passy** [comment]
:+1:

**Comment by arthurvr** [comment]
Fixed in #1103
