### ISSUE TITLE
The add.Initializer method has been depreciated in Marionette.js

### ISSUE THREAD

**Issue by adriangordon1231** [tastejs/todomvc#1105]
Currently, the Marionette Todo app uses the TodoList.addInitializer() method to instantiate the controller and router. However, it seems as though this method has recently been depreciated by the marionette team and is scheduled for removal in the next version. 

From the Docs : 
Warning: deprecated

    This feature is deprecated, and is scheduled to be removed in version 3 of Marionette. Instead of Initializers, you should use events to manage start-up logic. The start event is an ideal substitute for Initializers.

    If you were relying on the deferred nature of Initializers in your app, you should instead use Promises. This might look something like the following:

    doAsyncThings().then(app.start);

**Comment by samccone** [comment]
hi @adriangordon1231 thanks for raising this, the best place to cross post this so Marionette people can find it is on the the main website issue tracker
https://github.com/marionettejs/marionettejs.com

Thanks for filing this, we will fix it
