### ISSUE TITLE
Adding Backbone.View.Elements

### ISSUE THREAD

**Issue by jifeon** [tastejs/todomvc#1106]
Hi there!

I'm a contributor of https://github.com/backbonex/backbone.view.elements the library which provides possibility to avoid duplication of CSS classes and selectors and also helps with caching elements inside backbone views.

I forked todomvc to show the difference between two approaches using Backbone.View.Elements and without it in simple git diff like this https://github.com/backbonex/todomvc/commit/0745cc597fa1b089a23e5b4ee3d0d583b829bb0d

I understand that the lib is not a rich framework and touches only view part and the way how you manage your classes and selectors and retrieve elements. So my question is can I do a pull request? Or can Backbone.View.Elements be mentioned in your wiki at least?

**Comment by arthurvr** [comment]
We discussed this with the team and decided to not have an extra implementation for this. We would like to see the community around it develop and grow.

When you feel like the plugin matured and its community matured, feel free to reopen :)

Thanks, though! :dancer: 

> Or can Backbone.View.Elements be mentioned in your wiki at least?

In the wiki would be fine :)
