### ISSUE TITLE
New app UI & switch to npm for dependencies

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#1110]
I finally managed to finish the [new app UI](https://github.com/tastejs/todomvc-app-css).

Now we just need to switch the apps over. No structural changes should be needed.

I took the liberty to change from bower to npm as that's the future and it makes it easier for us to deal with dependencies. We should also .gitignore any unwanted file so to make it easier to upgrade dependencies in the future.

`todomvc-common` no longer contains the app CSS, only the learning-bar. The app CSS is in the `todomvc-app-css` module.

I've converted the [backbone app as an example](https://github.com/tastejs/todomvc/commit/d674391ea8334ee663b6b050b6b88863a3cba90f). ([live demo](http://todomvc.com/examples/backbone/)).
## 

Help from anyone more than welcome.
## Apps needing updating
- [x] FOAM
- [x] agilityjs (dropped, https://github.com/tastejs/todomvc/issues/1173)
- [x] ampersand
- [x] angular-dart
- [x] angularjs
- [x] angularjs_require
- [x] angularjs-perf
- [x] ariatemplates
- [x] atmajs
- [x] backbone
- [x] backbone_marionette
- [x] backbone_require
- [x] batman
- [x] canjs
- [x] canjs_require
- [x] chaplin-brunch
- [x] closure
- [x] componentjs
- [ ] cujo
- [x] derby
- [x] dijon
- [x] dojo
- [ ] duel
- [ ] durandal
- [x] emberjs
- [x] enyo_backbone
- [x] epitome
- [x] exoskeleton
- [x] extjs_deftjs
- [x] firebase-angular
- [x] flight
- [ ] gwt
- [x] jquery
- [ ] kendo
- [x] knockback
- [x] knockoutjs
- [x] knockoutjs_require
- [x] lavaca_require
- [x] maria (dropped, https://github.com/tastejs/todomvc/issues/1173)
- [ ] meteor
- [x] mithril
- [x] montage
- [x] olives
- [x] plastronjs
- [x] polymer
- [x] puremvc
- [x] ractive
- [x] rappidjs
- [x] react
- [x] react-backbone
- [ ] sammyjs
- [ ] sapui5
- [x] serenadejs
- [ ] socketstream
- [x] somajs
- [x] somajs_require
- [x] spine
- [x] stapes
- [x] stapes_require
- [ ] troopjs_require
- [x] typescript-angular
- [x] typescript-backbone
- [x] vanilladart
- [x] vanillajs
- [x] vue
- [x] yui
- [x] Thorax
- [x] Thorax_lumbar

**Comment by sindresorhus** [comment]
@tastejs/todomvc

**Comment by passy** [comment]
Thanks so much for this, Sindre. I love the new layout and you know that I was a bit sceptical on the first iteration, but this one is perfect. <3

Have you registered the new repo with `bower`? It's probably going to take a while until all authors switch over to npm.

**Comment by sindresorhus** [comment]
> Thanks so much for this, Sindre. I love the new layout and you know that I was a bit sceptical on the first iteration, but this one is perfect. <3

![tumblr_mqmk6j8kkz1qdlh1io1_250](https://cloud.githubusercontent.com/assets/170270/5980957/49bf5084-a8e8-11e4-833b-d789068ff9f6.gif)


> Have you registered the new repo with bower? It's probably going to take a while until all authors switch over to npm.

I have now.

**Comment by kamilogorek** [comment]
Ampersand [x]

**Comment by arthurvr** [comment]
I just opened a PR for the jQuery example. I'm willing to open one for some other examples too.

**Comment by sindresorhus** [comment]
@kamilogorek Nice!

@arthurvr Weeeee :dancer:

**Comment by addyosmani** [comment]
I'll take on updating the Polymer app (unless it's been started already).

**Comment by arthurvr** [comment]
Somebody may tick the vanilla js example too. My PR just got merged.

**Comment by passy** [comment]
Done! :facepunch:

**Comment by arthurvr** [comment]
Just got out two extra PRs. One for the Aria templates example, the other one for Batman.

**Comment by sindresorhus** [comment]
@arthurvr Woot! You're on fire:

![superhighfive](https://cloud.githubusercontent.com/assets/170270/6036383/0bac1a4c-ac77-11e4-89a4-cc425e127906.gif)

**Comment by arthurvr** [comment]
Next one, rAppid. https://github.com/tastejs/todomvc/pull/1118

**Comment by arthurvr** [comment]
next: https://github.com/tastejs/todomvc/pull/1119. :tada:

**Comment by kmargaritis** [comment]
I will take the flight example! Great work @sindresorhus!

**Comment by arthurvr** [comment]
I just opened 3 more PRs.

**Comment by kogarashisan** [comment]
In IE 10 on Win8 there is a CSS bug: 
"clear completed" button is invisible in all applications (reproducible in Backbone and Angular examples)

**Comment by sindresorhus** [comment]
@kogarashisan I don't care about IE, but PR welcome if you do.

**Comment by arthurvr** [comment]
@sindresorhus Why did you close this?

**Comment by sindresorhus** [comment]
I didn't.

**Comment by addyosmani** [comment]
You're all on fire. Thanks for getting so much momentum behind updating these apps to the new UI, @sindresorhus. Is it worth us re-pinging former contributions for the outstanding items to see if they can help?

**Comment by sindresorhus** [comment]
@addyosmani Yes, good idea.

**Comment by addyosmani** [comment]
What would be less noisy? We can either do this in new issues for each app requiring a UI upgrade or can just do it in a single comment here.

**Comment by sindresorhus** [comment]
@addyosmani Lets just do a mention bomb here.

**Comment by addyosmani** [comment]
:+1: Drafting.

**Comment by addyosmani** [comment]
Hey folks. If you're tagged below, we would love to get your help updating the TodoMVC application for the library or framework you previously helped land to the latest version of our UI. Pardon the batch message :)

* AgilityJS: @tshm 
* AngularDart: @passy wrote it. Maybe @chirayuk or @vicb know someone that could help us update it?
* AngularJS Require: @cburgdorf @jacobmumm
* Atma: @tenbits 
* Marionette and Marionette Require: @jsoverson @derickbailey 
* CanJS: @justinbmeyer - could someone at Bitovi possible help here?
* Chaplin/Brunch: @paulmillr 
* Closure: @chrisprice
* ComponentJS: @rse
* Cujo: @briancavalier 
* Dijon: @creynders
* Dojo: @edchat @asudoh
* Durandal: @abhinavgujjar
* EmberJS Require:
* Epitome: @DimitarChristoff/
* Ecoskeleton: @paulmillr 
* Firebase Angular: @cburgdorf
* Flight: @mkuklis 
* GWT: @ColinEberhardt (hah!)
* Kendo: @bsatrom @burkeholland
* Knockout: @knockoutjs-todos @kmalakoff 
* Maria: @petermichaux 
* Meteor: @MStumpp
* Mithril: @lhorie

(Tagging in the rest of the list shortly)

**Comment by kmargaritis** [comment]
@addyosmani I am already working on Flight! I will send a pull request later.

**Comment by creynders** [comment]
Check. I'll update dijon this week.

**Comment by sindresorhus** [comment]
* Epitome: @DimitarChristoff

**Comment by mkuklis** [comment]
@kmargaritis how far along are you? Do you need any help with Flight example?

**Comment by DimitarChristoff** [comment]
I can look at it Monday night.

On Sunday, February 8, 2015, Sindre Sorhus <notifications@github.com> wrote:

>
>    - Epitome: @DimitarChristoff <https://github.com/DimitarChristoff>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tastejs/todomvc/issues/1110#issuecomment-73416506>.
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by kmargaritis** [comment]
Hey @mkuklis. I have finished with all the restructuring. Only thing left is to check the tests and i can send the pr. One thing to note is that jasmine-flight is not available through npm so it will remain as a bower dependency. 

There is though another matter that i would like to discuss. I have 2 different versions of flight-todo app. If we use the UMD bundle of Flight which is available in the npm the modules have different structure which might cause some frustration to early adopters. If we want the current structure then either a new npm module should be submitted that contains Flight as separate modules or use the bower version temporarily. What i have done is to create 2 different versions of the same todo, one using Flight from bower which keeps the existing structutre and one with npm Flight(UMD).

What is your opinion on that?

**Comment by sindresorhus** [comment]
> One thing to note is that jasmine-flight is not available through npm so it will remain as a bower dependency.

npm can depend on git repos: `"jasmine-flight": "flightjs/jasmine-flight#4.0.0"`

**Comment by kmargaritis** [comment]
Ok @sindresorhus. So i can put both jasmine-flight and FlightJS in the same manner. Good catch!

Funny thing is that i have been using this method with Bower for a long time!

**Comment by kmargaritis** [comment]
I just opened a PR for the Atmajs example.

**Comment by kmargaritis** [comment]
@sindresorhus issue closed

**Comment by kmargaritis** [comment]
ping @sindresorhus

**Comment by chrisprice** [comment]
I can take a look at the Closure app but it might take me a little while to get round to it (I think the last time I used it was for that example!). Happy to let anyone jump in if they've got the time.

**Comment by arthurvr** [comment]
@sindresorhus ping, it's closed again :)

**Comment by sindresorhus** [comment]
:p

**Comment by jsoverson** [comment]
@sindresorhus the backbone marionette require version can be removed, i don't think module systems are new enough anymore to warrant a separate version.

**Comment by kmargaritis** [comment]
@sindresorhus :dancers:

**Comment by tshm** [comment]
I'm a little confused about the new style for "Clear completed" button.
In short, following two lines of index.css breaking the style of the button.
(I see that even backbonejs example is now failing the test.)

 #clear-completed { visibility: hidden; }
 #clear-completed::after { content: "Clear completed"; }

Can anybody tell me what is the intention of the code above?

**Comment by sindresorhus** [comment]
@tshm It's done so we don't have to change the HTML on all the existing apps. The most important factor of the redesign was to not require changes to the HTML semantics.

**Comment by altmind** [comment]
I was also biten by this redesign. Now my todomvc implementation cannot pass tests AND it violates specs: Clear completed button -- Displays the number of completed todos.

**Comment by sindresorhus** [comment]
@altmind Rather than just complain, help us update the tests/specs ;)

**Comment by goodmike** [comment]
I'm sorry if this just sounds like complaining, but the "Clear completed" button is broken in Firefox 35.0.1:

* Clicking it does not clear completed items
* The number of completed items does not appear in parentheses
* The button is not selectable through the keyboard, nor can you find it by searching for the text "Clear completed." I think this is an issue with using the `::after` CSS selector to place the content on screen.

Am I missing something? Is this a matter of updating specs, or should we be fixing the HTML or CSS? The app functions fine in FF [when the ::after selector is removed from the CSS](https://github.com/goodmike/todomvc/commit/324c5bc42a4ee367b2dade5a6681f19e9771f094#diff-516c52d40303456c7e587bcac33e6c60L326).

**Comment by technic-tec** [comment]
> The number of completed items does not appear in parentheses
> The button is not selectable through the keyboard, nor can you find it by searching for the text "Clear completed." 

I observed those 2 issues on chrome also, in angularjs and emberjs.

I ran the full browser test, the new app UI seems breaking the "Clear completed button" tests in all frameworks that updated to new app UI.

**Comment by arthurvr** [comment]
Last few days I did some more apps.

> Hey folks. If you're tagged below, we would love to get your help updating the TodoMVC application for the library or framework you previously helped land to the latest version of our UI. Pardon the batch message :)

<blockquote>(Tagging in the rest of the list shortly)</blockquote>

Tagging some more authors.

* montage: @mczepiel
* mozart: @tomdionysus
* puremvc: @cliffhall
* sapui5: @schubertha
* somajs: @soundstep
* thorax: @eastridge
* TroopJS: @mikaelkaron

**Comment by mikaelkaron** [comment]
Sure.

Do you have a timeline for this in mind?

cc @eyalar to potentially get some help with this.

**Comment by schubertha** [comment]
Is there a guide or anything comparable describing the differences?

Sent from a mobile device. Please excuse brevity.

On 14 Mar 2015, at 07:33, Arthur Verschaeve <notifications@github.com<mailto:notifications@github.com>> wrote:


Last few days I did some more apps.

Hey folks. If you're tagged below, we would love to get your help updating the TodoMVC application for the library or framework you previously helped land to the latest version of our UI. Pardon the batch message :)

(Tagging in the rest of the list shortly)

Tagging some more authors.

  *   montage: @mczepiel<https://github.com/mczepiel>
  *   mozart: @tomdionysus<https://github.com/tomdionysus>
  *   puremvc: @cliffhall<https://github.com/cliffhall>
  *   sapui5: @schubertha<https://github.com/schubertha>
  *   somajs: @soundstep<https://github.com/soundstep>
  *   thorax: @eastridge<https://github.com/eastridge>
  *   TroopJS: @mikaelkaron<https://github.com/mikaelkaron>

**Comment by eastridge** [comment]
Thorax is abandoned, you can remove from todomvc, thanks!

**Comment by soundstep** [comment]
I'll have a look at soma.js in the next week. As soon as I get some time.

**Comment by mikaelkaron** [comment]
Looking at the [spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md#clear-completed-button) regarding the "clear completed" it says:

> Displays the number of completed todos, and when clicked, removes them. Should be hidden when there are no completed todos.

However, the text for this button is set via CSS [here](https://github.com/tastejs/todomvc-app-css/blob/master/index.css#L325). Am I missing something?

**Comment by samccone** [comment]
you are not missing anything @mikaelkaron, this change happened to break 3 integration tests across all projects :(

We are tracking it here, would love any input
https://github.com/tastejs/todomvc/issues/1215

**Comment by mikaelkaron** [comment]
Submitted tastejs/todomvc#1218 for TroopJS

**Comment by arthurvr** [comment]
> I'll take on updating the Polymer app (unless it's been started already).

@addyosmani ping ping ;)

**Comment by addyosmani** [comment]
Go for it!

**Comment by cliffhall** [comment]
I'm happy to update the PureMVC app but I'm watching this thread for confirmation that the CSS breakage of the "Clear completed" button noted above has been addressed. Until then I'm watching.

**Comment by soundstep** [comment]
@arthurvr Oh i just noticed you updated the soma.js ones I was bout to check. Thanks for that.
Cheers.

**Comment by arthurvr** [comment]
@cliffhall It's been fixed a while ago. Feel free to PR now :)

@schubertha You can look at the other apps as example. If the app was built without any CSS tweaking, the update should be as easy as updating dependencies to npm and including todomvc-app-css.

@soundstep Cheers! :beers:

@shepheb @kgrgreer I added FOAM to the list above. It just needs to be updated to use npm for dependencies. Anyone of you who's interested in working on that?

**Comment by arthurvr** [comment]
@urrgur In our opinion, no, not anymore :)

I removed mozart from the list as we deleted the example.

**Comment by arthurvr** [comment]
Whoops.

**Comment by fboechats** [comment]
I think now this issue is resolved.
