### ISSUE TITLE
Examples written in pure JavaScript.

### ISSUE THREAD

**Issue by atdotslashdot** [tastejs/todomvc#1114]
Great resource, thanks!
Is it correct to include react in this tab? A lot of the source appears to be in JSX.
I know you can use react without jsx but this isn't what this example does. Would this particular example be better placed in the Compile-to-JS tab?

**Comment by arthurvr** [comment]
> I know you can use react without jsx but this isn't what this example does. Would this particular example be better placed in the Compile-to-JS tab?

@tastejs/todomvc What do we think? I'm +1 for moving it.

**Comment by arthurvr** [comment]
@petehunt What do you think?

**Comment by samccone** [comment]
+1 I think it clearly falls under compile-to-js, since you are literally compiling the file :)

**Comment by passy** [comment]
Hm, I'm :-1: on this. JSX is really just a tiny bit of sugar on top of normal JS and completely optional. It doesn't provide any new semantics. I thought of the C2JS category more in terms of a showcase for other languages that provide new semantics and paradigms you can't express directly in JavaScript.

It would be easy to just desugar the JSX and use the normal JS code for the React example, but apart from making it easier to see which tab it belongs in, there isn't really any benefit in doing that.

Either way, I'm cool with whatever the majority thinks should happen. :)

**Comment by ColinEberhardt** [comment]
I'm with @passy - React apps are primarily JS, with just a little bit of sugar. Conceptually it is still very much JS.

**Comment by sindresorhus** [comment]
I'm with @passy.

**Comment by samccone** [comment]
kk :) I defer to the group
