### ISSUE TITLE
`Aria templates` example overwriting styles

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1120]
Followup on https://github.com/tastejs/todomvc/pull/1116. Seems like the Aria templates example is overwriting/forcing [some of the old UI](https://github.com/tastejs/todomvc/blob/master/examples/ariatemplates/js/view/TodoStyle.tpl.css#L47).

**Comment by sindresorhus** [comment]
@olaf-k

**Comment by olaf-k** [comment]
#1127 should take care of that.
