### ISSUE TITLE
Please add the option to compare 2 or more framework sources side by side

### ISSUE THREAD

**Issue by Emasoft** [tastejs/todomvc#1122]
Please add the option to compare 2 or more frameworks sources side by side.

**Comment by arthurvr** [comment]
Isn't this a feature request for your editor, not for todomvc?

**Comment by samccone** [comment]
not sure if this is a concern for todomvc... thoughts anyone?

**Comment by arthurvr** [comment]
Closing this as we already have this open issue: https://github.com/tastejs/meta/issues/3.
