### ISSUE TITLE
Aurelia App

### ISSUE THREAD

**Issue by KenPowers** [tastejs/todomvc#1147]
Would there be interest in an [Aurelia](http://aurelia.io/) TodoMVC app? I'm interested in making something with Aurelia and TodoMVC seems like a good project to start with.

Looking around I see some implementations already done [1](https://github.com/mhoyer/todomvc-aurelia) [2](https://github.com/sonnylazuardi/todomvc-aurelia).

**Comment by mhoyer** [comment]
Hi @KenPowers,

I am more or less [finished with it](https://twitter.com/pixelplastic/status/564717229724676096) but I struggle a lot on letting the [browser-tests](https://github.com/tastejs/todomvc/tree/master/browser-tests) pass. I currently have those issues:

0. Aurelia relies on [SystemJS](http://www.github.com/systemjs/systemjs). Thus, all content is loaded asynchronously when e2e browser-tests run. In [browser-tests/test.js#L35](https://github.com/tastejs/todomvc/blob/master/browser-tests/test.js#L35) there is a startup delay of `200ms` defined.
  - Increasing the `browser.sleep` delay to 3000 and running the `mocha` command with `--timeout 10000` I was able to let the first tests pass. But not all, read 3. to understand why.
  - I already tried to play around with [systemjs/builder](http://www.github.com/systemjs/builder), but couldn't get the [aurelia-bootstrapper](https://github.com/aurelia/bootstrapper) to be bundled and called correctly with my `app.js` and dependent modules.
0. Besides the poor loading performance for the e2e tests I also don't want to push this nasty `jspm_packages` folder into the example folder for Aurelia.
0. IMHO the latest [todomvc-app-css](https://github.com/tastejs/todomvc-app-css) and [todomvc-common](https://github.com/tastejs/todomvc-common) packages have a breaking layout change which makes the browser-tests fail - even with reference example with `backbone`.
```
  TodoMVC - backbone
    When page is initially opened
      √ should focus on the todo input field (93ms)
    No Todos
      √ should hide #main and #footer (283ms)
    New Todo
      √ should allow me to add todo items (850ms)
      1) "before each" hook
...
  1) TodoMVC - backbone "before each" hook:
     ElementNotVisibleError: element not visible
  (Session info: chrome=40.0.2214.111)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2...
...
   at projects\todomvc\browser-tests\page.js:117:11
```

**Comment by mhoyer** [comment]
Maybe this is helpful: https://github.com/SAAirey/aurelia-skeleton-navigation-bundling

**Comment by arthurvr** [comment]
Closing as it landed. https://github.com/tastejs/todomvc/pull/1163
