### ISSUE TITLE
BigPipe app

### ISSUE THREAD

**Issue by Swaagie** [tastejs/todomvc#1161]
As co-author of the framework I'd love to see a [BigPipe](https://github.com/bigpipe/bigpipe) powered app on TodoMVC.

Currently, we are finishing up the tests and docs for the milestone 1.0 release and we think it would be great to have BigPipe listed on TodoMVC. It excels at:

- Performance, html chunks are written to the response as fast as possible, the client will start rendering (and loading assets) as soon as the first headers are written.
- Asynchronous, different parts of the page (or basically the collection of pagelets) can be rendered async, making it an excellent framework for heavy dashboard or data-heavy apps.
- Modularity, each [pagelet](https://github.com/bigpipe/pagelet) can be endlessly extended and inherited from and ties the Model(any logic inside or outside the pagelet), View(plain template) and Controler(or Router) together

As reference, [browsenpm.org](http://www.browsenpm.org) and Nodejitsu's private npm UI already run on BigPipe and so far it has proven itself in production.

**Two things I was wondering about:**
1. How closely should we stick to the application structure as BigPipe is somewhat different from typical MVC, per example [browsenpm source code](https://github.com/nodejitsu/browsenpm.org/tree/pageletify)? Mainly due to pagelets fusing the M, V and C, bold new ideas right ;)
2. Why are the source codes of some node_modules included in the `index.html` template files of some examples, is that just to omit browserify?

Let me know what you think and if it would be a good addition to the TodoMVC family

**Comment by passy** [comment]
Hey @Swaagie, thanks for reaching out before sending a PR. :)

BigPipe looks really interesting, I'm actually surprised it took that long until a serious effort to replicate what Facebook has built comes around. We'll need to discuss this internally as this is quite different from the other apps and this blurs the line between a client- and server-side app.

On the other hand, we do allow Meteor which in many ways follows a similar concept.

**Comment by Swaagie** [comment]
Thanks for replying :)

Yeah meteor being there kinda convinced me to actually submit this. I agree on it being different from the more client orientated frameworks. But having the same modular and extendable pattern on the server side is valuable we think. We are creating an exciting (well @3rdeden mostly atm) middle layer as well, named [fittings](https://github.com/bigpipe/fittings) which allows bigpipe to work with any established client framework. So you should be able to do bigpipe+angular, bigpipe+ember, bigpipe+react, etc. whatever floats your boat

**Comment by arthurvr** [comment]
We discussed this and agreed that BigPipe was a little too far away from client-side MV* to be a good fit for TodoMVC. Therefore, it would be difficult to realistically compare it with other frameworks.

Keep up the nice work and thanks for reaching out to us! :dancer:
