### ISSUE TITLE
[PR] Rivets.js implementation

### ISSUE THREAD

**Issue by altmind** [tastejs/todomvc#1180]
This is new implementaion using rivetsjs https://github.com/mikeric/rivets - #1176

Rivets is tiny two-way binding library that is not opinionated and works well with all types of routers or models. It can also be considered "MVC" as it handles both changes on models, translates models to ui views and handle manual events.

I would say, that rivets is VERY similar to angularjs - they both are 2-way binding frameworks, they both use DOM-based views, they both define user events and bind model to dom in templates, they both have some sort of components(they are called binders in rivets) and filters(they are called formatters in rivets) and they both have the same data and behavior in controllers. Yey, I say that rivets is much simplier, less opinionated and much more composable(compatible with other frameworks).

Rivets is quite popular(2100 stars) and our company had enough experience to say that rivets is very mature. There was also a request for rivets #337 (sorry, this implementation does not use backbone and requirejs)

This implementation is using new UI (and thats why 'Clear completed button' tests fail)
This implementation also depends on director for rouring and jquery for dom manipulations.

Tests output: https://gist.github.com/altmind/16a38c0f79c2aceb89c8 (again, some tests fail because of breaking changes in new UI: #1110)

**Comment by benliebert** [comment]
rivetsjs is the BEST Javascript framework I've come across and its current omission from todomvc is surprising.  Hopefully altmind's work can change this - cheers.

**Comment by arthurvr** [comment]
@benliebert @altmind @mikeric The PR https://github.com/tastejs/todomvc/pull/1226 was sooo close so it's super sad we had to close it due to inactivity. If anyone of you is interested in finishing it up, we're still interested :)

**Comment by arthurvr** [comment]
I just closed another PR for this implementation due to inactivity :( Same things as before, we're still willing to add an example for rivets, if anybody is interested in finishing up #1295.

**Comment by arthurvr** [comment]
I'm going to close this. A PR is still welcome but if nobody's interested in finishing one we're not going to add an example :wink:.
