### ISSUE TITLE
Invitation to two new core team members

### ISSUE THREAD

**Issue by addyosmani** [tastejs/todomvc#1189]
TodoMVC would like to invite two new members to the core engineering team. These individuals have been an immense help to the project of late and we feel would have a huge impact to the project long-term. They are:

@arthurvr and @samccone 

First, a huge thank you for your efforts Arthur and Sam. Second, if you feel comfortable accepting the invitation, we would be happy to add you to the site and provide you direct commit access to master :) 

You are of course entirely free to turn down the invite, but we hope you'll accept! :star: 

cc @tastejs/todomvc as an FYI.

**Comment by samccone** [comment]
:smile:

**Comment by sindresorhus** [comment]
:+1: 

![tumblr_mlf8zt33uq1qdlh1io1_400](https://cloud.githubusercontent.com/assets/170270/6577940/32f730e4-c77c-11e4-853d-11f80920260d.gif)

**Comment by samccone** [comment]
![](http://31.media.tumblr.com/2d9385c3b1ae84e7d5e56d9e7b330857/tumblr_n0i2nfC6QB1qekx3go1_250.gif)

**Comment by stephenplusplus** [comment]
Thank you for all of your work @arthurvr and @samccone, and welcome to the team!

**Comment by passy** [comment]
Woo! Thanks for the contributions you two and welcome! :)

**Comment by jasonLaster** [comment]
![](http://i.giphy.com/MC9lNbEWeuQBa.gif)

**Comment by arthurvr** [comment]
I'm in! Thanks all of you!

**Comment by samccone** [comment]
good to close now :+1: ?

**Comment by sindresorhus** [comment]
First, add yourself to the readme and site ;)

**Comment by addyosmani** [comment]
:cake:

**Comment by arthurvr** [comment]
Seems like we're gonna have a design issue in the footer. Somebody suggestions?

**Comment by passy** [comment]
@arthurvr Added you and Sam and got (temporarily) rid of the last names, to make you guys fit. But would indeed be nice if we found a better way for that. Perhaps we could move ourselves out of the footer and do something similar to yeoman.io instead?
