### ISSUE TITLE
Missing platform.js.map file for home page

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1191]
![screen shot 2015-03-10 at 4 26 27 pm](https://cloud.githubusercontent.com/assets/883126/6584532/680d39de-c742-11e4-9d2a-fcfbae079b73.png)

Given that this is a site targeted at developers, I think we should add in the map file :) easy win, simple fix.

thoughts?

**Comment by sindresorhus** [comment]
:+1:

**Comment by samccone** [comment]
I went for it
