### ISSUE TITLE
Replace old style homepage screenshot

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1192]
Another easy win:

![screen shot 2015-03-10 at 4 26 36 pm](https://cloud.githubusercontent.com/assets/883126/6584561/8929ec70-c742-11e4-93e5-6ec22a130091.png)

Just need a new screenshot with the new UI

**Comment by arthurvr** [comment]
Sure. I'll take this one.

**Comment by arthurvr** [comment]
The homepage will, in general, need some design updates. It doesn't really match the design of the apps.

**Comment by samccone** [comment]
yeah, just pointing out some simple wins we can get :)

**Comment by sindresorhus** [comment]
:+1:
