### ISSUE TITLE
Fix google page speed score

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1193]
No reason we can not get into the :green_apple: on this one.

I figure this should be another easy win.

https://developers.google.com/speed/pagespeed/insights/?url=todomvc.com&tab=mobile
#### for bookkeeping

![screen shot 2015-03-10 at 4 32 42 pm](https://cloud.githubusercontent.com/assets/883126/6584663/28f71048-c743-11e4-90a6-f9ff3fff4f6e.png)
![screen shot 2015-03-10 at 4 32 45 pm](https://cloud.githubusercontent.com/assets/883126/6584665/2a5d585c-c743-11e4-98a2-05d6a78c61c0.png)

**Comment by himanshuchauhan** [comment]
Should  I do this now?

**Comment by addyosmani** [comment]
@himanshuchauhan thanks for the offer. We're tackling this over in https://github.com/tastejs/todomvc/pull/1533. That said, any help improving it further after that work lands would be appreciated.

**Comment by abhidevmumbai** [comment]
Is this still open?

**Comment by stmoreau** [comment]
@addyosmani maybe this issue should get closed.

**Comment by FadySamirSadek** [comment]
@stmoreau the PR for this issue has not been merged if you wish you can follow from there and get it shipped

**Comment by madarsbiss** [comment]
if this is done it should be closed :)
