### ISSUE TITLE
Reconsider why we are using polymer for the home page.

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1200]
The home page is quite simple, using polymer seems almost like overkill, when we can hand spin some bespoke :sparkles:  javascript.

##### Why?

If we want to optimize the speed of the initial page render we can significantly drop the js payload thus decreasing the time to render. 

It looks like currently we don't get a paint until 1 second in on refresh

![screen shot 2015-03-12 at 11 52 19 pm](https://cloud.githubusercontent.com/assets/883126/6632815/1a4ffad8-c913-11e4-900d-9e82e359c69d.png)

From there in the next 500 or so ms the page is not yet "ready"

![screen shot 2015-03-12 at 11 52 51 pm](https://cloud.githubusercontent.com/assets/883126/6632826/4d4d6eac-c913-11e4-97fc-b44a27323adc.png)

only around 800 or so ms in do we start getting the page into the initial correct render state

![screen shot 2015-03-12 at 11 53 03 pm](https://cloud.githubusercontent.com/assets/883126/6632829/589e4c40-c913-11e4-8a56-f78fa3224d1b.png)

I could be totally misreading the data on this one however. 

But my hypothesis is that the initial render is still slowed down by the fact that we using polymer, as compared to simply just having our page static with a dash of the good ol JScript. 

----------

You may be thinking:

##### This is dumb and a micro optimization that is not needed

Fair enough, just something I have been noodling on when taking a look at the perf of this page. no harm and we can just close this sucker out :finnadie:

**Comment by sindresorhus** [comment]
I'm ok with this. The polymer usage is indeed a bit overkill just for the tabs.

Pinging in @passy as he's the one that added it.

**Comment by addyosmani** [comment]
Let's have a chat about whether Polymer 0.8 can tackle the paint issues we're seeing here. Failing that there's the Material Design vanilla JS/CSS components we can use from Starter Kit.

**Comment by podefr** [comment]
you guys need some guidance on a good lib to use for a website with a few interactions? :)

**Comment by sindresorhus** [comment]
Ping @passy

**Comment by sindresorhus** [comment]
@podefr Just comment your recommendation. No need to ask for permisison to suggest something ;)

**Comment by passy** [comment]
Sorry for the very late reply, but yes if we can improve the load time by switching to MDL or something entirely different, then I'm all :+1: for it!

**Comment by ebidel** [comment]
The site is using an old version of the webcomponents (full) polyfill and polymer 0.5 Updating to 1.0 will go a long way.

**Comment by passy** [comment]
I'll try to take care of the Polymer 1.0 homepage update.

**Comment by ebidel** [comment]
Looks the the improvements made a difference. First paint is now ~350ms, which is well under RAIL. 
A lot of the elements also received perf updates in the last several months, so I suspect that is also helping. There are now 18 custom element instances on the page (not sure what it was before)...but that is very low :)

BTW, you could also add `async` to the web components polyfill to take it out of the rendering equation and/or dynamically load it.

**Comment by arthurvr** [comment]
Yeah, very nice improvement :) IMHO it's okay for now and we can close this issue.

**Comment by addyosmani** [comment]
Agree. Let's close this one up!
