### ISSUE TITLE
App breakage should be a factor in removal.

### ISSUE THREAD

**Issue by addyosmani** [tastejs/todomvc#1203]
Maybe we should include some verbiage in our acceptance rules to cover long term breakage of an implementation. This is a particularly poor experience for users and doesnt look good for authors either.

Like, if an app has been broken for N releases without update it gets removed until fixed.

This has the potential to encourage more authors to actively check in.

**Comment by arthurvr** [comment]
Yes, I can only agree with that. :+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by passy** [comment]
:+1:

**Comment by arthurvr** [comment]
@tastejs/todomvc I think we all agree on this, so do we want to document this somewhere, or can we close the issue?

**Comment by samccone** [comment]
I think we can close this since we all agree, just good to have documented in the issue right?¿

**Comment by addyosmani** [comment]
Agreed. We should prob document somewhere though. Wiki?

**Comment by arthurvr** [comment]
Seems fine. Will take care of that this weekend.

**Comment by arthurvr** [comment]
Anyone an idea where we should have this documented? Maybe we should have a whole paragraph in the `contributing.md` about being around to help us maintain your app after submitting it?

**Comment by arthurvr** [comment]
I would honestly love it if we could say something like

> Please think about the fact that contributing a new app means more than just
a one-off pull request submitting the app. When the app gets included on the site,
you will need to help use maintaining the app and help us to solve issues with the
implementation. If the app breaks for a decent amount of time, we will (temporary)
remove it from the site, until somebody opens a PR to fix the raised issues.

but guess it's a little too much?
