### ISSUE TITLE
Early Angular 2 example(s)

### ISSUE THREAD

**Issue by passy** [tastejs/todomvc#1204]
There was a cool talk at ng-conf about implementing TodoMVC with Angular 2 and TypeScript: https://t.co/bOQzF04Z9q

We generally don't include WIP frameworks, but we've also been flexible when it comes to making the decisions and in this case it should be pretty crystal clear that there's a lot of interest from the community in this development. One particularly interesting factor here is that Angular 2 is going to support writing applications in both TS, ES6 and ES5 which is a great opportunity to show how they look next to each other - exactly what TodoMVC is about.

In addition to agreement from the team here, we'd obviously also need support from the Angular folks or someone closely following the development to keep the examples up to date.

What are your thoughts on this? :+1: / :-1:?

**Comment by sindresorhus** [comment]
:+1:

**Comment by samccone** [comment]
:+1:

**Comment by addyosmani** [comment]
:+1:

**Comment by madvas** [comment]
:+1:

**Comment by josedepaz** [comment]
:+1:

**Comment by josedepaz** [comment]
:+1:

**Comment by josedepaz** [comment]
:+1: 

Also in the ng-conf, John Papa spoke about the style guide, I think it would be good to implement todoMVC in AngularJS using good practices found there.

https://github.com/johnpapa/angular-styleguide

**Comment by arthurvr** [comment]
Close this as we landed an Angular 2 implementation :star:

**Comment by samccone** [comment]
:deciduous_tree:
