### ISSUE TITLE
Update `epitome` example

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1209]
The Epitome example will need to be updated to the latest version of epitome.

cc @DimitarChristoff

**Comment by arthurvr** [comment]
ping @DimitarChristoff - are you interested?

**Comment by DimitarChristoff** [comment]
oh sorry forgot completely. changes nearly done. got to pull upstream and
cleanup. prolly pr tomorrow night sorry.

On Sunday, April 26, 2015, Arthur Verschaeve <notifications@github.com>
wrote:

> ping @DimitarChristoff <https://github.com/DimitarChristoff> - are you
> interested?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tastejs/todomvc/issues/1209#issuecomment-96392044>.
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by arthurvr** [comment]
Awesome @DimitarChristoff!

**Comment by arthurvr** [comment]
ping @DimitarChristoff

**Comment by arthurvr** [comment]
Hey @DimitarChristoff - Are you still willing to pick this up?

**Comment by sindresorhus** [comment]
I think we should just remove it. No response from author and the framework itself was last updated Oct 10, 2014.

**Comment by arthurvr** [comment]
Yep, sgtm.

**Comment by samccone** [comment]
:+1:

**Comment by DimitarChristoff** [comment]
sorry there is no sense in maintaining it as MooTools scene has died out
completely. remove it pls.

On Monday, August 24, 2015, Sam Saccone <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tastejs/todomvc/issues/1209#issuecomment-134321491>.
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff
