### ISSUE TITLE
what is base.js?

### ISSUE THREAD

**Issue by qeantx** [tastejs/todomvc#1211]
can i ask a question?
i downloaded and execute project, and i see 
todomvc/examples/backbone_require/index.html
but, i don't understand, why need base.js in index.html?
todomvc/examples/backbone_require/node_modules/todomvc-common/base.js
and i don't understand, what is this?

**Comment by arthurvr** [comment]
As you can see in the readme of [todomvc-common](https://github.com/tastejs/todomvc-common):

> Common TodoMVC utilities used by our apps

It's just a file that handles things like analytics, the learn bar, templating utility, ... Would you suggest us to clarify that somewhere else?

**Comment by urrgur** [comment]
ok

**Comment by ryan-w-moore** [comment]
I would suggest that the base.js file is another example of an opportunity for novice developers to learn from. If the base.js file was better described, including how it fits into the overall todomvc-app in its general application across all examples and how it fits/works within the individual examples it would better highlight the overall mission of the app to help those either just starting out or as I've experienced myself, that plateau between beginner and intermediate javascript learning and experience. perhaps better commentary or additional descriptive content in the overall readme file?
