### ISSUE TITLE
Clear completed integration tests are failing as a result of the new UI

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1215]
since we now set `clear completed` in CSS https://github.com/tastejs/todomvc-app-css/blob/master/index.css#L325 the integration tests that we have no longer pass. 

This is unfortunate because it impacts any app that has upgraded to the new UI. We should investigate how we would like to resolve it, since it would be great to get a passing suite once more.

:+1: :sparkles: :spaghetti:

**Comment by evverx** [comment]
`clear completed` in CSS breaks Firefox: [Firefox: Click on CSS pseudo element doesn't trigger click event](http://stackoverflow.com/questions/21858942/firefox-click-on-css-pseudo-element-doesnt-trigger-click-event).
IE11 doesn't show button at all
![](https://leto13d.storage.yandex.net/rdisk/4203feb601316ef790830a5d67db152faf6281d83a1f3078dd6f52d10046259d/inf/-DDIprZESaDwZiD2vmMTyP9jZsi2c0xSPU7dGe4iReJ95UHO5BslnUR4SLTm_7jvWkbpNvr8MYSHkj3mtQ9_iQ==?uid=0&filename=2015-03-20%2007-54-31%20IE11%20-%20Win7%20%5BRunning%5D.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=f263067d0f905c659bb803d917f2a372&force_default=no)

**Comment by arthurvr** [comment]
I'll hopefully find some time to look into this.

**Comment by samccone** [comment]
Fixed via 
https://github.com/tastejs/todomvc-app-css/pull/7
