### ISSUE TITLE
Policy about separated `require.js` apps?

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1216]
Discussion started here: https://github.com/tastejs/todomvc/commit/79c34b30006f91f35b14295087bcc477ba8ea990#commitcomment-10202521. We already decided to remove `backbone-marionette-requirejs` (https://github.com/tastejs/todomvc/commit/79c34b30006f91f35b14295087bcc477ba8ea990).

> the backbone marionette require version can be removed, i don't think module systems are new enough anymore to warrant a separate version.

-

We have quite a bunch of these `require.js` apps, and are gonna stay getting more and more. It's a PITA to maintain two different versions of those apps. Personally I also feel like module systems aren't new enough anymore to have separated apps for them.

Apps that fall under this:

* angularjs_require
* backbone_require
* canjs_require
* emberjs_require
* knockoutjs_require
* somajs_require

**Comment by samccone** [comment]
:+1: to dropping

**Comment by arthurvr** [comment]
I'm also a huge +1 to dropping.

**Comment by sindresorhus** [comment]
Cyclopean :+1:

I was always against this.

**Comment by mikaelkaron** [comment]
Not that it matters but I'm +1 on dropping to (the only reason I care is that that would hopefully rename `troopjs_require` to simply `troopjs`)

**Comment by arthurvr** [comment]
The troopjs example isn't gonna be effected by this, as there is no duplicating, there is only one app.

> that would hopefully rename troopjs_require to simply troopjs

Maybe we should indeed just rename it. @tastejs/todomvc Thoughts?

**Comment by addyosmani** [comment]
I'm :+1: on renaming the Troop example to just TroopJS. Definitely avoids confusion - good idea @arthurvr! :star:
