### ISSUE TITLE
What happend to your blog?

### ISSUE THREAD

**Issue by gruppjo** [tastejs/todomvc#1217]
Not sure, whether this is the right place to address this, but it's the only place I found to contact you.

You're blog seems to be down, in case you weren't aware of the fact.
http://blog.tastejs.com/ redirects to https://ghost.org/?utm_source=roon.io&utm_medium=redirect&utm_campaign=ghost

I'd like to quote your excellent article *Yet Another Framework Syndrome* in our company's blog. Can you provide any information on whether this is a temporary or permanent outage?

**Comment by sindresorhus** [comment]
It's waiting on @addyosmani to update the DNS records to the new blog at https://medium.com/@tastejs

**Comment by addyosmani** [comment]
I've dropped Sindre a mail about this with some follow-up questions :)

**Comment by addyosmani** [comment]
The tl;dr of this is that medium custom domains are currently still private so we'll need to do a hard forward to the new location for the blog. I assume that everyone is fine with this. Will get this taken care of soon.

**Comment by sindresorhus** [comment]
Yes.

**Comment by arthurvr** [comment]
> Will get this taken care of soon.

@sindresorhus @addyosmani any status update?

**Comment by sindresorhus** [comment]
From earlier email to @addyosmani:

> I guess you can delete the CNAME we used for the previous blog platform and use a web redirect instead for now: https://wiki.gandi.net/en/domains/management/domain-as-website/forwarding

This is needed since medium.com doesn't yet support custom domains.

**Comment by arthurvr** [comment]
@sindresorhus Sounds good to me. Who can set that up for us? @addyosmani I guess?

**Comment by sindresorhus** [comment]
Yes

**Comment by addyosmani** [comment]
I've setup the subdomain redirect rules in gandi.net and this should be live before long at blog.tastejs.com (currently does the roon direct to ghost).

**Comment by samccone** [comment]
thanks @addyosmani !!!!!!!!

**Comment by arthurvr** [comment]
Yay, thanks everyone. Going to close this now :)

**Comment by arashkhan** [comment]
How can I  move out of your fucking conversation and do not receive email

**Comment by samccone** [comment]
You can click this button :)

![screen shot 2015-10-01 at 1 15 23 pm](https://cloud.githubusercontent.com/assets/883126/10232601/80262808-683e-11e5-87f2-cc42a88e47e8.png)

Happy Thursday to you as well :jack_o_lantern:
