### ISSUE TITLE
Drop plastronjs app?

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1219]
Kinda same thing as with https://github.com/tastejs/todomvc/issues/1173. Latest release was on on April 23, 2013: https://github.com/rhysbrettbowen/PlastronJS/releases. There don't seem to be any active committers on the project.

**Comment by samccone** [comment]
yeah :+1: 
https://github.com/rhysbrettbowen/PlastronJS/pulse/monthly

**Comment by addyosmani** [comment]
:+1:
