### ISSUE TITLE
Montage app totally broken!

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1222]
/cc @mczepiel

**Comment by mczepiel** [comment]
Thanks for the heads up, I've brought this to the attention of @marchant /cc @rayshan as I'm a little booked right now myself.

**Comment by samccone** [comment]
it is worth nothing that it has been broken for some time, it might be best to remove from the site and reintroduce when someone fixes it, as compared to having a broken version on the site.

**Comment by arthurvr** [comment]
Definitely. That's what's being discussed in https://github.com/tastejs/todomvc/issues/1203. Would not do it directly as the issue is just opened, but if it isn't fixed quick that seems reasonable to me.

**Comment by marchant** [comment]
Working on it, expect a PR in the next few days

**Comment by samccone** [comment]
:+1: thanks @marchant

**Comment by arthurvr** [comment]
Thanks @marchant!

**Comment by arthurvr** [comment]
Friendly ping

**Comment by marchant** [comment]
I did submit a PR yesterday, need more feedback to adress some concerns that were raised

**Comment by arthurvr** [comment]
aggrr. Didn't see that one. Shall take a look :)
