### ISSUE TITLE
Meteor + AngularJS app

### ISSUE THREAD

**Issue by madvas** [tastejs/todomvc#1227]
Hi guys,

If I created, would you accept [Angular-Meteor] todomvc app? It's relatively new approach to create real-time full stack using two super popular frameworks. 

[angular-meteor]: http://angularjs.meteor.com/

**Comment by arthurvr** [comment]
Hey! We briefly discussed this and decided that it's not worth it to include a new example for this. We already have some Angular examples (6!) and a Meteor example,  and wanted to keep off from including many other composite examples.

Thanks for reaching out and thanks for the suggestion. Oh, also sorry for having it take so long to get back at you.
