### ISSUE TITLE
Get rid of completed todos count

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1234]
As of https://github.com/tastejs/todomvc/commit/a5c2dc6c7c21cd4ef4e5ec7b6da63635f0d34647 the number of completed todos isn't needed anymore in the `clear completed` button. It can be removed from existing apps.

Ref https://github.com/tastejs/todomvc-app-css/pull/7.

**Comment by arthurvr** [comment]
Dropping in the app list so we can easily follow this up. I'm already working on some of them as well as the tests.

- [ ] ampersand
- [ ] angular-dart
- [x] angularjs
- [ ] angularjs_require
- [ ] angularjs-perf
- [ ] ariatemplates
- [ ] atmajs
- [ ] backbone
- [ ] backbone_marionette
- [ ] backbone_require
- [x] batman
- [ ] canjs
- [ ] canjs_require
- [ ] chaplin-brunch
- [ ] closure
- [ ] componentjs
- [ ] cujo
- [ ] derby
- [ ] dijon
- [ ] dojo
- [ ] duel
- [ ] durandal
- [x] emberjs
- [ ] enyo_backbone
- [ ] epitome
- [ ] exoskeleton
- [ ] extjs_deftjs
- [ ] firebase-angular
- [ ] flight
- [ ] gwt
- [ ] jquery
- [ ] kendo
- [ ] knockback
- [ ] knockoutjs
- [ ] knockoutjs_require
- [ ] lavaca_require
- [ ] meteor
- [ ] mithril
- [ ] montage
- [ ] mozart
- [ ] olives
- [ ] plastronjs
- [ ] polymer
- [ ] puremvc
- [ ] ractive
- [ ] rappidjs
- [ ] react
- [ ] react-backbone
- [ ] sammyjs
- [ ] sapui5
- [ ] serenadejs
- [ ] socketstream
- [x] somajs
- [ ] somajs_require
- [ ] spine
- [ ] stapes
- [ ] stapes_require
- [ ] troopjs_require
- [ ] typescript-angular
- [ ] typescript-backbone
- [ ] vanilladart
- [ ] vanillajs
- [ ] vue
- [ ] yui

**Comment by arthurvr** [comment]
Just so I don't forget it, this would also fix https://github.com/tastejs/todomvc/issues/1252.

**Comment by arthurvr** [comment]
@shepheb @Lastalas @tomdionysus @krebbl @mckamey Any of you interested in submitting a PR to fix the your apps? The only thing that needs to happen is to update it todomvc-app-css to 1.0.4 and to remove the count from your app. If your app isn't updated to the new UI yet, you of course shouldn't update todomvc-app-css. See https://github.com/tastejs/todomvc/pull/1245 for many examples.

**Comment by mckamey** [comment]
@arthurvr I am interested in updating for DUEL. Life has been busy but will check it out soon.

**Comment by arthurvr** [comment]
Removed mozart as the example is removed. @mckamey That would be awesome! still interested?

**Comment by arthurvr** [comment]
@mckamey No worries. I did it myself :)

**Comment by arthurvr** [comment]
@dprotti @ColinEberhardt Anyone of you interested in fixing the GWT app?

**Comment by dprotti** [comment]
Yes, I can work on it next weekend.

**Comment by arthurvr** [comment]
Thanks @dprotti. Appreciate it :)

**Comment by arthurvr** [comment]
@marchant Are you interested in taking care of this for the montage app? Preferably after the other PR landed.

**Comment by sindresorhus** [comment]
So close to finishing this.

**Comment by arthurvr** [comment]
ping @dprotti, are you still interested? That would be super great.

**Comment by dprotti** [comment]
Created PR #1419

**Comment by arthurvr** [comment]
Awesome, thanks.

**Comment by marchant** [comment]
Yes, we'll do, we're wrapping up a couple of issues we found in Firefox and will do another PR for this

**Comment by arthurvr** [comment]
@marchant Thanks. A PR for this would be super cool.

**Comment by arthurvr** [comment]
ping @marchant

**Comment by arthurvr** [comment]
We dropped the montage app so closing this now. Thanks everyone.

**Comment by marchant** [comment]
Just as we had fixed our bugs with pointer events and were ready wrap it up, can you re-open please?

Thanks!

> On Oct 1, 2015, at 10:22 PM, Arthur Verschaeve <notifications@github.com> wrote:
> 
> We dropped the montage app so closing this now. Thanks everyone.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/tastejs/todomvc/issues/1234#issuecomment-144926705>.
> 


 <http://montagestudio.com/>
montagestudio.com <http://montagestudio.com/>	 	
Benoit Marchant <mailto:benoit@montagestudio.com>
CEO & Founder
1290 Oakmead Parkway, Ste 111
Sunnyvale, CA 94085
(1) 408.621.4874 mobile <tel:+1-408-621-4874>
Profile <http://www.linkedin.com/in/benoitmarchant> |  @benoitmarchant <http://twitter.com/benoitmarchant>

**Comment by samccone** [comment]
:+1: sure thing thanks @marchant !

**Comment by marchant** [comment]
Thanks!

> On Oct 1, 2015, at 10:36 PM, Sam Saccone <notifications@github.com> wrote:
> 
> Reopened #1234 <https://github.com/tastejs/todomvc/issues/1234>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/tastejs/todomvc/issues/1234#event-424949260>.
> 


 <http://montagestudio.com/>
montagestudio.com <http://montagestudio.com/>	 	
Benoit Marchant <mailto:benoit@montagestudio.com>
CEO & Founder
1290 Oakmead Parkway, Ste 111
Sunnyvale, CA 94085
(1) 408.621.4874 mobile <tel:+1-408-621-4874>
Profile <http://www.linkedin.com/in/benoitmarchant> |  @benoitmarchant <http://twitter.com/benoitmarchant>

**Comment by samccone** [comment]
@marchant I reopened the original PR, I will keep this issue closed however since as @arthurvr said the app is temporarily not on the site (so it is not an issue) :)
