### ISSUE TITLE
A question about "this"

### ISSUE THREAD

**Issue by Fishfaceeast** [tastejs/todomvc#1236]
path: todomvc/examples/backbone/js/views/app-view.js

Line 31-34, 
why not just use "this.allCheckbox = $('#toggle-all')[0];" instead of 
"this.allCheckbox = this.$('#toggle-all')[0];"?

**Comment by ryantan** [comment]
IIRC this.$ queries within the context of the view. So '#toggle-all' matches only #toggle-all within the view instead of the whole dom.

**Comment by arthurvr** [comment]
Exactly what @ryantan said ;)
