### ISSUE TITLE
Remove "-webkit-filter: blur(1px);" for countries where April fools' day is not celebrated :p

### ISSUE THREAD

**Issue by frankcortes** [tastejs/todomvc#1243]
Haha! Nice try, TodoMVC! :+1:

**Comment by samccone** [comment]
https://github.com/tastejs/todomvc/commit/41aaa9a024bce4834c37b9e84180ff4825d1eb1b

hhahahaha

**Comment by arthurvr** [comment]
lol :lollipop:

**Comment by samccone** [comment]
#wontfix :+1:

**Comment by bkeyvani** [comment]
LOL, You got me TodoMVC. I thought this was a bug and was going to submit an issue.
