### ISSUE TITLE
Add page with all resources in learn.json

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1244]
We should have a page on the site listing all resources in `learn.json`. Might be a really popular bookmark. Also, an `edit on github` button to encourage contributions to the list. 

Credits to @stephenplusplus for the idea. I'm definitely +1. If everybody likes the idea I can work on that.

**Comment by stephenplusplus** [comment]
Thanks for taking the lead on this one! :beers:

**Comment by sindresorhus** [comment]
:+1:

**Comment by mriccia** [comment]
@sindresorhus  Do you still need this to be created? I'd be happy to help out

**Comment by samccone** [comment]
:+1: if you are interested, you have our full support @mriccia :)

**Comment by mriccia** [comment]
@samccone :+1: amazing, I'll give it try! 
I may need some assistance as it is (kinda) my first OSS contribution, but seems like a good way to get started!
First question: should a page be generated from the json file? Or client-side rendering? I can see the file is exposed -> http://todomvc.com/learn.json but would make more sense if a static file would be generated IMO

**Comment by samccone** [comment]
I am totally fine with client side rendering :) keeps the complexity of our build process low

**Comment by mriccia** [comment]
Cool! I'll take a stab at it, will probably use a Underscore template or something similar. 
Will post some details once I start getting somewhere (or come up with more questions :) )
Thank you for your help so far! :)

**Comment by mriccia** [comment]
@samccone I got something working but have some questions around where's best to keep things and whether it's OK to use certain things, what's the best forum for asking those questions? 
Should I just post them here?

**Comment by samccone** [comment]
you can post them there, or open up a PR and we can chat there.

Thanks!

**Comment by mriccia** [comment]
Ok I'll put them here, what I've got is not really PR ready.

- Where should I place the .html file? at the root of the repo?
- I have seen Polymer components being used on index.html, is it OK to use Polymer components on the Learn page?
- I am using most of the code from here: https://github.com/tastejs/todomvc-common/blob/master/base.js but it's just copied over and adjusted. Do you think I should refactor it so that I can extend it? Or is it OK to keep it as separate files?
- the learn.json file contains a template at the very end of the page, as I may use a different template, should I place it in that object as well?

Apologies for the long list!

**Comment by mriccia** [comment]
Hi @samccone,
from the previous list, could you just get back to me on the first and last questions? Ignore the other two.

Also I had a first attempt at this, I am not really a creative person, so just want to get your opinion on my first attempt. Any suggestions on things it should contain? It's all in my fork of the repo if you want to take a look.

![todo_attempt](https://cloud.githubusercontent.com/assets/5655093/11616164/fe5c6f86-9c6c-11e5-9d02-291af677e6f3.JPG)

**Comment by samccone** [comment]
+1 to keep the template separate 
+1 to refactor base.js to be extendable... however that is hard to say 100% without seeing the code

The screen shot looks awesome PS, I am really excited to see this land. Thanks again for this work :+1:

**Comment by mriccia** [comment]
Thank you for those answers, I'll work on those and send a PR when done.
And thank you for the feedback, very happy to help!

**Comment by samccone** [comment]
@mriccia Let me know if I can be of any more help!

**Comment by tarang9211** [comment]
hello everyone! is still issue still open for help?

**Comment by swapnilaga3** [comment]
hello everyone, is the issue still open?

**Comment by Gitcat711** [comment]
Hello , anyway I can contribute?

**Comment by kkavita92** [comment]
Hey, is this issue still open?

**Comment by FadySamirSadek** [comment]
This one has already been tackled at #1552 but the PR is a bit old feel free to go there and check for things needed to be added or modified

**Comment by addyosmani** [comment]
Hey folks. As Fady mentioned over in #1552, we could really use a second look at that PR given age just to make sure it's still doing the work intended. We can merge it after if so.

**Comment by FadySamirSadek** [comment]
closed in favor of #1552
