### ISSUE TITLE
Investigate angular app memory leak

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1254]
https://github.com/tastejs/todomvc/pull/1223#discussion_r27026063

**Comment by samccone** [comment]
:white_check_mark: leak verified

#### Steps to reproduce 

1. open up the angular example
2. add 9 todos
3. hit the x next to each todo
4. check node count

#### Before Fix
![screen shot 2015-04-07 at 1 35 04 pm](https://cloud.githubusercontent.com/assets/883126/7029367/271a1e66-dd2b-11e4-9114-a3a7eef97c00.png)


#### After Fix
![screen shot 2015-04-07 at 1 35 52 pm](https://cloud.githubusercontent.com/assets/883126/7029370/2c20786a-dd2b-11e4-9e6b-cefb3a2f8a41.png)


#### The problem code
https://github.com/tastejs/todomvc/blob/master/examples/angularjs/js/directives/todoEscape.js#L14


#### The patch

```patch
		return function (scope, elem, attrs) {
			elem.bind('keydown', function (event) {
				if (event.keyCode === ESCAPE_KEY) {
					scope.$apply(attrs.todoEscape);
				}
			});
                       
+           scope.$on('destroy', function () { 
+             elem.unbind('keydown');
+           }
         };
```


#### Takeaways

##### Angular 
* Should angular yell at you when you manually bind to the element?
* Should the angular docs make it clear that binding to a raw element is leak prone unless you use $destroy?

##### Chrome Dev Tools

* Should there be some kind of obvious alert in the profiler when a node is removed that still has listeners bound?
* Should there be some kind of indicator or "stale" node list that is user friendly to see these kind of issues?


cc @addyosmani

**Comment by arthurvr** [comment]
wow. Thanks Sam! :+1:  

> Should the angular docs make it clear that binding to a raw element is leak prone unless you use $destroy?

Sure. Open a docs issue and I think they may be willing to improve this.

**Comment by Garbee** [comment]
> Should there be some kind of obvious alert in the profiler when a node is removed that still has listeners bound?

Sounds very reasonable that the DevTools could do something to alert the developer to this.

**Comment by samccone** [comment]
:boom:
