### ISSUE TITLE
Angular Style Guide from John Papa

### ISSUE THREAD

**Issue by josedepaz** [tastejs/todomvc#1255]
In the last ng-conf, John Papa spoke about the style guide, I think it would be good to implement todoMVC in AngularJS using good practices found there. What do you think about it?

https://github.com/johnpapa/angular-styleguide

**Comment by addyosmani** [comment]
I would defer to @igorminar for a call on this. If this style guide is generally considered best practice then sure. If not I would prefer the Angular team's preferences on style be maintained.

**Comment by arthurvr** [comment]
@IgorMinar WDYT?

**Comment by josedepaz** [comment]
Thanks for your comments, so let's wait for @IgorMinar

**Comment by samccone** [comment]
going to close until we get a response from @IgorMinar we can reopen when we do
