### ISSUE TITLE
Bring back Maria MVC ...

### ISSUE THREAD

**Issue by jamesladd** [tastejs/todomvc#1256]
Removing Maria MVC's Todo example is setting a bad example, please bring it back.

As I understand it you removed the example because Maria MVC is marked as finished or hasn't had updates in a few years. That's because it works and for the set of usecases it addresses it has resolved known bugs. 

So the more solid the code the more likely you are to remove it in favour of less solid bug ridden code?
This is ludicrous.

I have used Maria MVC in production on several occasions and it is simply fantastic. Simple, clean and most of all complete and bug free. The fact it doesn't have lots of updates is a winning proposition.

**Comment by samccone** [comment]
@jamesladd mind migrating this comment here
https://github.com/tastejs/todomvc/issues/1173#issuecomment-90702350
