### ISSUE TITLE
Polymer items array are not in sync with (un)checked item

### ISSUE THREAD

**Issue by gnjec** [tastejs/todomvc#1257]
Clear completed button shows incorrect value.

This issue can be resolved like this:
```javascript
    // td-item.html
    ...
    itemChangeAction: function() {
	    setTimeout(function(self){self.fire('td-item-changed')}, 0, this);
	    // this.fire('td-item-changed');
    },
```
but there must be a better way :)

**Comment by gnjec** [comment]
This is in Firefox. 
In Chrome and IE11 is ok.

**Comment by arthurvr** [comment]
Thanks for reporting this! I'm able to reproduce it. The count inside of the clear completed button itself is going to get removed (https://github.com/tastejs/todomvc/pull/1245), but this is still worth looking into. The button appears at the wrong moments it seems. @addyosmani you've got an idea?

**Comment by gnjec** [comment]
![1257](https://cloud.githubusercontent.com/assets/11833945/7067524/28b95348-decc-11e4-8e5f-bbca59a7cad9.png)

**Comment by addyosmani** [comment]
Confirmed this is an issue. @arthurvr I would say we should defer any Polymer 0.5.x related fixes for a few weeks and just switch to Polymer 0.8/0.9. The syntax has changed sufficiently that it's not worth us patching this up. We're working on a new TodoMVC implem and we'll PR a refresh when it's ready.

**Comment by arthurvr** [comment]
Awesome. Thanks Addy.

**Comment by samccone** [comment]
Pretty sure my pr resolved this @arthurvr 😎

**Comment by arthurvr** [comment]
@samccone's PR landed so going to close this. Thanks again for the report.
