### ISSUE TITLE
FOAM app is hosted but not listed?

### ISSUE THREAD

**Issue by shepheb** [tastejs/todomvc#1265]
The FOAM implementation of TodoMVC is [hosted](http://todomvc.com/examples/foam/) on the site and working well from my testing. It is not, however, included in any of the lists on [http://todomvc.com](http://todomvc.com). Is that the intended state, or a bug?

It would be great to be on the front list, but I suspect Labs is the right list.

See #913, #1085, and #1113 for the history of including FOAM in TodoMVC.

**Comment by arthurvr** [comment]
I guess we just forgot it. Sorry about that! Will fix it up. Thanks for letting us know.

> It would be great to be on the front list, but I suspect Labs is the right list.

yup.

**Comment by addyosmani** [comment]
Thanks @arthurvr!

**Comment by arthurvr** [comment]
PR merged.

**Comment by samccone** [comment]
:rocket:
