### ISSUE TITLE
Backbone.Marionette router history placement?

### ISSUE THREAD

**Issue by jh3y** [tastejs/todomvc#1270]
Hi there,

I've just been going through the source of the example.

However, I was wondering about `Backbone.history.start()` placement.

If a user interacts with the application and then tries to copy the url into another browser tab (bookmarking), route handlers won't be fired. It isn't too important for the example but where the `TodoList.Controller` is instantiated, if you place `Backbone.history.start()` here before the controller is started, the route handling will be respected.

I don't think binding to application start respects an order so one is getting called before the other and therefore the controllers routes aren't respected.

@jh3y

**Comment by samccone** [comment]
verified as a bug :white_check_mark:

**Comment by jh3y** [comment]
Think a possible solution would be to move `Backbone.history.start()` into `index.html` wrapped in an `on('start', func...` and change the current `on('start`, func...` to an `on('before:start', func...`.

@jh3y

**Comment by jh3y** [comment]
Submitted a PR with the proposed fix.

Happily make changes if deemed necessary.

@jh3y

**Comment by samccone** [comment]
:clap:
