### ISSUE TITLE
Better AngularJS + RequireJS app

### ISSUE THREAD

**Issue by leog** [tastejs/todomvc#1276]
Hi all.

I was wondering if you'd be interested in a better AngularJS + RequireJS app implementation. It would be more organized and probably more upgradable to adopt Angular 2 in the future.

For starters, the app module wouldn't be required everywhere which is confusing and totally unnecessary. Following AngularJS recommendations, I would be creating new AngularJS modules for each implementation and explicitly declaring their own direct dependencies in order to trace better which component is needed to make a module work helping reusability and conform with Angular 2 way to use inject some implementation into another.

Anyway, let me know if I can work on a new app example applying the described RequireJS pattern.

Regards.

**Comment by samccone** [comment]
hey @leog we are always open to improving our example apps. The best way to go about this is to open small PRs (or multiple atomic commits) that improve it in "objective ways". If you are interested in working on this it would be more than appreciated and welcome.

thanks! :sparkles:

**Comment by leog** [comment]
Got it, thanks.

**Comment by samccone** [comment]
No thank you :dancer: 
let us know if you have any questions

**Comment by leog** [comment]
BTW, is there any reason why libraries are being retrieved by NPM instead of Bower? What about the inclusion of node_modules into the repo? I was just curious :blush:

**Comment by samccone** [comment]
hey @leog since the site is hosted on gh-pages and we want to keep the deployment and dev simple for users and people who checkout the repo and run examples, we include the npm dependencies files (only the ones that are used) in the actual repo. hopefully this makes sense let me know if not . :dancers:

**Comment by leog** [comment]
Perfect sense, thanks again!
