### ISSUE TITLE
AngularJS example missing filter

### ISSUE THREAD

**Issue by blacksonic** [tastejs/todomvc#1284]
I dont find statusFilter in the example code, although it is used when listing the todos in the list.

**Comment by arthurvr** [comment]
I see it in the example code: https://github.com/tastejs/todomvc/blob/3fa235a9150f58a43474cb315adaef9196ac1b55/examples/angularjs/js/controllers/todoCtrl.js#L27 ;)

**Comment by blacksonic** [comment]
sometimes this example feels like magic

**Comment by blacksonic** [comment]
the ```resolve``` in the route section and  the ```$routeChangeSuccess``` event makes the application much harder understand, there should be a clearer way to accomplish it

**Comment by arthurvr** [comment]
> the resolve in the route section and the $routeChangeSuccess event makes the application much harder to understand, there should be a clearer way to accomplish it

I haven't worked with the example's source code a bunch but if you have any concrete suggestions or a PR that would be totally welcome ;)
