### ISSUE TITLE
Node modules and angularjs tests

### ISSUE THREAD

**Issue by blacksonic** [tastejs/todomvc#1285]
Is there a reason behind committed node_modules folder?
Why is it necessary to maintain a different ```package.json``` for AngularJS tests?

The reason behind these questions is to start increase the quality of the AngularJS example to be more sane and understandable.

**Comment by arthurvr** [comment]
> Is there a reason behind committed node_modules folder?

There is. We use npm to manage front-end dependencies so that makes sense (they should be there on the live site).

> Why is it necessary to maintain a different package.json for AngularJS tests?

I agree in there. We better add the testing dependencies as `devDependencies` in the main angular `package.json`. You in for a PR?

**Comment by blacksonic** [comment]
Im in for a PR, will check it tomorrow.
The site is on GithubPages? Because otherwise a simple ```npm install``` would solve the frontend dependencies.

**Comment by arthurvr** [comment]
> The site is on GithubPages? Because otherwise a simple npm install would solve the frontend dependencies.

A 'simple' npm install in every app folder, yes. We should look into that for the future. We first want to setup some other CI features :) 

A PR would be awesome. Don't forget to update the [`.gitignore`](https://github.com/tastejs/todomvc/blob/master/examples/angularjs/.gitignore).

**Comment by samccone** [comment]
ping @blacksonic

**Comment by arthurvr** [comment]
There we go: https://github.com/tastejs/todomvc/pull/1311 :)
