### ISSUE TITLE
FOAM example's "Clear completed" link doesn't work in Firefox 

### ISSUE THREAD

**Issue by drbraden** [tastejs/todomvc#1286]
Didn't work for me using Firefox 37.0.2 on OS X 10.10.3.  Checked using Chrome and Safari and worked fine.

http://todomvc.com/examples/foam/

**Comment by arthurvr** [comment]
Duplicate of https://github.com/tastejs/todomvc/issues/1252, FOAM [is one of the only ones](https://github.com/tastejs/todomvc/issues/1234) that still needs fixing.
