### ISSUE TITLE
Marionette displays completed tasks when "Active" tab is... uh.. active, and a task is checked

### ISSUE THREAD

**Issue by cmawhorter** [tastejs/todomvc#1290]
Viewing this: http://todomvc.com/examples/backbone_marionette/

1. Add a bunch of tasks
2. Click Active (only active tasks will be shown)
3. Check a task
4. It is still displayed

All the rest hide it in this scenario.  

Thanks for the service and a side question.  Any discussion on the same thing but on a larger scale?  Todo tells you a little about UX but not much.

**Comment by samccone** [comment]
:+1: good catch @cmawhorter
