### ISSUE TITLE
Drop angular-dart example?

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1298]
From @addyosmani in #1261:

> This example is one of those I wouldn't mind us dropping in the future if it isn't getting a lot of use.

I'm definitely :+1:.

**Comment by sindresorhus** [comment]
:+1:

**Comment by arthurvr** [comment]
cc @tastejs/todomvc more thoughts on this one?

**Comment by samccone** [comment]
Hmm so I am :-1: on this. It is pretty clear that angular2 is going to support dart as a first class language. For that reason I think this example is still valuable because down the road this will be transitioned to angular2. 

tldr;
Dart is still kicking

**Comment by passy** [comment]
Agreed with Sam. They talked about it in their keynote so I'm sure it's
gonna stick around for a while.

**Comment by urrgur** [comment]
ping? Please re-open as there was still a majority.

**Comment by samccone** [comment]
@urrgur  the team spoke out of band on this one after @passy made a very good argument. If you have an argument around why we should drop please leave it here.

**Comment by arthurvr** [comment]
I personally still believe dropping it later on would be a good choice, though, I think it's the right decision to wait. I think we will all agree that Angular 2 will change the world of angular in a significant way that we're better off revisiting this later on.
