### ISSUE TITLE
[submission] SkateJS

### ISSUE THREAD

**Issue by treshugart** [tastejs/todomvc#1306]
Hey guys, I wanted to submit a proposal for including a [SkateJS](https://github.com/skatejs/skatejs) TodoMVC app.

Skate is a web component library, based on the custom element spec. While it uses the spec as a guideline it adds several features on top of it, including some to aid in transitioning to web components from legacy style components. It's not a framework, so it doesn't offer a built-in data-binding or templating solution, but gives you the facilities to use whatever you want, if you want. In creating a TodoMVC app for Skate, we'd probably opt to use something as this layer. At this point in time, we are undecided on what we would use for it, though.

We use Skate at Atlassian for building web components and we thought it would benefit anyone using the library if there were a TodoMVC example that compares it to other libraries and frameworks on the market.

Thanks for your consideration.

**Comment by arthurvr** [comment]
:+1:. PR welcome :)

**Comment by samccone** [comment]
going to close, and we can evaluate the PR when it comes in :clap:

**Comment by treshugart** [comment]
Thanks guys! We'll start work on it soon.

**Comment by treshugart** [comment]
Hey guys, how do you prefer that we write unit tests? I know it's not required, but I think it's important for a library to include examples of how it can / should be tested. As I understand you haven't set anything in stone yet. Are you looking to automate this? The easiest thing for us would be to just set up a karma runner and expose it through `npm test`.

**Comment by alexreardon** [comment]
:+1:

**Comment by arthurvr** [comment]
> The easiest thing for us would be to just set up a karma runner and expose it through npm test.

SGTM. Also take a look at https://github.com/tastejs/todomvc/issues/254.
