### ISSUE TITLE
Meteor version, major overhaul

### ISSUE THREAD

**Issue by ffxsam** [tastejs/todomvc#1309]
Anyone have any issue with me giving the Meteor version an overhaul? Quite a bit of the code is outdated now (I'd say over 70% of it), and there are other strange things like the existence of bower files (which are not needed with Meteor). IMO todomvc is a way for people to see how the same app is built in different languages, and I think cleaning up the Meteor code would make it more appealing to newcomers.

**Comment by samccone** [comment]
👍

**Comment by ffxsam** [comment]
Cool! Will dive in when I get some spare time.
