### ISSUE TITLE
BangJS (Bacon-flavored Angular) #newapp

### ISSUE THREAD

**Issue by timmolendijk** [tastejs/todomvc#1310]
I implemented an app using [BangJS](http://bangjs.org), a framework/adapter for using Bacon.js in an AngularJS context:

* [Live app](http://bangjs.org/todomvc/)
* [Source](https://github.com/bangjs/todomvc)

The reason that I think it would be a valuable addition is that the FRP (functional reactive programming) approach is a distinct and powerful way of thinking about MVC web app development. The resulting implementation is considerably different from most others, and it has [some unique qualities](https://github.com/bangjs/todomvc#implementation).

Apart from that, it is the first implementation using Bacon.js, and also the first AngularJS implementation that uses an FRP approach.

The framework is quite early-stage and I am pretty sure that its API is not stable at this point. Therefore I am not sure that it should be included right away (hence no PR just yet), but I'd love to hear what you guys think.

**Comment by samccone** [comment]
> The framework is quite early-stage and I am pretty sure that its API is not stable at this point. Therefore I am not sure that it should be included right away (hence no PR just yet), but I'd love to hear what you guys think.

I think you nailed the reasons why for now were are going to reject this one.
The idea of combining FRP and angular is quite interesting, and worth investigating further. Feel free to open another PR when you think the lib is ready for a more serious evaluation.
