### ISSUE TITLE
Scalajs-react example

### ISSUE THREAD

**Issue by elacin** [tastejs/todomvc#1312]
Hey!

I wrote a version of todomvc using scalajs [1] and scalajs-react [2]. I know it is quite different from a lot of the other languages/frameworks you have here, but seeing as you have accepted for example a GWT version i thought i would see if you would be interested in me cleaning it up and PRing it?

[1]: http://www.scala-js.org/
[2]: https://github.com/japgolly/scalajs-react

**Comment by samccone** [comment]
:+1: to this

**Comment by arthurvr** [comment]
Though it will probably move to [TasteLang](https://github.com/tastejs/TasteLang/issues/1) at one point far in the future I'm +1 for the time being. Though I'd rather see us adopting one of those examples, not both.

**Comment by arthurvr** [comment]
The PR landed so closing this. Thanks again!
