### ISSUE TITLE
Remove sapui5

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1315]
The app is non-functional currently.  If no one wants to fix it we will remove this example in accordance with https://github.com/tastejs/todomvc/issues/1203

----------------

ping  @schubertha @passy 

any interest in fixing?

##### last (functional) change

104cfde3f5a4b08df3598f4e136a60c80549e4fd

##### Introduced in 

e7fbe334bb09689fc2d14fef348263b3c25cd7b8

**Comment by arthurvr** [comment]
:+1: If nobody comes in to fix this soon let's drop it.

**Comment by passy** [comment]
Oddly, it receives a lot of traffic, but yeah, if no one's around to fix it, let's drop it.

**Comment by akudev** [comment]
Hi,
I'll at least have a look.

**Comment by akudev** [comment]
It appears like the previous code only worked because Array.prototype.push had been overridden by someone and had been returning the resulting array instead of the array length.
Maybe in an external library, which has been removed or fixed recently...
