### ISSUE TITLE
Remove `mozart` example?

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1317]
I might be going to quick but this is one of the examples which always causes pain (for me at least).

* The app wasn't really functionally updated since it was added back in 2013.
* The framework itself isn't unique, unmaintained since October 2013 and not popular.
*  We don't have anybody to maintain the app
* Many needed updates to the app are staying open. (https://github.com/tastejs/todomvc/issues/1110, https://github.com/tastejs/todomvc/issues/1234, ...)
* The app doesn't add value anyways. The actual coffeescript source code never lived in this repo.
* Quite a bunch of failing specs.

**Comment by samccone** [comment]
👍

**Comment by sindresorhus** [comment]
:+1:

**Comment by samccone** [comment]
Implementation added in 6e00474eaef2822da4eb17d1e90a125a4b1ec4a2 in 2013

--------

**Creator:** @tomdionysus

@tomdionysus any interest in fixing this?

**Comment by arthurvr** [comment]
> @tomdionysus any interest in fixing this?

@samccone I personally still think that, even if the author is willing to fixup some stuff, we should drop it. There's really no deal with suggesting a framework which is effectively dead.

**Comment by tomdionysus** [comment]
@samccone He's right, Bigcommerce don't officially support it anymore and
I've moved on from client MVC. I just keep mozart.io up for historical
reasons. I'm good if you remove it.

**Comment by arthurvr** [comment]
Okay. That makes it quite clear. Thanks for the update @tomdionysus.
