### ISSUE TITLE
favicon not showing

### ISSUE THREAD

**Issue by Haroenv** [tastejs/todomvc#1324]
For some reason http://todomvc.com/site-assets/favicon.ico gives a 404 error, while it is visible at https://raw.githubusercontent.com/tastejs/todomvc/master/site-assets/favicon.ico 

I didn't find why, since the other images that are in the same directory do show.

**Comment by arthurvr** [comment]
The build task doesn't copy it, that's the problem. I'll fix this up.

**Comment by arthurvr** [comment]
All fixed! Again, thanks for letting us know!

**Comment by Haroenv** [comment]
No problem :smile:!
