### ISSUE TITLE
ArtJs example

### ISSUE THREAD

**Issue by arthwood** [tastejs/todomvc#1325]
Hi!

I'd like to submit an example written in my own framework [ArtJs](http://artjs.org).
Here's the link to working example: [todomvc](http://todomvc.artjs.org)

**Comment by samccone** [comment]
hi @arthwood thanks for the submission.

At this point in your frameworks life we would like to see the community and ecosystem around artjs grow  before adding it to todomvc. When you feel like it has reached this point feel free to open a PR or leave a comment in this issue thread.

Again thanks!
