### ISSUE TITLE
Ember DOM node leak

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1333]
##### Steps  to reproduce

* start timeline profiler
  * add three todos
  * delete three todos
  * (repeat above 2 more times)
* force GC
* stop timeline profiler

![screen shot 2015-06-06 at 8 44 03 pm](https://cloud.githubusercontent.com/assets/883126/8022123/cd58d0ca-0c8c-11e5-9029-9900cda24c0f.png)
![screen shot 2015-06-06 at 8 43 47 pm](https://cloud.githubusercontent.com/assets/883126/8022122/cd586aae-0c8c-11e5-9e24-2403697892ca.png)

--------

It seems like we are leaking DOM nodes :fountain:

**Comment by samccone** [comment]
ping @tomdale  @bantic

**Comment by samccone** [comment]
Just following up with some more research, ember is consistently allocating more DOM node each pass of the above steps (keep in mind I am forcing a GC between each test) 

After a bit more digging into the heap it looks like `_RenderBuffer` is doing something questionable

![screen shot 2015-06-24 at 5 34 28 pm](https://cloud.githubusercontent.com/assets/883126/8344502/64cad85a-1a97-11e5-931b-b50f4420214e.png)

Let me know if I can provide any more details.

**Comment by samccone** [comment]
cc @rwjblue @stefanpenner @wagenet

**Comment by stefanpenner** [comment]
this appears to be a duplicate of: https://github.com/emberjs/ember.js/issues/11501

**Comment by samccone** [comment]
Hey @stefanpenner thanks for getting back to me, it looks like the version of ember we are using is 
`ember#1.10.0-beta.3`

Which is an older release.
I was not sure if this leak was an error in the implementation of the todoapp or in ember core, that is why I raised the issue here.

Looking at the issue that you cross posted it seems like the two issues are not directly connected, (by the fact that a different object is retaining the nodes in this case)

At this point would you consider this an ember core bug?

**Comment by addyosmani** [comment]
@samccone Will you have time to try bumping the Ember app to latest? @paullewis ran into this leak today and was curious if we're planning to try updating to see if this has been solved upstream.

**Comment by stefanpenner** [comment]
its solved

**Comment by samccone** [comment]
@stefanpenner would it be possible to wrangle someone from the ember team/community to take a look at / help with

https://github.com/tastejs/todomvc/pull/1360 || https://github.com/tastejs/todomvc/pull/1472

I know there are a few research projects going on using TodoMVC and I would hate for ember to be poorly represented here.

**Comment by stefanpenner** [comment]
For those interested, we maintain an idiomatic version: https://github.com/ember-cli/ember-cli-todos

Although it uses build tooling/provides tests and full ci/es6 features. It should serve as a good reference for this projects variant

**Comment by samccone** [comment]
@stefanpenner Would you or someone that works on that fork be interested in PRing this back into main TodoMVC? We have full support for this kind of build process now, I think that it would be super helpful to the community at large :)

**Comment by stefanpenner** [comment]
I'm quite pressed for time.

@tchak do you have spare cycles?

**Comment by tchak** [comment]
@stefanpenner I can do that.

**Comment by samccone** [comment]
aweeeesome @tchak :hand: :bow: 

Let me know if you run into any issues or whatever, I am here to help!

**Comment by samccone** [comment]
updated to latest ember. This is no longer an issue

**Comment by addyosmani** [comment]
Thanks Sam!
