### ISSUE TITLE
Polymer 1.0

### ISSUE THREAD

**Issue by MunchyYDL** [tastejs/todomvc#1342]
Hi guys,

I was interested in converting the Polymer example to support the 1.0 release of the library.

Is there a need to keep the 0.5 version as a separate example to show the differences in syntax between the releases? Or do you only want the latest to be present? I couldn't find anything in the guidelines concerning this.

Happy to be able to contribute with this if you want it. :)

**Comment by arthurvr** [comment]
Somebody at the Polymer team is working on it so no need to duplicate work. Going to keep the ticket open till that's finished.

> Is there a need to keep the 0.5 version as a separate example to show the differences in syntax between the releases? Or do you only want the latest to be present?

Only latest :)

**Comment by arthurvr** [comment]
@addyosmani We wanted this in 1.4 so maybe you can give us a quick status update? If the team can't work on it we can still do it in-house. Thanks :wink:

**Comment by sindresorhus** [comment]
ping @addyosmani

**Comment by samccone** [comment]
I can do this @addyosmani

**Comment by arthurvr** [comment]
The PR landed so closing this now. Thanks everyone.

**Comment by samccone** [comment]
it was reverted due to deploy issues, reopening

**Comment by samccone** [comment]
whoops nm
