### ISSUE TITLE
React Example: Usage of subscribe/inform in TodoModel ?

### ISSUE THREAD

**Issue by Huxpro** [tastejs/todomvc#1346]
I wonder the usage of the `subscribe()` and `inform()` in the `TodoModel.js`

I noticed that `model.subscribe(render)` in `app.jsx`, but the `subscribe()` method push the return of `render()` (a snapshot of DOM description?) into `onChange` array? and `inform()` method traverse `onChange` and invoke the function in the array?

I am really confused here and ask a help, thank you

**Comment by samccone** [comment]
This is a react specific question not a todomvc one. Going to close as a none issue.

ping @chenglou

**Comment by chenglou** [comment]
I guess I'll write my answer here for future references.

> Why not put the model on the `state` but use a Backbone-like way to manually call the render()?

@Huxpro that was @petehunt's way of showing the "backbone way" of doing things, a long time ago. You're right, it's not really idiomatic React and now that people understand how React works, we could probably switch to keeping the model in the state and call `setState`.

**Comment by samccone** [comment]
:+1: @chenglou thanks for the info
