### ISSUE TITLE
Igaro App JS Framework Inclusion

### ISSUE THREAD

**Issue by andrewcharnley** [tastejs/todomvc#1347]
Given Igaro App is at 1.00, if it gets the go ahead I'll make a separate App submission for the todomvc module which is already done and included at;

http://app.igaro.com/showcase/

BTW, some CSS issues are noted on the page (like how do you expect touch users to click the destroy button if you use :hover?).

**Comment by samccone** [comment]
Hi @andrewcharnley thanks for bringing this to our attention. At this time it looks like the community around igaro is still quite small. We would love for you to grow this tool and community. When you feel like the library has been battle tested, please reopen this issue or open a PR with the implementation.

Thanks again.
