### ISSUE TITLE
Dojo todomvc not working in ie11

### ISSUE THREAD

**Issue by sajrashid** [tastejs/todomvc#1349]
please see post on so http://stackoverflow.com/questions/30980564/dojo-todomvc-not-working-in-ie11

No errors, Not working for me on ie11, chrome is fine

**Comment by arthurvr** [comment]
Yes, I was able to confirm this. Thanks for the report.

**Comment by arthurvr** [comment]
@asudoh may be interested in looking into this?

**Comment by asudoh** [comment]
@arthurvr Sure will take a look.

**Comment by sajrashid** [comment]
fab, thx guys
