### ISSUE TITLE
Add a README to SAPUI5

### ISSUE THREAD

**Issue by jyguyomarch** [tastejs/todomvc#1352]
Add a README file for SAPUI5 example as requested in issue #386

**Comment by arthurvr** [comment]
> as requested in issue #386

Exactly. There's already an open issue for this so I'm going to close this one.

**Comment by jyguyomarch** [comment]
Ok. Thought it was better to have one issue per application requiring a README. So I'll link a pull request to #386 once I have a README ready.

**Comment by arthurvr** [comment]
Awesome!
