### ISSUE TITLE
Running The Tests - Unable to find application root, did you start your local server?

### ISSUE THREAD

**Issue by defx** [tastejs/todomvc#1357]
Running The Tests says "You need to run a local server at the root of the TodoMVC project. Start the server using: npm run serve", however the serve script is declared inside package.json in the "tests" folder, not the root folder. If I do **npm run serve** and **npm run test** from /tests, the todomvc site is available at 127.0.0.1:8000, but I get the following;

    Error: Unable to find application root, did you start your local server?

**Comment by samccone** [comment]
go up a directory and run `python -m SimpleHTTPServer` then go into tests and run the suite.

if you find the docs unclear would you mind opening a PR to make this clearer thanks!

**Comment by defx** [comment]
@samccone Thanks for the reply, although this yields the same result.

The server is running fine whether i use `npm run serve` from /tests or `python -m SimpleHTTPServer` from root. The problem appears to be that the test browser isn't opening as expected. I've tried running with firefox and phantom, but neither of those open either, so it would appear that this isn't particular to chrome. I'm able to run other tests with selenium-webdriver without any issues.

**Comment by defx** [comment]
@arthurvr I'm bringing discussion back to the original issue as requested, so if you have any suggestions then I would be happy to hear them.

**Comment by arthurvr** [comment]
@defx Thanks!

> The problem appears to be that the test browser isn't opening as expected.

This sounds like an actual issue with your local setup, not really with ours. What version of chrome/node/selenium-webdriver are you on?

**Comment by defx** [comment]
@arthurvr 

Chrome: 43.0.2357.130 (64-bit)
Node: 0.10.33
Selenium-webdriver: ^2.45.1 

tests/package.json is the same as todomvc master.

**Comment by arthurvr** [comment]
> ^2.45.1

This doesn't help. I could have read that in `package.json` as well. What version are you actually on?

**Comment by defx** [comment]
2.46.1

**Comment by arthurvr** [comment]
I can't reproduce on exactly those same versions. We'll be happy to look into it when you can show concrete issues with our setup, for now I just assume this is an issue with your local setup.
