### ISSUE TITLE
D3.js

### ISSUE THREAD

**Issue by andrejlamov** [tastejs/todomvc#1359]
Hi!

Me and a friend have developed a version of the todomvc with D3.js, using its data binding mechanism.

Although not designed to be a pure MVC framework we still choose it to implement web applications since it provides very direct level of control, powerful data-binding and very concise code. 

[Our repo](https://github.com/andrejlamov/todomvc-app-template)

**Comment by andrelaszlo** [comment]
:+1:

**Comment by arthurvr** [comment]
Hey there! We chatted about this and agreed not to include a new example for this. Sorry!

It's really interesting, but for the time being more of an experiment, not something we'd suggest folks to build real-world apps with. When it matures a little, feel free to ask us to reopen.

Thanks for reaching out! :cake:

**Comment by ColinEberhardt** [comment]
@arthurvr personally I think a D3 implementation makes some sense. When creating visualisations I've often used D3 to render UI controls and perform MVC functionality rather than add another framework.

**Comment by ColinEberhardt** [comment]
Having said that, this implementation needs a bit of work!

**Comment by andrejlamov** [comment]
@ColinEberhardt could you please elaborate on what parts you think needs improvement? I would appreciate any comments or advice you have.
