### ISSUE TITLE
Event Sourced vanillajs version

### ISSUE THREAD

**Issue by CrowdHailer** [tastejs/todomvc#1364]
I have been working on a demo todo project that uses event sourcing with each version getting a unique url.

Added features ontop of the basic todoMVC are the ability to undo any change, visit any historic version by visiting the appropriate url.
It is written without a framework. and also not using the todoMVC templates.

I am thinking about converting to a proper todoMVC project but was wondering if the extra features and also complexity are a good thing or a bad thing with regards this project. 

These questions might be a bit vague without an example right now, but any opinions on a more complex project are appreciated.

**Comment by passy** [comment]
Hey @CrowdHailer, that sounds interesting! Our main focus here is to have a resource that makes it easy to compare different implementations of the same thing. That requires us to be really strict about the feature set an example must have - and what it must not have. So I'm afraid your implementation wouldn't be eligible for inclusion, but please feel free to add your demo to the example. It's still super interesting to see what you can build on top of the basic app.
