### ISSUE TITLE
Team diversity

### ISSUE THREAD

**Issue by qqbbgm** [tastejs/todomvc#1374]
The whole team exists of white, straight, plus-minus same age, male, western people. Not the way to go.

**Comment by passy** [comment]
I totally agree. The core team is simply a representation of the people we get the most contributions from. The problem here is not how we choose our team members, but that we don't attract a diverse enough set of people to contribute to the project. If anyone has ideas how we can improve this or hints on what we've been doing wrong so far, I'd much appreciate that.

**Comment by addyosmani** [comment]
I genuinely want to see more women and folks from diverse backgrounds contributing to the project. We need more of them in the industry as a whole and I've seen nothing but positive input and innovation from these groups in other projects. They are part of the heart and soul that is OSS and are always, always welcome to TodoMVC and any of the projects this group of folks are involved in.

That said: I created TodoMVC and was one of the creators of Yeoman. I'm not white :(. I come from a background of parents from Lebanon and Pakistan and am very much brown. It's unfortunate that when deciding to call out the project you failed to do background research here :/. You assumed everyone of us was straight, assumed we're all the same age (definitely not true) and assumed we are all western. At best, your sentiment is very much something we agree with but the note in your description is a little disheartening. 

We're going to continue to support the sentiment echoed by your issue in seeking to get more diverse members of the open-source community involved here, but I'm going to close this issue citing that this is an on-going area we're going to work on. We continue to be interested in feedback and ideas for how improving diversity can be applied to TodoMVC and will monitor the comments here.
