### ISSUE TITLE
Unclear specification has caused (potentially unfair) implementation differences.

### ISSUE THREAD

**Issue by samdoiron** [tastejs/todomvc#1376]
The specification does not say if a TODO should be added to the list on key UP or key DOWN.

While this might seem minor, those implementations which respond on keydown _seem_ much faster during typical usage.

Examples:
Keydown: Angular 1, Polymer, React
Keyup: Mithril, Angular 2, Ember

**Comment by samccone** [comment]
You are correct, we assume on keypress, however the implementation details thus far have been left up to the implementer.

We currently test this spec via:

https://github.com/tastejs/todomvc/blob/master/tests/page.js#L235-L239
<img width="456" alt="screen shot 2015-07-13 at 1 34 46 pm" src="https://cloud.githubusercontent.com/assets/883126/8656165/f693cc1c-2963-11e5-92e5-c74b0706dd5f.png">

Which is invoked by webdriver via
http://selenium.googlecode.com/git/docs/api/javascript/enum_webdriver_Key.html

Which sends the custom keycode via the driver to the browser which simulates a user typing. For now I personally think this "lax" bit of the spec if ok.. what do others thingk?

**Comment by arthurvr** [comment]
> Which sends the custom keycode via the driver to the browser which simulates a user typing. For now I personally think this "lax" bit of the spec if ok.. what do others think?

:+1:

**Comment by samccone** [comment]
going to close, @samdoiron let us know if you have any further thoughts :cloud: , thanks for opening the issue
