### ISSUE TITLE
clear completed button test has flake

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1378]
https://github.com/tastejs/todomvc/blob/a034b0d7aff2119e797f738cedba765578d1beaf/tests/page.js#L228-L233
<img width="689" alt="screen shot 2015-07-14 at 9 26 18 am" src="https://cloud.githubusercontent.com/assets/883126/8675586/7305d47e-2a0a-11e5-9859-cc86f9fd109d.png">

https://travis-ci.org/tastejs/todomvc/builds/70852831

should be simple enough to fix

**Comment by FadySamirSadek** [comment]
This is obsolete as the test suite has been completely changed
