### ISSUE TITLE
Introducing Kenna-JS

### ISSUE THREAD

**Issue by ken107** [tastejs/todomvc#1379]
Hello there,

This is a framework I have been working on for some time.  It's thin, simple, low-learning curve, but very flexible and can be used to build any complex application.  It does not handle routing.  Here are some links for you to checkout:

Basic TodoList with custom directives:
http://kenna-js.com

Basic TodoList:
http://cdn.rawgit.com/ken107/kenna-js/master/examples/todolist/todo.html

TodoList with reusable components (views)
http://cdn.rawgit.com/ken107/kenna-js/master/examples/todolist2/todo.html

GitHub homepage
http://github.com/ken107/kenna-js

Kind regards

**Comment by robbbz** [comment]
:-1:

**Comment by arthurvr** [comment]
Hey @ken107. Thanks for reaching out!

We discussed this and decided that we're not going to include a new example for now. We first want to see its community grow and develop, and want to reconsider it then. When you feel like it reached that point, feel free to ask us to reopen this. :dancer:

**Comment by ken107** [comment]
OK, no problem.

Thank you, Arthur.

On Fri, Jul 24, 2015 at 2:02 AM, Arthur Verschaeve <notifications@github.com
