### ISSUE TITLE
Angular 2 example misses routing

### ISSUE THREAD

**Issue by robbbz** [tastejs/todomvc#1391]
Which is in the app spec as a requirement.

**Comment by samccone** [comment]
Yep, when we implemented it initially angular2 did not expose routing in the dist version, they now do which means this just needs to be implemented.

**Comment by robbbz** [comment]
Okay, thanks for the answer. I think it makes sense to implement routing now or do you want to wait till the angular1 example gets replaced by the angular 2 one? And how quick do you see that happening or do you want the angular 1 example to stick around for a while?

**Comment by sindresorhus** [comment]
Angular 1 is going to stick around for a long time, so we'll have them both in the forseeable future.

**Comment by arthurvr** [comment]
> Angular 1 is going to stick around for a long time, so we'll have them both in the forseeable future.

SGTM.

**Comment by kasperpeulen** [comment]
I created a angular 2 dart version with routing here:
https://github.com/ng2-dart-samples/todomvc

**Comment by robbbz** [comment]
Maybe open a different issue, this is about the main angular example.
