### ISSUE TITLE
Update elm example to latest elm

### ISSUE THREAD

**Issue by robbbz** [tastejs/todomvc#1394]
It's at 0.14, but 0.15 is already in stable.

**Comment by samccone** [comment]
@robbbz any interest in fixing :)

**Comment by robbbz** [comment]
No, not really. Sorry. Just digging into the elm thing.

**Comment by arthurvr** [comment]
Maybe @passy is interested?

**Comment by passy** [comment]
I am indeed! We can assign this to me but I won't be able to jump right onto it.

**Comment by arthurvr** [comment]
There's no hurry! Thanks passy.

**Comment by arthurvr** [comment]
@passy Hey, there's totally no hurry, but mind giving us a status update? It looks like you've done some cool work in a branch, what should happen more?

**Comment by passy** [comment]
@arthurvr So there is a branch here on the repo, but I'm tracking the changes at [this repo](https://github.com/evancz/elm-todomvc) which will soon be upgraded to 0.16. There are a bunch of open PRs which get it closer to spec compliance, but Evan is busy sorting the Elm release out. It's probably going to take a bit longer, but I haven't forgotten about it. :)

**Comment by arthurvr** [comment]
Thanks @passy :)

**Comment by absynce** [comment]
It has been updated to 0.17, but would be cool to see it at 0.18.
