### ISSUE TITLE
Poochie

### ISSUE THREAD

**Issue by garious** [tastejs/todomvc#1395]
Request for comments: https://github.com/garious/poochie-todomvc

Anything interesting to anyone here? The goal of the microframework is to allow for 100% line and branch coverage as the app is incrementally developed. It's also quite lightweight. Browserfied gzipped version is under 5k - includes both the library [poochie](https://github.com/garious/poochie) and the TodoMVC implementation.

My favorite piece is how the top-level file is nearly a single expression and written in plain old JavaScript:
https://github.com/garious/poochie-todomvc/blob/0.1.0/index.js

**Comment by garious** [comment]
First impressions?

**Comment by garious** [comment]
Ping

**Comment by samccone** [comment]
hey @garious this framework does seem quite interesting, especially given the declarative nature of the kickoff script, thanks for opening this issue!

One of the goals of todomvc is to provide people with a site to explore different frameworks that they could use to build an application. We typically like to limit the frameworks that we add to those that have been "battle tested" or have been used by a fair amount of people.

It currently seems like your framework is still quite new (which is not a bad thing), and we (todomvc org) would love it mature and be used some more before adding this new framework.

Feel free to ping us on this issue when you feel like the framework has reached this point. Thanks again!

**Comment by garious** [comment]
Hi @samccone, thanks for the feedback. If you or anyone feels that this framework is very similar to some existing framework, please let me know. I'm wondering if [poochie](https://github.com/garious/poochie) contains an innovative design decision. The framework encourages declaring *static* elements with dynamic attributes *and dynamic contents*. I believe this decision alleviates the need for DOM-diffing, which I see is popular in reactive JS frameworks, but something I haven't seen in reactive frameworks in other languages. I'm concerned the JS community is building infrastructure around a problem that wasn't intended to exist in the reactive programming paradigm. If anyone would like to talk more about it, let's chat at https://gitter.im/garious/poochie.
