### ISSUE TITLE
Problem with cancel

### ISSUE THREAD

**Issue by rulotr** [tastejs/todomvc#1405]
In todomvc with react, when i edit, and after pressing esc to cancel, and click in a row  the new value returns.

It can solved it

	handleChange: function (event) {
			 	if(this.props.editing){
					this.setState({editText: event.target.value});			
			 	}			 	
		}

**Comment by samccone** [comment]
not sure I follow, or can reproduce, @rulotr can you post a gif or screenshots?

**Comment by rulotr** [comment]
![todomvc](https://cloud.githubusercontent.com/assets/13245511/9211189/134b17b8-4046-11e5-8af2-b852c359e8ea.gif)

**Comment by samccone** [comment]
wow, totally not able to reproduce in chrome on osx...

**Comment by rulotr** [comment]
in chrome its ok, it´s only in firefox.

**Comment by samccone** [comment]
great catch @rulotr ... so that brings up the question of why only in firefox?

**Comment by rulotr** [comment]
when i cancel: in firefox call handleKeyDown -> handleChange -> handleSubmit
and firefox call  handleKeyDown -> handleSubmit

**Comment by rulotr** [comment]
sorry and chrome call handleKeyDown -> handleSubmit

**Comment by arthurvr** [comment]
Hm, this is a strange one. I'm able to reproduce this in Firefox 40 and 39, but not in 38, which makes me think it's a Firefox bug.

**Comment by jonnykry** [comment]
It seems like @rulotr's suggestion fixes this bug.  I built it locally with the changes and couldn't reproduce the bug.  Is there a PR for this?  I can make one (and add unit tests too) if not.

The bug is still happening on Firefox with the production code.

**Comment by samccone** [comment]
PR away @jonnykry :)

**Comment by jonnykry** [comment]
Cool!  Can't get around to it tonight, but I can get it done tomorrow np.
:hammer: :bug:

**Comment by samccone** [comment]
617079e
