### ISSUE TITLE
✅ Change checkbox approach on todos

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1408]
Currently we are using a pseudo element on the checkbox elements however, Firefox, and IE edge both have some serious trouble rendering this. :crying_cat_face: 

![](https://cloud.githubusercontent.com/assets/9906/9224879/a726905e-40fd-11e5-99f6-2364d7905358.png)

<img width="742" alt="screen shot 2015-08-12 at 9 34 05 am" src="https://cloud.githubusercontent.com/assets/883126/9225107/4d573a42-40d5-11e5-9769-c4321257a788.png">

I thinkkkkkk maybe we should consider updating the approach

xref #1259

**Comment by patrickkettner** [comment]
PRd a fix upstream - not sure how it would work getting it here since upstream has converted ids to classes. Happy to help get it landed, if desired, though

**Comment by arthurvr** [comment]
Happy to change it, but I think it's better if we wait to do it though. There are some other big updates (new UI, npm, classes, clear completed button) and I'm worried that it will get messy and difficult (both for us but also for contributors)

**Comment by patrickkettner** [comment]
I'm fine with whatever, but I am not clear how meeting this makes anything
messy

**Comment by arthurvr** [comment]
> but I am not clear how meeting this makes anything
> messy

Basically it might become difficult to keep track of what examples still need the update and what versions different examples should use. Getting people to update their apps always takes quite a while. Some aren't even on the new UI yet.

**Comment by patrickkettner** [comment]
> it might become difficult to keep track of what examples still need the
update

>Some aren't even on the new UI yet.

So par for the course?

Isn't the point of it being a module to allow for people to update to it
when they would like to without having to block on updates to the module
itself?

Or is it that its likely that the apps will be forking the CSS file or
something?

**Comment by arthurvr** [comment]
> Isn't the point of it being a module to allow for people to update to it
> when they would like to without having to block on updates to the module
> itself?

Yes, and we should totally update the module. Just saying that I think it will be quite a long time till we get all examples to actually upgrade.

**Comment by patrickkettner** [comment]
Totally understand and empathise that. What I am having a disconnect with
is why that is a reason to not include a big fix that doesn't require them
to change anything that wouldn't already be required with the modules
current state. There are no markup changes required to support it.

**Comment by arthurvr** [comment]
> There are no markup changes required to support it.

Ah, whoops, sorry. I thought the `toggle-all` class was new, sorry. Then totally :+1: :) Sorry for the noise. Thanks for the fix, @patrickkettner!

**Comment by patrickkettner** [comment]
![image](https://cloud.githubusercontent.com/assets/465414/9426878/c1fd1382-492a-11e5-923e-878efb296144.png)

**Comment by samccone** [comment]
:taco: :tada:  nice work
