### ISSUE TITLE
Ember example uses a deprecated context-switching

### ISSUE THREAD

**Issue by jspdown** [tastejs/todomvc#1411]
Hi, 

I noticed that `index.html` file in the Ember example use a deprecated `{#each}`( [#L17-L27](https://github.com/tastejs/todomvc/blob/de6a0729d8c6f953e2a52d7c7669b87082f0b787/examples/emberjs/index.html#L17-L27)).

As mentioned in [the deprecations section of the documentation](http://emberjs.com/deprecations/v1.x/#toc_transition-plan), it should be replaced by something like that:

```
{#each todos}
...
{/each}
```

**Comment by samccone** [comment]
We have a pending new version of the ember app here
https://github.com/tastejs/todomvc/pull/1360

:)
