### ISSUE TITLE
Bootstrap?

### ISSUE THREAD

**Issue by timoc** [tastejs/todomvc#1415]
What about adding Bootstrap?
http://getbootstrap.com/

**Comment by passy** [comment]
How do you mean?

**Comment by addyosmani** [comment]
Bootstrap is a UI library rather than a framework or library for application architecture. As such adding a Todo app using it would offer minimal value to our end users.

**Comment by samccone** [comment]
:+1: 

> Bootstrap is a UI library rather than a framework or library for application architect

Going to close for now but we can continue the discussion if you have thoughts otherwise.
Thanks @timoc for raising this :sparkles: !

**Comment by timoc** [comment]
Hi,

Maybe i'm missing something, because I've seen alot of application templates using HTML5 and Bootstrap, and presumed bootstrap was an MVC based toolkit. Would this mean that all of these templates have written their own framework on top of bootstrap?

**Comment by passy** [comment]
@timoc Either that or they've used an MVC framework in combination with Bootstrap.
