### ISSUE TITLE
Is cloud9 down or todomvc workspace is not available anymore?

### ISSUE THREAD

**Issue by pbassut** [tastejs/todomvc#1428]
I'm getting a 404 error when trying to edit the code using cloud9. 
Is it down or the workspace is not available anymore?

**Comment by samccone** [comment]
+1 to reconsider the value of these

**Comment by addyosmani** [comment]
:+1: Let's reconsider. I'm not particularly tied to them being in there. The idea was to originally let people view/edit sources quickly if they wanted to tinker around with our implementations. TBH I don't think that many do. Perhaps PR the removal and if no one says anything after a week we nix them?

**Comment by arthurvr** [comment]
> Perhaps PR the removal and if no one says anything after a week we nix them?

Yep, sgtm. Doing now.

**Comment by pbassut** [comment]
I was just going to quickly view the code in a more ide-like environment to download right after. But I prefer to have to code on my computer. So I think it does add much.

**Comment by pbassut** [comment]
Not ready to close yet? It has been discussed, right?

**Comment by arthurvr** [comment]
@pbassut Discussed, but it isn't fixed yet ;)
