### ISSUE TITLE
Split todomvc up in different repos?

### ISSUE THREAD

**Issue by robbbz** [tastejs/todomvc#1432]
Just a suggestion, some advantages:

* Easier to maintain
* Easier to use a `master` branch for source and `gh-pages` for live version (for apps that need compilation steps)
* Easier for people to clone and experience with one app
* Easier for people to explore apps
* Easier issue tracking
* ...

**Comment by arthurvr** [comment]
Thanks for your suggestion, we discussed with the team. Although there are some advantages indeed, it would make our CI, deployment, hosting and release process way more complicated. Also, there wouldn't be a place where we can easily review new apps. I'm going to close this for now.
