### ISSUE TITLE
New application property: Show TODO properties

### ISSUE THREAD

**Issue by koppor** [tastejs/todomvc#1433]
The todomvc app shows important aspects of frameworks. I miss, however, an important property: The property window. If I click on a TODO, I'd like to see it in a properties view (possibly a column on the right side). At this properties view, I can edit the TODO's text. Such an additional functionality would show how two-way databinding works in the different frameworks.

**Comment by arthurvr** [comment]
We know the TodoMVC example doesn't cover every aspect of modern webapps, but the goal is to give people a quick glance and *help* them choose. That said, frameworks that heavily use two-way databinding generally already show that on that simple of an app. I personally don't think we need to add any more features to the examples and adding more would also mean a maintainability risk.

I'm going to close this for now but feel free to reopen if anyone disagrees. Thanks for the suggestion!
