### ISSUE TITLE
Haxe implementation

### ISSUE THREAD

**Issue by mtkocak** [tastejs/todomvc#1440]
Source: https://github.com/mtkocak/haxe-todomvc
Demo: http://mtkocak.github.io/haxe-todomvc/

**Comment by samccone** [comment]
Hey @mtkocak would you mind opening up a PR with the implementation. I think it will ease the review process quite a bit. Thanks!

**Comment by arthurvr** [comment]
We never actually received a PR so I'm going to close this for now. If someone shows interest to open up that PR we can reopen this ;)
