### ISSUE TITLE
angular2 dart example

### ISSUE THREAD

**Issue by kasperpeulen** [tastejs/todomvc#1446]
Would you  guys appreciate an Angular2 Dart example ?

If so, I could make a PR from this one: 
https://github.com/ng2-dart-samples/todomvc

**Comment by arthurvr** [comment]
Would you like to add a new example for this or would you like to update our current `angular-dart` example?

**Comment by arthurvr** [comment]
I'm going to close this for now. We're not really interested in having two Angular+Dart examples and will reconsider how we're going to handle the Angular examples once Angular 2.0 actually releases. Thanks for the suggestion though.

**Comment by kasperpeulen** [comment]
Okay, np :) @arthurvr 

I think angular1 dart is not longer maintained, so maybe it would be good to replace that one, once angular2 is released. But for now, I guess the angular1 dart example is more relevant.

**Comment by samccone** [comment]
@kasperpeulen any interest in helping out with our angular 1 example :)
