### ISSUE TITLE
Basic instructions?

### ISSUE THREAD

**Issue by ChuckIrvine** [tastejs/todomvc#1447]
I am very new to Ember and would like to use your Ember todo example. Are there some basic instructions somewhere on how to start using your examples to learn the various frameworks - Ember in my case? Thanks

**Comment by samccone** [comment]
Hi @ChuckIrvine please refer to the ember readme file here :)

https://github.com/tastejs/todomvc/tree/master/examples/emberjs

Best of luck learning!
