### ISSUE TITLE
New app with redux

### ISSUE THREAD

**Issue by sotayamashita** [tastejs/todomvc#1460]
http://rackt.github.io/redux/index.html

**Comment by canvaskisa** [comment]
@sotayamashita i have made a little [TodoMVC example](https://github.com/canvaskisa/redux-css-modules-todomvc), using redux, so i can update it for todomvc repository style, if you're interested in it

**Comment by sotayamashita** [comment]
@canvaskisa sound good to me !

**Comment by FadySamirSadek** [comment]
Closed as per #1674
