### ISSUE TITLE
Lack of favicon.ico in root directory raises 404 error, cluttering test output

### ISSUE THREAD

**Issue by davidrunger** [tastejs/todomvc#1465]
When I run the tests per the instructions in `tests/README.md`, I get a 404 error for favicon.ico in many/most/all(?) of the tests.

Example:

```
  TodoMVC - backbone
    When page is initially opened
      ✓ should focus on the todo input field
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444529718462,
    type: '',
    closure_uid_682459046: undefined } ]
    No Todos
      ✓ should hide #main and #footer (131ms)
[ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8000/favicon.ico 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444529720273,
    type: '',
    closure_uid_682459046: undefined } ]
...
```

The tests pass, but these error messages terribly clutter up the test output.

I imagine that there is some setting to suppress the printing of the errors, but that is probably not ideal because it would be nice to see other, legitimate errors in the test output.

The problem can be fixed by simply creating in the root directory a symlink to the favicon.ico that is in the `site-assets` directory:

```sh
~/Downloads/todomvc $ ln -s site-assets/favicon.ico favicon.ico
```

Now we get a much neater test output:

```
  TodoMVC - backbone
    When page is initially opened
      ✓ should focus on the todo input field
    No Todos
      ✓ should hide #main and #footer (98ms)
...
```

I'd make a pull request adding the symlink, but I feel like I am probably missing something? Otherwise I imagine that someone else would have raised this issue by now. Apologies if that is the case. Additionally, I'm not sure if y'all want that symlink cluttering up the root directory.

**Comment by samccone** [comment]
Here is so more context https://github.com/tastejs/todomvc/commit/6b12eb31a81f8ec8271cb25d564ea31439620b3

I'm totally up for a more elegant solution if you can think of one

**Comment by davidrunger** [comment]
One option is to use an express.js server instead of the simpler http-server for serving the todo apps for the tests. Express has a middleware that allows specifying the location of the favicon.

Here's a pull request for that: https://github.com/tastejs/todomvc/pull/1467

Or the simpler option of just putting that symlink in the root directory doesn't seem all too terrible to me. Probably something needs to be done, though; those error messages are really intrusive. These are the two solutions that I can think of for now.
