### ISSUE TITLE
Add routing to typescript / backbone example

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1487]
cc @DanielRosenwasser @dprotti  @addyosmani 

Anyone have any interest here, or know anyone that might?

Thanks! :sparkles:

**Comment by DanielRosenwasser** [comment]
:tada:

**Comment by samccone** [comment]
@dmethvin coming in strong on this one!

**Comment by samccone** [comment]
(typescript should send him some sweet stickers :package: :wink: )
