### ISSUE TITLE
New App: NodeListJS

### ISSUE THREAD

**Issue by eorroe** [tastejs/todomvc#1489]
Hey I'm the creator of [NodeListJS](https://github.com/eorroe/NodeList.js). I was wondering if I could do a todoMVC non-framework implementation with my library.

You can check out the repo to learn about it, or here's a [SitePoint article](www.sitepoint.com/dom-manipulation-with-nodelist-js/) I wrote about on it.

Would this be a good candidate that you guys would be interested in?

**Comment by arthurvr** [comment]
Mind elaborating a bit? NodeListJS is a DOM manipulation library, not an MVC solution, isn't it?

**Comment by eorroe** [comment]
@arthurvr Yea, but so is jQuery sort of, it just has ajax etc, which don't need for the todoMVC

**Comment by arthurvr** [comment]
The reason jQuery is there is that everybody knows it and people have a familiar thing to compare actual MVC solutions to. This isn't really the same situation. It's not an MVC solution so I'd prefer to close this. Thoughts?

**Comment by eorroe** [comment]
Well that's true, but I thought you guys were doing non-mvc solutions as well?

**Comment by arthurvr** [comment]
Going to close this because this is a DOM manipulation library. 

> Helping you select an MV* framework
