### ISSUE TITLE
Incorrect path in Aurelia demo

### ISSUE THREAD

**Issue by bondden** [tastejs/todomvc#1492]
![todomvc-2015-10-26_22-53-33](https://cloud.githubusercontent.com/assets/5232392/10735978/d5c9f3fc-7c34-11e5-8bc6-feedd9d3ee78.png)

**Comment by samccone** [comment]
@bondden thanks for the report! are you interested in opening a PR to resolve?

**Comment by arthurvr** [comment]
@mhoyer Can you look into this? Thanks.

**Comment by mhoyer** [comment]
@arthurvr sure I can have a look. Hopefully tomorrow. I was already preparing a new PR for Aurelia example including the fix for https://github.com/mhoyer/todomvc-aurelia/issues/10. 
@bondden in the meantime you may have a look into current master of my original sources.

**Comment by samccone** [comment]
Resolved!
