### ISSUE TITLE
angular-dart complains about audio context...

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1501]
'http://localhost:8000/examples/angular-dart/web/main.dart.js 66335:22 \'webkitAudioContext\' is deprecated. Please use \'AudioContext\' instead.',

wat :)

**Comment by arthurvr** [comment]
Not a bug, just a stupid warning. :cry: https://github.com/dart-lang/sdk/issues/23259. 

Honestly, I don't think we should care. Definitly as (I guess?) this example will be replaced/dumped after ng2. Angular.dart itself is currently [dying](https://github.com/angular/angular.dart/graphs/contributors) anyways.

**Comment by samccone** [comment]
alright :(
