### ISSUE TITLE
To-Do text overflow

### ISSUE THREAD

**Issue by anubhav7495** [tastejs/todomvc#1506]
Steps to reproduce:

1. Open any todomvc app.
2. Write a very long To-Do in the input area.
3. The text flows out of the text container when todo is submitted.

Expected Behaviour:
The long text show always stay in the container and not overflow out of it.

**Comment by passy** [comment]
Which one? Seems to be alright for Backbone at least.

<img width="1552" alt="screenshot 2015-11-08 09 42 49" src="https://cloud.githubusercontent.com/assets/9906/11019710/220a4b0a-85fd-11e5-81ce-5edf140918d1.png">

**Comment by anubhav7495** [comment]
Angular, angular+firebase.

**Comment by anubhav7495** [comment]
/home/anubhav/Pictures/Screenshot from 2015-11-08 15:29:16.png

**Comment by anubhav7495** [comment]
![screenshot from 2015-11-08 15 29 16](https://cloud.githubusercontent.com/assets/10097603/11019756/9d7997ac-862d-11e5-88eb-8581b1b2cb83.png)

**Comment by anubhav7495** [comment]
even the backbone one doesnt work

**Comment by anubhav7495** [comment]
Update: This issue is Firefox Specific, i tried with chrome and it works fine.

**Comment by samccone** [comment]
@anubhav7495 this seems like something that we can resolve in the todo-app-css repo https://github.com/tastejs/todomvc-app-css

cc @sindresorhus

**Comment by anubhav7495** [comment]
created a pull request on todomvc-app-css: https://github.com/tastejs/todomvc-app-css/pull/12
Fixes the issue on firefox.

**Comment by samccone** [comment]
boom thanks for the PR @anubhav7495
