### ISSUE TITLE
go example allows you to enter empty todos

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1516]
![screen shot 2015-11-10 at 9 34 35 am](https://cloud.githubusercontent.com/assets/883126/11070049/5043b47e-878e-11e5-8896-b647de5a13a6.png)

just by hitting enter 

cc @albrow @shurcooL

**Comment by albrow** [comment]
Sorry about that. Should be an easy fix. I'll do it soon.

**Comment by samccone** [comment]
nah I should have caught it, the blame is on me

**Comment by shurcooL** [comment]
Question, what exactly does the test suite cover and is easy to change it so it catches these kind of behavior issues?

**Comment by samccone** [comment]
the tests cover most of the "spec", but there are gaps still

the tests are here:
https://github.com/tastejs/todomvc/blob/master/tests/test.js

and it is fairly simple to add new tests :)
