### ISSUE TITLE
Update Ember.js example to latest version (and Ember-CLI?)

### ISSUE THREAD

**Issue by iheanyi** [tastejs/todomvc#1520]
Currently the Ember.js example is using version 1.10, whereas the latest official version of Ember is 2.1.0. Additionally, the example given is written without the use of Ember-CLI, but Ember-CLI is the official way of starting on new Ember projects. So the Ember.js example should be updated to reflect this.

**Comment by samccone** [comment]
we agree!

going to xlink here and close this issue for now
https://github.com/tastejs/todomvc/issues/1069


thanks for the interest @iheanyi !!!
