### ISSUE TITLE
Error in IE11.0.25, file missing: HTMLImports.min

### ISSUE THREAD

**Issue by RedFeet** [tastejs/todomvc#1543]
The Aurelia implementation of the todomvc doesn't start running...
It reports that the HTMLImports polyfill file is missing:
github:webcomponents/webcomponentsjs@0.5.4/HTMLImports.min

But since I can see that the file exists in the directory /bower_components/
maybe the path is just incorrect or the Bower install wasn't complete.

Background: capture from the IE11.0.25 console log:
DEBUG [bootstrapper] loading core-js
DEBUG [bootstrapper] loading the HTMLImports polyfill
DEBUG [bootstrapper] loading the HTMLTemplateElement polyfill
Potentially unhandled rejection [4] Error loading "github:webcomponents/webcomponentsjs@0.5.4/HTMLImports.min" at http://todomvc.com/examples/aurelia/jspm_packages/github/webcomponents/webcomponentsjs@0.5.4/HTMLImports.min.js
Not Found: http://todomvc.com/examples/aurelia/jspm_packages/github/webcomponents/webcomponentsjs@0.5.4/HTMLImports.min.js (WARNING: non-Error used)

**Comment by arthurvr** [comment]
This was fixed in #1545. Thanks for the report!
