### ISSUE TITLE
Were there breaking CSS changes in last 8 months?

### ISSUE THREAD

**Issue by gadfly361** [tastejs/todomvc#1546]
Hey team,

There is something funky going on with the CSS in the reagent example. I am curious if there has been some kind of change to the demo's css? I authored it 8 months ago, and I recall it looking fine, it passed all the tests, and there is no way it would have passed your review process in its current state because the css problems are _egregious_.

Steps to reproduce:
1. Type foo, hit enter
2. Type bar, hit enter
3. Type baz, hit enter
4. Mark bar as complete
5. Click 'Completed' (_this will show checkbox in a weird place_)
6. Click 'Active'
7. Click 'All' (_the circle next to baz disappears_)

**Comment by samccone** [comment]
verified :white_check_mark: 

![screen shot 2015-12-05 at 4 34 34 pm](https://cloud.githubusercontent.com/assets/883126/11611051/35a9547c-9b6e-11e5-9f2c-23032679c620.png)


Hi @gadfly361 thanks for finding this, as you can see no one has touched your example in the last 8 months

https://github.com/tastejs/todomvc/tree/master/examples/reagent

It seems like there may a potential rendering bug in chrome with :after tags... SVG and content

![screen shot 2015-12-05 at 4 38 49 pm](https://cloud.githubusercontent.com/assets/883126/11611061/cd636bae-9b6e-11e5-8ec7-90f7b6968899.png)

**Comment by samccone** [comment]
I have filed this upstream https://code.google.com/p/chromium/issues/detail?id=566561&thanks=566561&ts=1449362663

**Comment by gadfly361** [comment]
Sweet, thanks!  Does that mean this issue should be closed? Not really sure, what the protocol is if the problem is indeed upstream.

**Comment by gadfly361** [comment]
Also, just so there is an example, after step 5 in my steps to reproduce, it looks like this (note checkmark):

![image](https://cloud.githubusercontent.com/assets/8610039/11611091/b9b12cac-9b70-11e5-86eb-c713269fbf4d.png)

**Comment by samccone** [comment]
I will leave it open until we get a response :)

**Comment by lewislong** [comment]
CSS now uses classes exclusively where the js and html use id's. Following the backbone js TodoMVC tutorial I had to fix the html/css to use a mixture of classes and id's.

https://addyosmani.com/backbone-fundamentals/#exercise-1-todos---your-first-backbone.js-app

**Comment by gadfly361** [comment]
Just checked and it looks like this issue is no longer present - going to close. 🤷‍♂
