### ISSUE TITLE
Tutorial for jQuery ToDoMVC

### ISSUE THREAD

**Issue by xmatic** [tastejs/todomvc#1548]
Firstly, thank you to the creator/s for creating the jQuery ToDoMVC. 

A large number of JavaScript programmers know and use jQuery.

A large number of us find it hard to wrap our heads around the new MVC frameworks (Angular, React etc.). I'm one of them.

So... the jQuery ToDoMVC build is a great "bridge" for those of us who know jQuery and want to understand what MVC is all about.

I'm humbly requesting someone to please create a tutorial that explains the jQuery ToDoMVC. It would be a huge help.

**Comment by dmitriz** [comment]
Would more in-code comments be of use?
What about Angular examples?

**Comment by samccone** [comment]
Hey @xmatic  I agree this sounds like an awesome idea, anyone is more than welcome to write this up, and we can link to it from the wiki pages and one of the example pages!

(closing as this is not a direct issue in todomvc)
