### ISSUE TITLE
Would a non-CSS solution be compatible with the website?

### ISSUE THREAD

**Issue by relfor** [tastejs/todomvc#1553]
Hey,

So I just launched this constraint-based rendering engine, which forgoes CSS positioning (for all block elements), and instead uses HW acceleration. It also has MVC baked into it.

The repository is here: [https://github.com/TheRelforFoundation/LAY.js](https://github.com/TheRelforFoundation/LAY.js)

And here is TodoMVC implemented using it:
(http://codepen.io/relfor/full/VeaVNe/)[http://codepen.io/relfor/full/VeaVNe/]

The entire app consists of 1 JS file, and it doesn't use the `base.css` offered as a part of TodoMVC.
The CSS file is not required as the engine takes care of styling and positioning.
Would you ever accept this engine on your website?

**Comment by samccone** [comment]
I think we would accept it... we would just have to manually audit how things look

**Comment by arthurvr** [comment]
See https://github.com/tastejs/todomvc/pull/1614#issuecomment-247875139 :)
