### ISSUE TITLE
Tests miss the lack of focus :)

### ISSUE THREAD

**Issue by dmitriz** [tastejs/todomvc#1560]
This fork has disabled focus on double-click to demonstrate that the tests do not catch the lack of focus:

    npm run test -- --framework=angularjs-perf

https://github.com/dmitriz/todomvc/tree/tests-miss-focus-failure

**Comment by samccone** [comment]
good catch @dmitriz 

https://github.com/tastejs/todomvc/blob/master/app-spec.md#new-todo

> The input element should be focused when the page is loaded

:pencil2:

**Comment by samccone** [comment]
I would have expected this to catch it...

```js
		test.describe('When page is initially opened', function () {
			test.it('should focus on the todo input field', function () {
				testOps.assertFocussedElementId('new-todo');
			});
		});
```
https://github.com/tastejs/todomvc/blob/master/tests/test.js#L91

weird eh

**Comment by dmitriz** [comment]
Doesn't look quite that obvious tho.

https://github.com/tastejs/todomvc/blob/master/tests/test.js#L92

uses

    testOps.assertFocussedElementId('new-todo');

but we don't have the `Id` for the double-clicked element, so looks like changes are needed in several places. Or not?
