### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by mxstbr** [tastejs/todomvc#1563]
I wanted to update the React TodoMVC app to React 0.14, the newest version. I noticed that [JSX Transformer](https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html), which the example uses to avoid a build step, was officially removed with v0.14 in favor of babel-browser – which, ironically, is now [deprecated as well](https://babeljs.io/docs/usage/browser/).

Does anybody know of other tools that allow in-browser JSX transpiling? Otherwise we might have to include a build step in the React example.

**Comment by samccone** [comment]
@mxstbr we can include a build step if there is no official way to do it in browser now... also check out this issue https://github.com/tastejs/todomvc/issues/1541

If you are interested, it would be great to have a react perf example :)

**Comment by mxstbr** [comment]
@samccone will make a v0.14 perf version and look into adding the simplest build step possible so beginners won't get confused by lots of magic!

**Comment by samccone** [comment]
:+1: awesome @mxstbr Excited to see it

**Comment by acamposruiz** [comment]
Hello all! :), @samccone and @mxstbr  I am new here, i would like make a babel react with simplest build step to contribute in this project, is here where i have to write or i have to create a new issue?, thanks!

**Comment by FadySamirSadek** [comment]
@mxstbr I can not see a PR for this but there is a PR at #1767 that uses create-react-app and a more recent version of react , you can help to make it happen by addressing the feedback there.
