### ISSUE TITLE
New TodoMVC implementation in Angular 2 with ES2015

### ISSUE THREAD

**Issue by vuesomedev** [tastejs/todomvc#1565]
Based on the existing Angular 2 TodoMVC implementation with Typescript i would like to implement it in ES6 Javascript and transpile it with Babel. I would use a Gulp based workflow with Webpack. Is there a place for it next to the original?

**Comment by blacksonic** [comment]
Completed the implementation here https://github.com/blacksonic/angular2-es6-todomvc.
What should i commit from this repository besides source files? I bundle the app with webpack and place the client application into the build directory and serve the static file from there with koa.

**Comment by blacksonic** [comment]
Implemented in {tastejs}/{todomvc}#{1581}

**Comment by flashdesignory** [comment]
Closing this issue, since we added a new Angular version: https://github.com/tastejs/todomvc/pull/2212
