### ISSUE TITLE
Angular2 example doesn't run locally

### ISSUE THREAD

**Issue by simondiep** [tastejs/todomvc#1589]
When I clone todomvc and open todomvc/examples/angular2/index.html in my Chrome browser, all I get is a JavaScript error.

    XMLHttpRequest cannot load file:/todomvc/examples/angular2/app/bootstrap.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.src.js:1049

Note: This is resolved by deploying the example to an HTTP server

**Comment by samccone** [comment]
Most examples require an http server, that is a known thing.

Thanks for the issue.
