### ISSUE TITLE
Elm - Scrolling not present

### ISSUE THREAD

**Issue by LeviSchuck** [tastejs/todomvc#1608]
The Elm todomvc can go beyond the bottom of the page with multiple tasks and scrolling does not seem to work or is present on the page.

**Comment by arthurvr** [comment]
Thanks for the report. What platform are you on and what browser are you using? I can't seem to replicate this.

**Comment by LeviSchuck** [comment]
I am unable to replicate this on the latest browsers, however I believe it was Safari on OS X Yosemite.

Closing
