### ISSUE TITLE
Component based AngularJS

### ISSUE THREAD

**Issue by kaeyeh** [tastejs/todomvc#1613]
Hi,
I'd like to contribute a version of todomvc using component based AngularJS (version 1.4), the concept has been specified in the following documents:
http://busypeoples.github.io/post/thinking-in-components-angular-js/
https://leanpub.com/web-component-development-with-angularjs

I have the TypeScript version attached so you can have an idea, and JavaScript version can be easily derived. If you guys interested to accept them, I can enhance it according to your coding standard.
[typescript-angular.tar.gz](https://github.com/tastejs/todomvc/files/214293/typescript-angular.tar.gz)

Kae

**Comment by blacksonic** [comment]
Why not version 1.5? It introduces one-way binding and components which helps a lot in making component based applications.

**Comment by kaeyeh** [comment]
We have lots pre 1.5 code was implemented as such, may not able to migrate for a while. For the new application we do use 1.5 component, I can contribute 1.5 version if you think it has some value. Thanks.

**Comment by lukaszkups** [comment]
I would like to see component-based implementation of that (but yes, in Angular 1.5 likely, no typescript please)

**Comment by kaeyeh** [comment]
Sorry, just came back from vacation, I will submit it soon.

**Comment by lukaszkups** [comment]
no problem! hope You enjoyed Your vacation :) happy coding! :)

**Comment by kaeyeh** [comment]
Here is the code, running with NG 1.5 and Javascript. Can you review.
https://github.com/kaeyeh/angular-component

**Comment by flashdesignory** [comment]
Closing this, since we added a new Angular version: https://github.com/tastejs/todomvc/pull/2212
