### ISSUE TITLE
Meteor example is offline

### ISSUE THREAD

**Issue by JulianSamarjiev** [tastejs/todomvc#1617]
The correct one seems to be - https://www.meteor.com/tutorials/blaze/creating-an-app

**Comment by passy** [comment]
Hey @JulianSamarjiev, could you be a bit more specific? I checked the links we have in the sidebar and they all seem to work. Which one is broken?

**Comment by JulianSamarjiev** [comment]
Hey @passy , this one doesn't work for me - https://github.com/tastejs/todomvc/blob/master/index.html#L307

**Comment by passy** [comment]
Thanks! I've removed the listing for now. Based on your URL I thought you were referring to the tutorial material.

@tastejs/todomvc Does anyone remember the credentials situation? I'm not sure if someone has to re-upload the app or if they've changed the hosting model altogether.

**Comment by michalsnik** [comment]
Hi @JulianSamarjiev and @passy, I also noticed this but I think it shouldn't be added for now.
Meteor released version 1.3  with some really big changes and improvements and 1.4 is soon to be released. Current todoMVC example in Meteor uses version 1.0.3 if I'm correct which is really old.

Another thing is that meteor dropped support for free deploy on their domain. I'm going to create new todoMVC using newest Meteor version following their most recent guidelines and try to get free galaxy account for this project so we can host it without further issues (They should go for it - it's in their best interest).

What do you think @passy ?

**Comment by michalsnik** [comment]
Btw. this issue duplicates #1611, so it would be reasonable close one of them

**Comment by michalsnik** [comment]
I created new TodoMVC example, and now I'm going to get hosting for it.
https://github.com/michalsnik/todomvc-meteor

When it's online I'll make separate PR with this.

**Comment by samccone** [comment]
👍

**Comment by arthurvr** [comment]
Any updates @michalsnik? Thanks in advance :)

**Comment by arthurvr** [comment]
Ah, sorry, I only just saw your PR. See #1670

**Comment by michalsnik** [comment]
Yup, I'm still waiting for a response in the PR you referenced :)
