### ISSUE TITLE
How do I start the server?

### ISSUE THREAD

**Issue by thejourneydude** [tastejs/todomvc#1627]
I rarely use npm or node so I'm absolutely lost on how to start the server. There are no instructions in the readme. I ran `npm install`. Everything works fine. I then run `npm start` but no file is set in `package.json` to run when starting npm.

My question is can we add some documentation for users new to Node/NPM on how to start their server locally. In my case I'm running the angularjs example.

**Comment by millerbryan** [comment]
@thejourneydude 

I notice some examples (AmpersandJS) include start declarations in their package.json files.  However, all of the examples I have run only require "npm install" to install packages (Node should not need to run for them to work).  Once that has completed, simply point your browser to index.html.

**Comment by tbranyen** [comment]
I just run a simple http server.  Something like this should work:

``` sh
cd todomvc
npm install http-server
http-server
```

The open up [http://localhost:8080](http://localhost:8080) to see the page. It's a static site, doesn't need anything more complicated than that.

**Comment by millerbryan** [comment]
So far, I have not had to run an HTTP server.  All of the code runs client-side in the browser (which is the point of client-side frameworks).  Do you recall which frameworks have required an http-server?   I have not tried it with Ampersand so far as it seems to run fine in the browser.

**Comment by tbranyen** [comment]
You probably don't need it, but when you're trying to test it in Browserstack or something, it makes a lot more sense to back it up with an actual address.

**Comment by millerbryan** [comment]
@tbranyen 

Good point!  I hadn't considered that aspect.

**Comment by yevgnenll** [comment]
i recommend that [browswersync](https://www.browsersync.io/)

**Comment by samccone** [comment]
+1 to what @tbranyen said

also python -m SimpleHTTPServer will work in the root folder.
