### ISSUE TITLE
Does this test work?

### ISSUE THREAD

**Issue by tbranyen** [tastejs/todomvc#1630]
From what I can tell this test isn't doing anything, and implementing it as written fails:

``` js
test.it('should remove the item if an empty text string was entered', function (done) {
  page.editItemAtIndex(1, webdriver.Key.ENTER);
  testOps.assertItems([TODO_ITEM_ONE, TODO_ITEM_THREE])
    .then(function () { done(); });
});
```

Yet if you comment out the `page.editItemAtIndex` line, the test still passes for the Backbone framework. I then went back to my implementation, and changed my app logic to not remove on empty string being edited (opposite of what this test is trying to prove), and it worked!

So I'm wondering if this test is broken. I don't know why the Backbone test passes with `page.editItemAtIndex` since it does a `model.destroy()` on empty text which should remove it.

**Comment by FadySamirSadek** [comment]
This is closed as the test suite has been completely changed
