### ISSUE TITLE
vanilla-es6 race condition?

### ISSUE THREAD

**Issue by iiSeymour** [tastejs/todomvc#1637]
In the [vanilla-es6](https://github.com/tastejs/todomvc/tree/master/examples/vanilla-es6/src) example  [`app.js`](https://github.com/tastejs/todomvc/blob/master/examples/vanilla-es6/src/app.js) creates a new [`todo`](https://github.com/tastejs/todomvc/blob/master/examples/vanilla-es6/src/app.js#L27) which creates a new [`View`](https://github.com/tastejs/todomvc/blob/master/examples/vanilla-es6/src/view.js#L56) which references the DOM on construction. All this could happen before the DOM is loaded, no? So when [`setView`](https://github.com/tastejs/todomvc/blob/master/examples/vanilla-es6/src/app.js#L29) is called after the DOM is loaded [`this.$todoList`]() could be `null`?

**Comment by flashdesignory** [comment]
Closing this, since we rebuilt the es6 example: https://github.com/tastejs/todomvc/pull/2207
