### ISSUE TITLE
Failure to npm install on Windows 10

### ISSUE THREAD

**Issue by davewallace** [tastejs/todomvc#1640]
Cloned today and after completion ran `npm install` which failed to fully install. I'm running in elevated privs mode and to note my work environment installed properly, which is also Windows 10 running `npm install` in elevated privs mode.

Console output here: https://gist.github.com/davewallace/3bef739c5a4957b087db28a0c3bd00b4

I've re-run `npm install` but no cigar. `gulp` subsequently also fails.

I've removed and re-tried the clone & install process a 2nd time to be sure, same deal.

It looks to be related to image dependencies.

**Comment by samccone** [comment]
Seems to be a npm imgmin issue not directly related to todomvc.

**Comment by davewallace** [comment]
Followup issue with imgmin here: https://github.com/gruntjs/grunt-contrib-imagemin/issues/109
