### ISSUE TITLE
Browser tests for Angular 2 still fail

### ISSUE THREAD

**Issue by vuesomedev** [tastejs/todomvc#1645]
I'm trying to submit my Angular 2 ES2015 example, but the tests still fail after upgrading to RC.3.
The `sendKeys` problem seems to be solved https://github.com/angular/angular/issues/6250, but there seems to be another issue.

The Xpath selector for the input field returns a promise, which is executed multiple times.
https://github.com/tastejs/todomvc/blob/master/tests/page.js#L257
In the highlighted line the `then` callback is executed multiple times until the timeout shuts down the test.

Tried to change the selector to select by css or class name, but it didn't help.
The same issue is present with the Angular 2 Typescript example.

**Comment by blacksonic** [comment]
Opened a ticket also on the main repo https://github.com/angular/angular/issues/9612

**Comment by flashdesignory** [comment]
Closing this, since we added a new Angular app: https://github.com/tastejs/todomvc/pull/2212
