### ISSUE TITLE
The Emberjs example page returns a 404

### ISSUE THREAD

**Issue by simondiep** [tastejs/todomvc#1650]
The link to the Emberjs TodoMVC example is not working.
http://todomvc.com/examples/emberjs/

**Comment by samccone** [comment]
For some reason ghpages does not like the symlinks we have in place
https://github.com/tastejs/todomvc/blob/master/examples/emberjs/index.html


A simple solution that I can think of would be to write a bit of code that walks the symlinks and just copies them over.
