### ISSUE TITLE
TodoMVC + Hapi

### ISSUE THREAD

**Issue by genediazjr** [tastejs/todomvc#1658]
Hi, I would like to ask if this would qualify to be included in TodoMVC. 

https://github.com/genediazjr/hapitodo
https://hapitodo.herokuapp.com

Thanks!

**Comment by arthurvr** [comment]
I've used Hapi before, it's quite neat. But it's a Node.js server framework, I kinda feel like it's out of scope for TodoMVC.

**Comment by genediazjr** [comment]
I was thinking it could be placed beside **Express + gcloud-node**. What do you think?
