### ISSUE TITLE
todomvc.com is down

### ISSUE THREAD

**Issue by MiguelAraCo** [tastejs/todomvc#1671]
http://www.downforeveryoneorjustme.com/todomvc.com

**Comment by roryp** [comment]
i thought my browser was broken!

**Comment by samccone** [comment]
thanks looking into it.

**Comment by roryp** [comment]
The irony is that i have a demo in 6 hours showing the site. Appreciate it if you could get it up

**Comment by sabakugaara** [comment]
+1  
```
Fastly error: unknown domain: todomvc.com. Please check that this domain has been added to a service.
```

**Comment by samccone** [comment]
@addyosmani is looking into this.

**Comment by sabakugaara** [comment]
It's up now
