### ISSUE TITLE
Common Lisp + Parenscript + React app

### ISSUE THREAD

**Issue by svetlyak40wt** [tastejs/todomvc#1681]
Hi, I want to submit an implementation in Common Lisp and Parenscript. I already rewrote basic React example, now polishing the code and making it more concise by using language's features.

What do you think, guys and girls?

**Comment by gitfoxi** [comment]
Sounds interesting. Where can I find it?

**Comment by svetlyak40wt** [comment]
I didn't finish it yet, because nobody was interested.

**Comment by gitfoxi** [comment]
You'd probably get more interest somewhere like https://www.reddit.com/r/Common_Lisp/ where there's a few enthusiasts. The TodoMVC crowd would probably take notice if it was something special in terms of performance, clarity, structure or lines-of-code.

For me personally, I'd like to see any example where someone did a good job of structuring a small, single-page web application in Lisp. I wonder if it's a good idea and can it even be done? There's probably an example somewhere but I haven't found it.

**Comment by svetlyak40wt** [comment]
Well, I've pushed my intermediate code, it is not completed yet though.

https://github.com/40ants/todomvc/blob/common-lisp-example/examples/common-lisp-react/src/app.lisp

It want to polish some details and to write instruction how to build it before making a pull-request.

**Comment by gitfoxi** [comment]
Thank you. It works quite nicely. In addition to your instructions in the readme, I had to install npm `brew install npm` on macon and run in `todomvc/examples/common-lisp-react`:

    npm install
    npm install http-server -g
    http-server

It works like magic. Thanks again. This will help me learn a lot.

**Comment by vindarel** [comment]
There's interest over there too ! I'd love to read about how it went, what you think of Panic' state, etc. Please come post something on reddit/lisp when you feel it.

ps: do you have any experience with [trident-mode](https://github.com/johnmastro/trident-mode.el) / Skewer ? (for live browser interaction)

pps: and if you'd like more challenge, nobody started a lisp version of [RealWorld](https://github.com/gothinkster/realworld) (a Medium clone) :] (and nobody [seems interested (reddit)](https://www.reddit.com/r/lisp/comments/6973q5/who_will_write_a_backend_andor_frontend_for/)).

**Comment by svetlyak40wt** [comment]
> ps: do you have any experience with trident-mode / Skewer? (for live browser interaction)

I have it in my bookmarks but still didn't try.

> I've seen this RealWorld post at reddit, but have no time for this. I'm more interested in Weblocks reanimation.

**Comment by svetlyak40wt** [comment]
I'm closing this issue, because lack of time to push the example into the upstream. Sorry, guys.
