### ISSUE TITLE
EmberJS TodoMVC Broken

### ISSUE THREAD

**Issue by SIRHAMY** [tastejs/todomvc#1695]
The link from the main pages directs to: http://todomvc.com/examples/emberjs/index.html/examples/emberjs/

The URL returns a 404 not found error.

**Comment by Luiz-N** [comment]
The working url is:
[http://todomvc.com/examples/emberjs/index.html](http://todomvc.com/examples/emberjs/index.html)
It's probably just some sort of re-direct bug.

**Comment by arthurvr** [comment]
Hm, indeed, strange. I guess something's going on in its router. I don't really have time to investigate this myself atm though, so PRs welcome 😆  The ember apps needs some serious cleanup regarding some other stuff too btw :/

**Comment by arthurvr** [comment]
Oh, this is a duplicate of https://github.com/tastejs/todomvc/issues/1650, sorry :)
