### ISSUE TITLE
firefight js TodoMVC

### ISSUE THREAD

**Issue by afrievalt** [tastejs/todomvc#1702]
Very new to open source, please be kind.  
# Firefight js TodoMVC

[TodoMVC](https://firefight.firebaseapp.com/samples/TodoFirefight/index.html)
[example source gist](https://gist.github.com/afrievalt/5677ce1e65568311ebce7e1c39f8c9d8)
[framework source](https://github.com/afrievalt/firefight)
[framework website](https://firefight.firebaseapp.com/)
### Easiest SPA library

Firefight.js is a JavaScript library that allows non-JavaScript programmers to decorate their HTML to provide dynamic / real-time data from Firebase.
### Features
- RealTime
- Build a single page app in a [single page](https://gist.github.com/afrievalt/5677ce1e65568311ebce7e1c39f8c9d8)
- Shared db with [Firebase + AngularJS](http://todomvc.com/examples/firebase-angular/)
- No build required
- No JavaScript required 
### Tests

All tests manually passing in chrome,
Blur issue fond in ie, more testing to come
### Roadmap:
- Respond to feedback, focus on easy interface
- Remove Firebase dependency, allow Gun, REST or no db.  Allow multiple connections.  
- Create and document extension points
- Add more social features 
- Reduce size and increase performance .  Remove jQuey
- Make SEO friendly -  Make isomorphic 
- transpile  to other frameworks

**Comment by arthurvr** [comment]
Thanks for working on this. Nice work so far! I think we should wait till the framework and its community matures a bit though. Anyone else any thoughts on this one?

**Comment by arthurvr** [comment]
Feel free to ping us a little later when you feel like we should look at this again.  I might just have overlooked it when checking the repo in a hurry, but did you write any tests for the code? I'd be very reluctant to promote any framework that doesn't have any tests at all. 😃
