### ISSUE TITLE
Angular app with ES6, components, etc.

### ISSUE THREAD

**Issue by nuragic** [tastejs/todomvc#1707]
Hi!

Would you consider a new Angular app built with ES6, and components? 

Thanks!

_PS: if is not the case, feel free to close quickly and sorry for the noise ;)_

**Comment by arthurvr** [comment]
Let's close this and discuss those in https://github.com/tastejs/todomvc/issues/1613 and https://github.com/tastejs/todomvc/issues/1565. There's already an open PR so feel free to help us review it 😺
