### ISSUE TITLE
Cannot use External Keyboard to create item with Vue.js

### ISSUE THREAD

**Issue by garrytaulu** [tastejs/todomvc#1717]
With every example I am able to use the iPad Pro Smart Keyboard to create new todo items by typing the item then pressing Enter. Unfortunately this does not work on your example using Vue.js.

**Comment by arthurvr** [comment]
Hm, strange, I'm able to confirm this. Thanks for the report! (It's also reproducible in the Xcode simulator, it works when tapping enter but not if you use your actual keyboard's enter key.)

The Vue app needs to be updated to Vue 2.0 too btw. PR welcome :)

cc @yyx990803

**Comment by FadySamirSadek** [comment]
please refer to #2218
