### ISSUE TITLE
Why doesn't changing CSS not change the website?

### ISSUE THREAD

**Issue by nikitavoloboev** [tastejs/todomvc#1720]
I am trying to experiment with some of the websites, in particular vanilla-es6 and I have tried changing the CSS and then refreshing the page that my server spits out to localhost but nothing changes.

In fact if I completely erase the css file that is referenced from the html, I still get a fully styled website, how can that be?

Thank you for any help.

**Comment by arthurvr** [comment]
It works fine for me. What CSS file are you editing? `node_modules/todomvc-app-css/index.css`? Can you try in an incognito browser window?

As this sounds like a problem with your personal setup rather than our code I'm gonna close this issue :)
