### ISSUE TITLE
todomvc vue:  complete the list in the 'active' tab,  get a weird list

### ISSUE THREAD

**Issue by shellphon** [tastejs/todomvc#1736]
http://todomvc.com/examples/vue/#/active

when I input todo item  for example :  todo1, todo2, todo3

then I click the 'Active' tab and I tap 'todo1' to mark it as completed, then the list for the active todos shows like this:
√  todo2
    todo3

actually, the checkbox of the 'todo2' should not be checked .

**Comment by jjimenez** [comment]
I noticed the same issue and created a pull request for this.  See pull request #1835

**Comment by flashdesignory** [comment]
Closing this, since we updated the Vue app: https://github.com/tastejs/todomvc/pull/2213
