### ISSUE TITLE
hello, i have one question in angularjs-todomvc about the 'indexOf(todo)'

### ISSUE THREAD

**Issue by Jionl** [tastejs/todomvc#1740]
hello, i have one question in angularjs-todomvc about the 'indexOf(todo)';
why 'indexOf(todo)' can help us find a object in array?

**Comment by arthurvr** [comment]
Check [`Array.prototype.indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf). Our bug tracker isn't a good place for support questions.
