### ISSUE TITLE
e2e tests for all frameworks

### ISSUE THREAD

**Issue by miherlosev** [tastejs/todomvc#1742]
Example pages contains a lot of script errors that don't find by testing tool.
For example for http://todomvc.com/examples/angularjs:
```
http://todomvc.com/api Failed to load resource: the server responded with a status of 404 (Not Found)
2017-01-10 11:10:07.832 
http://todomvc.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

Also tests executed only on Chrome browser.
I can rewrote tests using [Testcafe](https://github.com/DevExpress/testcafe).
It will catch script errors and run tests on two browsers - Chrome and Firefox.
What do you think?

**Comment by FadySamirSadek** [comment]
@miherlosev we have recently started using cypress for testing but it still needs work, would you like to help ?

**Comment by miherlosev** [comment]
I think cypress it is not best choice for e2e. TestCafe allows to easy run tests in most popular browsers, cypress - only in Chrome. 
I can create an example of test. You can see how it looks and works.

**Comment by samccone** [comment]
Thanks for the recommendation @miherlosev, let us know if you want to help with our existing effort with cypress! 

Cheers.
