### ISSUE TITLE
Any plan to extend this project into the realm of backend?

### ISSUE THREAD

**Issue by greenlaw110** [tastejs/todomvc#1756]
So that we have:

* A standard API spec 
* A good showcase comparing both FE (already done) and BE (as a RESTful service provider) solutions
* Optionally authentication/authorisation/auditing support
* Checking on common security issues e.g. XSS/CSRF etc

**Comment by sindresorhus** [comment]
We started https://github.com/tastejs/TasteStack, but no one was interested in pushing the project forward. Go ahead an start something, and we would be happy to link/promote it if it's well maintained.
