### ISSUE TITLE
Angular2 demo is broken on IE

### ISSUE THREAD

**Issue by fredgate** [tastejs/todomvc#1766]
The angular2 demo does not load on IE11. It is because system.js is not correctly loaded. On IE11, shims for systemjs are required but are not present on the server.
It tries to load the file located at this URL http://todomvc.com/examples/angular2/node_modules/systemjs/dist/system-polyfills.js.
But it produces a HTTP 404 error and the application does not start.

**Comment by flashdesignory** [comment]
Closing this, since we added a new Angular app https://github.com/tastejs/todomvc/pull/2212
