### ISSUE TITLE
Adding YUI3 to the TodoMVC page

### ISSUE THREAD

**Issue by virajkulkarni14** [tastejs/todomvc#1768]
Hi there,

Is it possible to include ToDo examples from legacy frameworks like YUI3? AFAIK, YUI is still in use, so it might help some developers. If you are okay with such a PR, should I include it under the JavaScript tab or can we do either of the following?:

1. Create a Legacy tab, next to JavaScript, Compile-to-JS, etc.
2. Create a Legacy section, like Real-time, Node.js, etc.
3. Include legacy frameworks under the JavaScript tab, but flag it as Old or Legacy, like "R = App also demonstrates routing"

Please let me know which one would suit the page better, I will accordingly add YUI and create a PR.

Thank you!
Viraj

**Comment by FadySamirSadek** [comment]
Thank you so much for creating this issue , the goal of the TodoMVC project is to be a curation not a collection of current javascript frameworks for developers deciding what framework to use next for their project. While it is true that there are some legacy apps that still use YUI and one can learn a lot from these libraries having a lot of libraries/frameworks on the site may add an extra layer of confusion .
