### ISSUE TITLE
Require some validation logic?

### ISSUE THREAD

**Issue by cluelessjoe** [tastejs/todomvc#1769]
When comparing the various libs used, I always wonder how nicely they handle - or not - validation. For example how would they display an error message if "foo" was contained in any of the todos. 

Do you think it would be worthwhile to add some validation as a requirement for TodoMVC apps?

cheers !

**Comment by FadySamirSadek** [comment]
What sort of things you are looking to validate ?

**Comment by whitefire0** [comment]
I would tentatively suggest this issue be closed as I am not sure there are any use cases that would require validation - it is a todo list!

**Comment by FadySamirSadek** [comment]
@whitefire0 Thanks
