### ISSUE TITLE
error in angularjs example

### ISSUE THREAD

**Issue by kai-steven** [tastejs/todomvc#1771]
I'm going through the angularjs example app and am fairly sure I found an undetected bug.  It doesn't affect the functionality but is confusing.  

In the saveEdits controller function, the store service gets called like this:
```
			store[todo.title ? 'put' : 'delete'](todo)
				.then(function success() {}, function error() {
					todo.title = $scope.originalTodo.title;
				})
				.finally(function () {
					$scope.editedTodo = null;
				});
```
and store.put looks like:
```
`			put: function (todo, index) {
				var deferred = $q.defer();

				store.todos[index] = todo;

				store._saveToLocalStorage(store.todos);
				deferred.resolve(store.todos);

				return deferred.promise;
			}`
```
Notice the index argument is not supplied.  After fiddling with the debugger, I saw that setting store.todos[undefined] = todo does not harm the array. 

I think that because of this line in the controller:
``		var todos = $scope.todos = store.todos;
`
that store.todos is always kept up to date by the $scope.todos changes (pass by reference).  so the call to store.put(todo,index) is not really needed in this case.  

Here is some of my console.log debugging about the array object equivalence
```
store.todos[1]
Object {title: "123 456 edited", completed: false}completed: falsetitle: "123 abcdef"__proto__: Object
$scope.todos[1]
Object {title: "123 456 edited", completed: false}
// simulate editing the $scope.todos
$scope.todos[1].title = "123 abcdef";
"123 abcdef"
$scope.todos[1]
Object {title: "123 abcdef", completed: false}
store.todos[1]
Object {title: "123 abcdef", completed: false}   // store.todos updated for free.

```
I guess I would recommend just fixing the call to store.put so it passes the index?

**Comment by flashdesignory** [comment]
Closing this, since we added a new Angular app https://github.com/tastejs/todomvc/pull/2212
