### ISSUE TITLE
RenderJS Example

### ISSUE THREAD

**Issue by eyqs** [tastejs/todomvc#1773]
[RenderJS](https://renderjs.nexedi.com/) is a fully promise-based JavaScript library for building single-page web applications. It uses modular components, called gadgets, which contain HTML and vanilla JavaScript. Its main features are the incredibly simple API, the ability to easily create and embed third-party gadgets into the framework, and the concept of _acquisition_ as a means of communication between gadgets.

Because RenderJS development solely focuses on gadgets, it is not a MVC framework in the traditional sense. However, it is easy to create separate model and view gadgets to emulate a MVC framework, and [that's exactly what I've already done](https://softinst75722.host.vifib.net/public/).

Full disclaimer: I work for [Nexedi](https://www.nexedi.com/), the French open-source company behind RenderJS. Although it is not as popular outside of France enterprises, RenderJS has been in active development for the past five years and is now used in production in many web apps.

I'd like to add RenderJS to the TodoMVC labs, so I've opened this issue to discuss its inclusion first. If everything seems alright, then I will add the learn bar and package [my working example](https://lab.nexedi.com/eyqs/todomvc/tree/renderjs/examples/renderjs) into an actual npm module.

**Comment by whitefire0** [comment]
@FadySamirSadek Proposing close as related to comment in PR #1823
