### ISSUE TITLE
jQuery version setroute director bug

### ISSUE THREAD

**Issue by Jamamuuga** [tastejs/todomvc#1778]
In the director (examples/jquery/node_modules/director/build/director.js), in the method Router.prototype.setRoute, there is a call on line 234 to url.splice(i, v, s) where the variable "s" is not defined anywhere...

**Comment by Jamamuuga** [comment]
Unfortunately, I haven't studied the code enough to write up a pull request. It was used as an example in a class that I am taking. We were learning to study code & when I opened up director.js in a code editor, it underlined it and said undefined variable. Somewhere I read that director.js was from or inspired by the project flatiron/director. When I looked at their's, it didn't seem to be currently anywhere close enough to be of any help...

**Comment by flashdesignory** [comment]
Closing this issue, since we updated the jQuery example: https://github.com/tastejs/todomvc/pull/2205
