### ISSUE TITLE
Error ELIFECYCLE errno 10 running tests

### ISSUE THREAD

**Issue by pmros** [tastejs/todomvc#1779]
I get `ELIFECYCLE` `errno 10` when I run npm `run test -- --framework=angular2_es2015`. It stops at test number 10. it works for me with `--framework=angularjs`.
I'm trying to test my own framework, called Cyclow, but it fails at test number 2.
Thank you in advance.

**Comment by FadySamirSadek** [comment]
you can try rebasing your code with the master branch, we have just replaced the test suite from selenium to cypress and it is working for some frameworks while the past test suite was broke.
