### ISSUE TITLE
gh-pages branch has not been updated 

### ISSUE THREAD

**Issue by patrickkettner** [tastejs/todomvc#1780]
I got in a [fix](https://github.com/tastejs/todomvc-app-css/pull/8) in for [todomvc-app-css](https://github.com/tastejs/todomvc-app-css) few weeks back, and noticed it wasn't working on todomvc.com. When I checked, I saw that most of the assets in the gh-pages branch haven't been touched in [9 months](https://github.com/tastejs/todomvc/tree/385da5d55ecbb2b1b0255402577f39f08a79d6a0/examples). Since it is a separate package, they apparently need to be kicked in order to get the updated css.

How would one go about updating the site to the latest module versions?

**Comment by digitarald** [comment]
Another part of the issue might also be that `package.json` in each test folder might link to the latest assets, but 1node_modules` is also checked in and has a much older version of the assets.

**Comment by patrickkettner** [comment]
ping @samccone @addyosmani @passy any chance one of you could update (happy to do it myself if given the rights)

**Comment by samccone** [comment]
The fix here is to go into each example and to pull in the latest todomvc-app-css. it is a bit of a tedious task.. but I will gladly land the change :D

**Comment by patrickkettner** [comment]
really? most just need an npm install, as it is within the range in their package.json. Is that not included as a step in the publish to travis process?
