### ISSUE TITLE
Add wolkenkit version

### ISSUE THREAD

**Issue by goloroden** [tastejs/todomvc#1792]
I would like to contribute a version of TodoMVC built using [wolkenkit](https://www.wolkenkit.io/). wolkenkit is an open-source Node.js backend that builds on the concepts of CQRS, DDD and event-sourcing.

Due to its relation to DDD it avoids the typical `CRUD` terminology, and instead favors a more meaningful, semantic terminology. E.g., if you remove an item from the list, with wolkenkit it is possible to differ between an item that is discarded (i.e., it was not completed before it was removed), and and item that is archived (i.e., it was completed).

Since all these semantics are stored as deltas, you can run nice reports on what your users did, e.g.: How many times did a user check and uncheck an item before it was finally discarded? How much time went by between creating an item and ticking it off for the first time? …?

I think that this could be a great demo, especially compared to the one built on top of Firebase, as you can run wolkenkit on your own machine and are not limited to a hosted cloud version.

What do you think? Could this be of interest to you?

**Comment by goloroden** [comment]
Ping 😉

**Comment by w990752800** [comment]
666

**Comment by FadySamirSadek** [comment]
Please refer back to our new app guidelines
