### ISSUE TITLE
< IE 11 Considered End of Life

### ISSUE THREAD

**Issue by snuggs** [tastejs/todomvc#1795]
Microsoft has sunsetted ALL Internet Explorer projects prior to 11. _**[Please read the End of Life announcement here](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support)**_.

Would be much appreciated to change requirements for submitting a project. There are some projects such as our own that are taking Micro$oft's advice and allowing the web to progress. I feel it removes more modern libraries who only support back to IE11 (As Microsoft suggests) from being able to submit.

https://github.com/devpunks/snuggsi/#browser-support

We are currently preparing for [a new todomvc entry here](https://github.com/devpunks/snuggsi/issues/85) and are not able to submit with the IE9 requirement.

Will submit a Pull Request shortly...

/cc @brandondees @tmornini @halorium

**Comment by FadySamirSadek** [comment]
Thanks for filing this issue.
Updated browser support to only include >IE 11.

**Comment by snuggs** [comment]
@FadySamirSadek the pleasure is all mine! Would love to help wherever I can.
