### ISSUE TITLE
backboneJS todo-renaming bug

### ISSUE THREAD

**Issue by asutosh97** [tastejs/todomvc#1802]
The Bug:- In the backboneJS version of the app, if we try to rename a todo by double-clicking on its name, then instead of the prompt appearing in the end of the todo-name as it appears in the rest of the versions, it appears in the beginning of the name.

I am interested in fixing the fixing the issue, but I'm new to open source contribution. So, can you please guide me how to proceed.

**Comment by FadySamirSadek** [comment]
closed as per #1916
