### ISSUE TITLE
Bug in react example, checkbox not remaining checked when expanding the todo's list

### ISSUE THREAD

**Issue by Olian04** [tastejs/todomvc#1810]
__How to replicate:__ 
1. [Open the react demo](http://todomvc.com/examples/react/)
2. Add a TODO
3. Navigate to the `Active` tab
4. Check the TODO
5. Press the `Down Arrow` next to the search bar
    * The TODO should now show up `unchecked`

**Comment by dhruvdutt** [comment]
I don't think that a bug. The `Down Arrow` :arrow_down: works like this:
- If some TODOs are partially checked or all TODOs are unchecked, it checks all TODOs.
- If all TODOs are checked, it un-checks all TODOs.

Since in this case, all TODOs (only one) was/were checked, it un-checked it.
