### ISSUE TITLE
heroku deploy "application error"

### ISSUE THREAD

**Issue by nk932714** [tastejs/todomvc#1817]
How to deploy this repo on Heroku 

when deploying this to heroku it displays application error 

![image](https://user-images.githubusercontent.com/29853208/29867431-2ed2ec98-8d99-11e7-816b-6d9e4a98e7dc.png)

**Comment by jdebettencourt** [comment]
Perhaps this has been answered elsewhere, but Heroku isn't likely to work the best as a demo server platform for the ToDoMvc examples. The Heroku platform works best when it is supporting fully-built applications as a basic Heroku app usually can't write new files which means it really can't support npm scripts for serving development environments or building production files. And, the pure javascript examples can even be tested in some cases by pointing a browser at them or serving them from even a client-side static page server.

**Comment by nk932714** [comment]
Thanks @jdebettencourt for info :+1:
