### ISSUE TITLE
Using tests for any repo

### ISSUE THREAD

**Issue by LMnet** [tastejs/todomvc#1818]
I'm working on https://github.com/LMnet/scala-js-preact library. I have a todomvc implementation in a subproject in the scala-js-preact repo. I want to run todomvc tests against my implementation. But currently, I can't do this without forking https://github.com/tastejs/todomvc repo and adding my implementation inside. Of course, I have a plan to do this. But as a first step, I want to add to my travis pipeline todomvc tests.

It would be cool if tests will not be tightly connected to this repo. Selenium tests could test any page with specified URL. I want to give URL to the test runner and run todomvc tests against my implementation in my repo.

Can I somehow achieve this?

**Comment by kt3k** [comment]
Hello

I'm not a maintainer of this repo, but I created a standalone cli tool to test TodoMVC implementation on the given url. See https://github.com/kt3k/todomvc-test . The test cases are basically copied from this repo's `tests/` directory and must be compatible with them. ( I created this tool to test my TodoMVC impl https://github.com/capsidjs/todomvc ). I hope this tool is useful for your case as well.

**Comment by LMnet** [comment]
@kt3k Thank you a lot! I just tried your project and all works great!

But I think this approach is acceptable only as a temporary solution. To keep your tests up to date you should manually track changes in the todomvc repo and migrate it to your repo.

**Comment by kt3k** [comment]
@LMnet Thanks for trying my tool!

Yes, I need to follow the change of this repo's tests, but I think that's not difficult because the tests seem very stable these days and didn't get that many commits recently. (For example, no commits yet in this year)

**Comment by FadySamirSadek** [comment]
This is definitely something the team have in mind but currently the test are broken and there are efforts by the cypress.io team to convert all the selenium test to cypress this will make a great addition to our new test suite. Thank you so much for raising this :D

**Comment by FadySamirSadek** [comment]
@LMnet  no this repo is not going to be abandoned the only thing changing is out current test suite we are replacing selenium with cypress.io but since this step will take a long time we will not be able to implement your requirement anytime soon but we will have it in mind when we integrate the cypress test. The reason I closed this issues is that we are currently cleaning up and collecting all issues related together so we can tackle them.

**Comment by LMnet** [comment]
@FadySamirSadek is there any issue I can subscribe on?

**Comment by kt3k** [comment]
I guess probably this one https://github.com/tastejs/todomvc/issues/1843

**Comment by kt3k** [comment]
And [this one](https://github.com/tastejs/todomvc/pull/1861) as well
