### ISSUE TITLE
Meteor todo app

### ISSUE THREAD

**Issue by devagrawal09** [tastejs/todomvc#1828]
Seems like todomvc is missing an app made using Meteor, which is a bad thing as Meteor is undoubtedly one of the major frameworks now. Although meteor already has an example [todos app](https://github.com/meteor/todos), it does not fit into the todomvc specifications, so I have decided to build one up. I believe that meteor todo app would come under the category of real-time. So should I start working on it or will it not qualify for todomvc?

**Comment by FadySamirSadek** [comment]
In fact there is a todoMVC app for meteor but it is not hosted as todomvc is being hosted using ghpages and it does not allow hosting of non static files as meteor. It used to be hosted if I can remember correctly before meteor dropped their instant deploy feature. You can still clone the repo and check the [meteor folder](https://github.com/tastejs/todomvc/tree/master/examples/meteor) in the examples directory but it is a bit old it is developed using meteor 1.1 while meteor is now at 1.6 so if you want to contribute by creating a PR and updating the meteor version it would be awesome💪 as you mentioned meteor is one of the major frameworks in the scene now. Thank you for raising this 👍

**Comment by devagrawal09** [comment]
I can deploy the app on Heroku with a mongodb sandbox database. I found a Heroku buildpack that nicely builds the Meteor app. In fact I already have an application I built using meteor running in Heroku. I will upload is soon and create a PR.
