### ISSUE TITLE
sapiui5 example not working

### ISSUE THREAD

**Issue by atherdon** [tastejs/todomvc#1831]
I think it's just outdated
posting my dev tool screen

![image](https://user-images.githubusercontent.com/1469198/32066635-1d4a5660-ba89-11e7-86a6-218efb2b1c2d.png)

**Comment by FadySamirSadek** [comment]
It is working you are having a problem with CORS. You need to run TodoMVC in localhost to be able to use it . Try running gulp serve after installing gulp globally and the TodoMVC npm packages.
