### ISSUE TITLE
SPAllinsonJS • TodoMVC

### ISSUE THREAD

**Issue by ChrisAllinson** [tastejs/todomvc#1834]
**SPAllinsonJS** is a fully functioning MVC Javascript framework that helps you build Single Page web Apps! Features include: _Routing, Deeplinking, Bookmarking, Components, Singletons, Services, Data Binding, Repaint, Repeat, Notifications, Ajax, Localization, Splash Screen, Preloading, Debug Console, Alerts, Lightbox, Storage_ ...

More information:
[http://www.spallinsonjs.com](http://www.spallinsonjs.com)

---

I've completed the TodoMVC Example app using SPAllinsonJS, and would like to make a PR :)

The app:
[http://www.allinson.ca/a/todomvc](http://www.allinson.ca/a/todomvc)

Source code:
[http://www.spallinsonjs.com/#/home/developer/todomvc](http://www.spallinsonjs.com/#/home/developer/todomvc)

**Comment by FadySamirSadek** [comment]
Thank you so much for your interest in contributing to the TodoMVC project. TodoMVC aims to be a curation not a collection of the most famous and widely used frameworks to ease out the pain new developers have when deciding to choose a new framework for a project. I do not think this is the right time for this framework to be added to the examples list but you can use the TodoMVC project to demonstrate to your new users the features of your framework. Feel free to ping us sometime in the future when your framework gets more traction and thank you so much for your contribution :D
