### ISSUE TITLE
[Angular 2]: Change 'Boolean' to 'boolean'

### ISSUE THREAD

**Issue by oreqizer** [tastejs/todomvc#1836]
See https://github.com/tastejs/todomvc/blob/gh-pages/examples/angular2/app/services/store.ts for example.

`Boolean` is a boolean object type, while `boolean` refers to the primitive value. The values are typed as `Boolean`s, but used as `boolean`s.

**Comment by flashdesignory** [comment]
Closing this issue, since we added a new Angular app: https://github.com/tastejs/todomvc/pull/2212
