### ISSUE TITLE
Angular 2 - Test Error: NoSuchElementError

### ISSUE THREAD

**Issue by pablo-albaladejo** [tastejs/todomvc#1841]
Hey there,

At my PR #1840 of Angular2 implementation I'm getting

```
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".todo-list li"}
[...]
From: Task: WebDriver.findElement(By(css selector, ManagedPromise::594 {[[PromiseStatus]]: "pending"}))
```

Find full log at [travis](https://travis-ci.org/tastejs/todomvc/builds/321167026)

I find this issue is also present at #1741 and #1103.
May I kindly ask for some help? I'm stuck.

Thank you in andvance.

**Comment by FadySamirSadek** [comment]
@pablo-albaladejo  you should check in your .gitignore file as well as your node_modules and in your .gitignore file you should ignore all the modules except the ones that are being used by your application as todomvc-common/base.js and todomvc-common/base.css . I can not find those in your PR , try adding them and try again.

Here is an example from the angular firebase .gitignore file notice at the end he is leaving the todo-mvc common files . 
Also check[ app-spec.md](https://github.com/tastejs/todomvc/blob/master/app-spec.md).
Tell me if this works thanks.
```
the node_modules/angular/*
!node_modules/angular/angular.js

node_modules/angularfire/*
node_modules/angularfire/dist/*
!node_modules/angularfire/dist/angularfire.js

node_modules/todomvc-app-css/*
!node_modules/todomvc-app-css/index.css

node_modules/todomvc-common/*
!node_modules/todomvc-common/base.css
!node_modules/todomvc-common/base.js
```
