### ISSUE TITLE
How do I submit a new exemple for an App?

### ISSUE THREAD

**Issue by victorgarciaesgi** [tastejs/todomvc#1844]
Reading the guidelines do I understand that I have to make a pull request on master and put my app in the exemple folder.

Btw it's a typescript-vue TodoMvc and i didn't see it anywhere so asking if it helps!

**Comment by FadySamirSadek** [comment]
@victorgarciaesgi you are correct . You need to fork this repo create a new branch then add the example you created to the examples folder along with a read.me and unit test(optional but preferred). After that when you are ready to make a PR make sure you are following the [contribution guidelines](https://github.com/tastejs/todomvc/blob/master/contributing.md) and make your PR against Default:master branch. 
Regarding your question about whether it is a good idea or not to add a typescript-vue example you should check the paragraph about  "Considerations before submitting a new app" in the contribution guideline and make sure your example brings something new to the table. I can not tell you if a typescript-vue is something that follows this criteria , you should make this decision based on your understanding of the technology and the contribution guidelines.

 **My personal opinion** I have seen a typescript-angular , typescript-backbone and typescript-react so I think it make sense to have a typescript-vue version but I am not very familiar with vue or the community around it and how much does it impact to have a typescript-vue version so you should make this decision using contributing.md as your guide also check this awesome article about [Front-end Choice Paralysis](https://addyosmani.com/blog/front-end-choice-paralysis/) by Addy Osmani  .

**Comment by FadySamirSadek** [comment]
@addyosmani  @samccone  This one can be closed too

**Comment by victorgarciaesgi** [comment]
@FadySamirSadek  I posted it on Reddit on the feedback was great so that's why I wanted to contribute to the TodoMVC exemples. I have read all the contribution guidelines(Readme etc..) and I have made a pull request but not on the good branch I think. 
It don't have unit test thought

**Comment by FadySamirSadek** [comment]
@victorgarciaesgi  Awesome 🎉I can see you have done your homework. Unit tests are not mandatory to get your example accepted but it is always a good thing to have I can not find your PR comment with a URL to your PR so I can check it and help if I can . Glad you are picking this one up 💪

**Comment by victorgarciaesgi** [comment]
@FadySamirSadek I will resubmit it shortly i'm just reducing the node_module size and making a production build! Thanks for your help 💯

**Comment by victorgarciaesgi** [comment]
@FadySamirSadek do I have to commit on master before making a pull request?

**Comment by FadySamirSadek** [comment]
No , you can do whatever you want on your fork but I prefer to create a new feature version on your fork for example typescript-vue-example branch and when creating the PR you chose todomvc:master as your target check[ this article](https://help.github.com/articles/creating-a-pull-request/) for more info

**Comment by nithindavid** [comment]
Hi @victorgarciaesgi,
Can you close this issue if you think its resolved ?
Thanks 😸

**Comment by victorgarciaesgi** [comment]
@FadySamirSadek  @nithindavid  The build failed just because of indentation rules, how do I fix this?  I've seen nowhere coding style mentionnend
