### ISSUE TITLE
ReactDOM vs. custom re-render

### ISSUE THREAD

**Issue by whitefire0** [tastejs/todomvc#1853]
The current React todoMVC implementation uses a custom re-render process, as opposed to harnessing the in-built power of ReactDOM and state management. I used React todoMVC to start my learning process with React, only later learning of features since released. Do the contributors here feel there would be any advantages in implementing this feature into the app - I'm thinking particularly in regards to those who used the source code for the same purposes as myself.

Best regards,
Rick

**Comment by FadySamirSadek** [comment]
@whitefire0  I think it is a good idea to update the react example as the react example has not been updated since version 0.13.3 two years ago and we are now in react fiber 16.2.0 . 
Are you interested to work on this @whitefire0 ?

**Comment by whitefire0** [comment]
I would be very keen to work on this! @FadySamirSadek 

Would you have any specific requirements to help me focus the development process?

**Comment by FadySamirSadek** [comment]
@whitefire0 I checked open PRs and found a really nice one at #1767 that was reviewed by  Dan Abramov the creator of create-react-app himself but not all the feedback have been addressed so if you want you can start where they left of and mention me if you need help . Glad you are keen to help and can not wait to see it live 💪

**Comment by whitefire0** [comment]
@FadySamirSadek that looks great, thank you - one way or another I'll be in touch!

**Comment by FadySamirSadek** [comment]
Unless you have more questions can you please close this issue and follow our conversation in your PR ?
