### ISSUE TITLE
"Vue.js on GitHub" link incorrect

### ISSUE THREAD

**Issue by AndrewBerry** [tastejs/todomvc#1858]
The link for "Vue.js on GitHub" listed under the official resources for http://todomvc.com/examples/vue/ links to https://github.com/yyx990803/vue instead of https://github.com/vuejs/vue.

**Comment by FadySamirSadek** [comment]
@AndrewBerry Thank you for opening this issue . The link has been fixed [here](https://github.com/tastejs/todomvc/commit/fc72ed61752302acded4f8ce8ae631a718d1987e) but has not been deployed yet but will be very soon.

**Comment by slayoo** [comment]
The old link is still there as of now. HTH

**Comment by FadySamirSadek** [comment]
@slayoo  will try to merge master branch with gh pages ASAP for this fix to be deployed
