### ISSUE TITLE
Add me to tastejs GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [tastejs/todomvc#1859]
Add me to tastejs GitHub Org, Know about me https://yoginth.ml

**Comment by FadySamirSadek** [comment]
@YoginthS you can find a list [here](https://github.com/tastejs/todomvc/issues/1842) by Addy Osmani on the things that the project need help with so pick up the thing you want to help with and comment on the issue to tell Addy and the team that you picked this specific task and you will start working on it. They add contributor privileges after you make some contributions to the project.

**Comment by Naylor55** [comment]
1




At 2018-03-11 19:41:02, "Fady Samir Sadek" <notifications@github.com> wrote:


Closed #1859.
