### ISSUE TITLE
Complete and fix cypress test

### ISSUE THREAD

**Issue by FadySamirSadek** [tastejs/todomvc#1866]
The goal of this issue is to collect all sub issues related to failing tests to either fix them or fix the tests themselves 
The specification states that edits should be cancelled on escape:
- [x] Mark all items as completed &  Mark all as completed should allow me to clear the complete state of all items :
 `<input id="toggle-all" class="toggle-all" type="checkbox">` is being covered by other elements. Exists in most of the examples.
- [x] No Todos should hide #main and #footer:
Exists in Ambersand, chaplin-brunch
- [x] Routing should allow me to display active items : 
Exists in ariatemplates along with all routing tests as routing is not working in ariatemplates
- [ ] Clear completed button should be hidden when there are no items that are completed : 
Exists in backbone_marionette

Second category Five or more tests not working in : 

- [ ]  chaplin-brunch 
- [ ]  enyo_backbone 
- [ ]  webrx
- [x]   vanillajs
- [ ]   vanilladart
- [x]   vanilla-es6
- [ ]   socketstream
- [ ]  serenadejs
- [ ]   sapui5
- [ ]  reagent
- [ ]   rappidjs
- [ ]   olives
- [ ]  meteor
- [x]   jquery
- [ ]   humble

Note: Fixing the first four tests will fix the build in a lot of examples while the examples in the second category need some work as some of them do not even implement routing and others need a server to run

**Comment by FadySamirSadek** [comment]
First one closed in favor of #1867

**Comment by gj262** [comment]
Hi @FadySamirSadek, I took a look at the test failures for vanillajs. I think I have a PR ready. Shall I open a separate issue to track that? 
Thanks,
-Gavin

**Comment by FadySamirSadek** [comment]
@gj262 yes please do that and than you for picking this up

**Comment by gj262** [comment]
thanks @FadySamirSadek @samccone for reviewing my changes. Fixing Cypress tests is fun 💥 🎉
