### ISSUE TITLE
jQuery: after clearing completed todos, filter is always back to 'all'

### ISSUE THREAD

**Issue by ugitch** [tastejs/todomvc#1869]
No matter what filter is selected prior to clicking "Clear completed", filter is always back to "all". Filter should retain the same value, as in other MVC examples.

**Comment by FadySamirSadek** [comment]
@ugitch nice catch , do you want to work on this ?

**Comment by ugitch** [comment]
@FadySamirSadek Thanks! I'd love too..

**Comment by FadySamirSadek** [comment]
Closed in favor of #1871
