### ISSUE TITLE
TodoMVC 1.5 🦄

### ISSUE THREAD

**Issue by FadySamirSadek** [tastejs/todomvc#1880]
# TodoMVC 1.5

This issue is open for discussion about what you think we should do in the next release.
Here is a list of some of the ideas that I think would be very cool to implement :
### Examples : 
- [x] Create a clear guideline to help us decide what makes a framework mature, production ready and fit to be added to TodoMVC.
- [x] Remove frameworks that are no longer maintained or have a clear better alternative as TodoMVC is a curation not a collection of frameworks and its main goal is to help developers pick a framework to learn or use for their next project https://github.com/tastejs/todomvc/blob/master/contributing.md#considerations-before-submitting-a-new-app
https://addyosmani.com/blog/front-end-choice-paralysis/
- [x] Update current outdated examples
- [ ] Make all examples PWAs . I think this is the standard now specially after almost all major browsers adding support for service workers https://jakearchibald.github.io/isserviceworkerready/
- [ ] Add units tests for each example. what was preventing this task was the number of examples maintained in TodoMVC but if we decided we are going to support just the production ready , actively maintained one this task will be a lot easier. I think this is important as a lot of people myself included use TodoMVC to try out a new framework and having unit tests already implemented in a right way will encourage new developers to use and implement unit tests.
- [x] Drop IE9 from supported browser https://github.com/tastejs/todomvc/blob/master/contributing.md#browser-compatibility
https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

### Site : 
- [ ] Create a guide that aims to explain in simple english the steps to rebuild a certain example and why certain design choices have been made + articles that should help developers write better code and make more performant apps
- [ ] Replace gulp with webpack

### Contribution:
- [x] Fix Travis build and complete cypress tests : Lately we moved from using selenium to cypress but more tests need to be added and current failing tests need to be fixed  #1866 . This task depends on the other tasks above as if we already have a clear list of frameworks that we are going to support and others that we are going to let go it would save a lot of time and save us from fixing examples that are going to be removed.
- [ ] Integrate page speed and lighthouse with our CI system to check the page speed and lighthouse score for each PR #1692
- [x] Close redundant Issues and PRs
- [ ] Create a Github template for new issues and PRs
- [ ] Fix linter and style checker and add them to the CI system

**These are just my suggestions, can't wait to know what you think 🎉🎉** 

![TasteJS Logo](http://tastejs.com/logo.png)

**Comment by FadySamirSadek** [comment]
@addyosmani @samccone @sindresorhus

**Comment by kt3k** [comment]
I think the linter and style checker are outdated and should be replaced as well. [The rule page](https://github.com/tastejs/todomvc/blob/master/codestyle.md) says it should pass the JSHint and JSCS checks, but most people seem using eslint, prettier, or eslint wrapper tools (like standard or xo) for linting / styling nowadays.

The problem of JSHint is that it can't parse some of esnext features. For example, it doesn't parse decorators, so the framework which depends on decorators can't pass the current regulation.

**Comment by FadySamirSadek** [comment]
@kt3k definitely, will add it to the list . What do you think about the current list ,is there anything else missing ?

**Comment by kt3k** [comment]
@FadySamirSadek Thanks for taking my item! The list seems quite big improvement to my eyes. I don't have anything to add for now.

**Comment by FadySamirSadek** [comment]
@jdebettencourt After we have enough discussion and agree on the guidelines we are going to use to select frameworks I will create a separate issue for each item so if you have the time pick one up. We appreciate all the help we can get.

**Comment by addyosmani** [comment]
First, thanks so much for driving a vision for the next release, @FadySamirSadek! 

 > Create a clear guideline to help us decide what makes a framework mature, production ready and fit to be added to TodoMVC.

I strongly agree having better guidelines for inclusion would help. In the past, determining when a library or framework had enough "traction" to be considered worth including was difficult. There are only a few public signals you can really use (stars are proxy for developers being interested in a library, but not use), some frameworks have most of their usage behind firewalls and download counts are similarly "okay" but not perfect signals to use. 

One could ask "well, why do you need criteria for what to include at all?" and the answer is that while the project was created to help developers get their foot in the door learning a framework/library, it's also a way for them to discover what their options are. Each addition we make increases the pool of choices they might have to sift through so being mindful of that is something we've tried to do. 

I'm sure all of this could be done much much better.

> Remove frameworks that are no longer maintained or have a clear better alternative as TodoMVC is a curation not a collection of frameworks and its main goal is to help developers pick a framework to learn or use for their next project

In the same vein as the above, strongly agree. 

> Add units tests for each example. what was preventing this task was the number of examples maintained in TodoMVC but if we decided we are going to support just the production ready , actively maintained one this task will be a lot easier.

If we think we're going to have enough contributors to help 1) author the tests and 2) maintain them, I would say go for this. It's definitely a nice to have. In our experience, it's proven difficult enough to get framework communities to update/help us update the upstream implementations that adding unit tests as a requirement could be viewed by some as another hurdle to cross. I'm supportive of adding tests as a requirement, but just be aware this can pose some trickiness further down the line.

> Drop IE9 from supported browser

👍 

> Fix Travis build and complete cypress tests : Lately we moved from using selenium to cypress but more tests need to be added and current failing tests need to be fixed

I would consider fixing the build and Cypress tests pretty key. Historically, broken or flaky builds were one of the biggest issues we found caused delays landing implementations. We were lucky enough to have an (almost) dedicated owner for our testing infra. Finding someone that's comfortable owning or helping with that side of things would help a lot.

> Integrate page speed and lighthouse with our CI system to check the page speed and lighthouse score for each PR

I'd file this one under "nice to have"/P2. It's a few hours work to get Lighthouse integrated into your CI builds now (if that) with solutions like https://github.com/ebidel/lighthouse-ci. For TodoMVC, I could see this being helpful for ensuring accessibility and basic best practices are followed. I might not put too much weight into caring about the overall Lighthouse score for implementations (as the focus is education/clean and readable code over all else). Projects like HNPWA.com try to be more performance centric, but it'll ultimately be up to the new maintainers to decide what we'd like to do here.

Excited to see where all of this work goes! 🎉

**Comment by addyosmani** [comment]
> Update current outdated examples

This is probably one of our P0s for the project. 

@mathiasbynens and I work on a browser benchmark called [Speedometer](https://webkit.org/blog/8063/speedometer-2-0-a-benchmark-for-modern-web-app-responsiveness/) where we maintained several up-to-date (well...8 months ago) implementations of the TodoMVC apps as part of the benchmark - with one main difference - all storage calls are disabled or shimmed to store items in memory instead. 

If someone wanted to, they could take the implementations we have over in https://github.com/WebKit/webkit/tree/master/PerformanceTests/Speedometer/resources/todomvc if they're more recent than what we have upstream and migrate them over. It's also perfectly fine if it would be cleaner to just rewrite/update the implementations we have here without using anything from Speedometer's source.

As an aside, we should probably also update the README to reflect you're effectively the new lead maintainer @FadySamirSadek. If you'd like to put together a PR for it, happy to wordsmith with you. I've been receiving a few requests to add more folks with contributor privileges to the repo and honestly, I'd rather just defer to your best judgement :)

**Comment by FadySamirSadek** [comment]
@addyosmani can not agree more, will create separate issue for each task for tracking and tag them with the appropriate priority and difficulty level to encourage new contributors as a lot of the tasks are Good First Contributors friendly and I could use all the help I can get.  Regarding the addition of more contributors this will help a lot specially in maintaining and updating the examples, will be actively looking  for new contributors in the upcoming PRs and hopefully add more contributors.

**Comment by F1LT3R** [comment]
I think "Drop IE9" and "Testing" would be really great.

Can I ask whether TODO MVC will ever cover a more fully featured app? I feel that it is too simple for today's needs. While the TODO MVC is perfect for demonstrating the view and model interaction, I think that developers today to grok a lot more details to make a good choice.

For example: Frameworks do not always ship with a router, or an http request framework, or any concept of a service model (think Angular service or React Context API/HOC), etc. But all of these considerations are important/crucial to choosing the right framework.

I would love to see the following become part of TODO MVC:

- [ ] Routing
- [ ] HTTP Requests
- [ ] State & Service
    * [ ] Common data model between views (think Angular service)
    * [ ] Time travel
- [ ] Login & Auth
- [ ] Server side rendering
- [ ] Build/Bundling

Perhaps it is possible to build out TODO MVC into something where you can select your core MV framework, and then select the other components: 

- Router 
	- [ ] Internal/Supported (React Router/Vue Router/Etc)
	- [ ] Abstract-State-Router 
	- [ ] Sawblade
	- [ ] Custom (repo link)
- HTTP Requests
	- [ ] Internal/Supported (Angular HTTP/etc)
	- [ ] Axios
	- [ ] Fetch
	- [ ] Custom (repo link)
- [ ] Etc (you get the point)

Then you could demo the app with the selected services selected, and you could check out something that would bundle/build locally and get started with almost everything you need to begin fleshing out the app.

IMO, this would lead to some nice common architectural patterns that could be re-used across projects. The framework developers would also have a place to demonstrate their suggested setups even if they don't ship with a router, request framework, etc.

For example: having a place to go and hot-switch the router you were using (without having to re-architect the app), would be hugely helpful. And the TODO MVC would then also demonstrate good patterns for building apps that are not locked into a particular solution, increasing reuse, showing good separation of concerns, etc.

What do you think?

Apologies if this is the wrong place to have this discussion.

**Comment by sindresorhus** [comment]
@FadySamirSadek This all sounds good! 👌✨

---

> Drop IE9 from supported browser

I would argue we should only target the latest version of browsers. There's no reason for us to get bogged down in browser support. That's not the point of TodoMVC.

**Comment by sindresorhus** [comment]
@F1LT3R https://github.com/tastejs/hacker-news-pwas solves many of your concerns. Although creating a full PWA is much more ambitious than a TODO app. I think both projects serve a useful purpose.

**Comment by whitefire0** [comment]
As there are currently over 50 frameworks in demonstration within the project, I have started to have a think about the other means by which frameworks can be selected. As already mentioned on this page, and some others, I think these might be the most important criteria:

1) Current adoption/popularity. @addyosmani mentioned the issues with firewalls - there may be no reliable ways to assess the degree to which frameworks are actually being used. I have considered the utility of surveying the frequency of medium articles/blogs on the frameworks we have, in combination with metrics on stackoverflow and github stars - this could provide insight into the current interest in frameworks. As mentioned, the purpose of todoMVC is to be a facilitator of learning; blogs, articles, forums and stackoverflow drive a lot of the 'buzz' around both new and old technologies, and in doing so encourage significant numbers of people to go and learn those frameworks. It may even be possible to get some of the big player websites to advertise a survey/questionnaire on our behalf, or showcase the link to a bespoke website created for that purpose.

2) It may be worth grouping frameworks by their distinguishing features (e.g. one or two way data binding, templating/JSX etc). Having many variations of similar technologies may be a little redundant, if the primary purpose is to help teach unfamiliar design patterns and ways of working. This might be particularly the case for frameworks that are only sporadically in use. Maintaining the versions and tests of codebases not in use is inefficient given that there is not that much manpower to spread around.

3) Aggregating statistics on the number of issues/PRs per framework may also give some inclination as to priority.

I would be happy to look into the surveying/research elements further, or begin the production of a survey website if folks think it might be worth the investment. It wouldn't need to be fancy at all - a simple front end, user authentication and data persistence. My company can provide free and reliable hosting for such a project, and it could be coded up in no short shrift if we join forces a little bit. My most recent work has been with Ruby on Rails and its great for putting applications together quickly.

Any thoughts folks?

**Comment by whitefire0** [comment]
Another thought, is there any merit in asking submissions to provide a working example of the applications whilst the test suites are not running? Mainly just to save us time in checking functionality.
