### ISSUE TITLE
 Create a clear guideline to help us decide what makes a framework mature, production ready and fit to be added to TodoMVC

### ISSUE THREAD

**Issue by FadySamirSadek** [tastejs/todomvc#1886]
Resources : 
-https://addyosmani.com/blog/front-end-choice-paralysis/
-https://github.com/tastejs/todomvc/blob/master/contributing.md#considerations-before-submitting-a-new-app

**Comment by Ahmed-90** [comment]
Can we say a framework should: (as a very basic example)

- Be at least 1 year old. (git commits?)
- Have at least 1k stars. (proof of public interest)
- Be compatible with modern standards and techniques like bundlers, code splitting, and offline first approaches like PWAs, services workers etc...
- Backward compatible for 2 older versions of at least 2 major browsers. (overkill?) 
- Should be unique/different and not just an enhanced/features rich fork of an existing framework.
      * If this line is a valid guideline what about things like nuxt/vue, next/react? 

---

Am I on the right track here?  
Should we mention licensing, opensource, etc...?

**Comment by FadySamirSadek** [comment]
@Ahmed-90 this is very similar to what I had in mind. 

> Be at least 1 year old

Completely agree

> Have at least 1k stars. (proof of public interest)

Also agree but I think we should make it 5k instead of 1k almost all the widely used projects are way passed this number React now has 104K and vue has 105K any framework that has been around for a while is going to have more than 5k stars if it is widely adopted which is exactly what we need.

> Be compatible with modern standards and techniques like bundlers, code splitting, and offline first approaches like PWAs, services workers etc...

Also agree but we should make a comprehensive list as the goal of these guidelines is to not think when adding a new framework and make it as close to a yes-no question as possible either the framework checks all the points or not.

> Backward compatible for 2 older versions of at least 2 major browsers

Not sure about backward compatibility but should definitely support recent versions of all major browsers.

>Should be unique/different and not just an enhanced/features rich fork of an existing framework.

I think its okay to have multiple examples and multiple implementations for the same framework as long as the framework is widely used and these implementations are considerable options for people starting new projects then we should have them.

Regarding licensing I think the framework must have a version that is free and open source no matter what the license is.

WDYT?

**Comment by Ahmed-90** [comment]
> Also agree but I think we should make it 5k instead of 1k

Initially, I actually thought about a high number, but I had the notion of "what about the shiny new projects", but yeah you're right ~~hype~~ stars are easy to generate, 5k seems reasonable.

> should make a comprehensive list as the goal of these guidelines is to not think when adding a new framework and make it as close to a yes-no question

Ofc, what about we start by borrowing some guidelines from lighthouse checklist? should we come up with a minimum lighthouse score for submissions?

> Not sure about backward compatibility but should definitely support recent versions of all major browsers.

Are we talking polyfills here? what about scenarios like native web components?

> I think its okay to have multiple examples and multiple implementations for the same framework *as long as the framework is widely used and these implementations are considerable options for people starting new projects* then we should have them.

I'm having difficulties of how to put that in a yes/no statement, that is clear for everyone? 

> Regarding licensing I think the framework must have a version that is free and open source no matter what the license is.

Totally

---

another possible rule

- Should be deployable on a simple "......."? (GitHub pages or free Heroku or now.sh instance for projects with SSR/backends) 

Thoughts?

**Comment by Ahmed-90** [comment]
@FadySamirSadek for clarity sake, these guidelines are only for the framework evaluation or does it include the submitted code too?

I've been reading through lighthouse checklist and most applicable rules need a code sample to be accurate, like the bundle/js files size rule, TTI, or js bootup time etc...

IMHO, it would be more convenient to make it a mix of [Considerations before submitting](https://github.com/tastejs/todomvc/blob/master/contributing.md#considerations-before-submitting-a-new-app)
and [App spec ](https://github.com/tastejs/todomvc/blob/master/app-spec.md) ?

Thoughts?

**Comment by Fruitseller** [comment]
I have my difficulties with creating a clear guideline. I have no idea how such a document would look like that can give a clear yes or no answer.

So I thought maybe we can learn by trying it out? If I understand correctly most projects are outdated so we could open issues for each existing framework and evaluate if it can be dropped or not(and hopefully updated).

So I hope after some finished evaluations some patterns would show that can be used in this guideline.

**Comment by Ahmed-90** [comment]
As a starting point a minimal guidelines list would be:

- At least 1 year old.
- Main repo/core should have a minimum of 5k stars.
- Has a free and opensource version.
- Supported in the latest version of all major. 
- Deployable on Github pages or a basic free instance of now.sh, or Heroku.


Maybe we can use this and evolve from there

**Comment by FadySamirSadek** [comment]
@Ahmed-90 This issue is for creating guidelines for submitting a new example for a new framework but you are welcome to open a new issue to discuss creating a guide for submitted code.
`So I thought maybe we can learn by trying it out?
` 
With the addition of new examples and new frameworks the complexity of maintaining this project increases dramatically so after creating the guidelines we will walk through all the examples we have and see which ones comply with the new guidelines and which ones do not.
 But we can not create this guideline based on our belief that some frameworks should exist and others do not we should make these guidelines eliminate the need to think about if a framework is a good fit or not. Not the other way around.
Thanks a lot for your contribution will try to create an initial PR with your notes and other contributors so we can start from there  🙂

**Comment by FadySamirSadek** [comment]
@Ahmed-90 @Fruitseller @whitefire0 please review the PR #1910 and tell me WDYT?

**Comment by FadySamirSadek** [comment]
closed as per #1910
