### ISSUE TITLE
React Hooks Example

### ISSUE THREAD

**Issue by jacob-ebey** [tastejs/todomvc#1955]
I haven't seen anything out there demonstrating react hooks in a todo app, so I borrowed your npm css package and whipped one up: https://github.com/jacob-ebey/hooks-todo

Would you like this added to this repo?

**Comment by FadySamirSadek** [comment]
@jacob-ebey Definitely, Please open a PR and tell me if I can help with anything

**Comment by jacob-ebey** [comment]
PR's out if you wanted to merge it at some point.

**Comment by flashdesignory** [comment]
Closing this since the newly merged React example is using hooks: https://github.com/tastejs/todomvc/pull/2202
