### ISSUE TITLE
The React example is outdated

### ISSUE THREAD

**Issue by J-F-Liu** [tastejs/todomvc#1959]
You can find an updated example at here:
https://github.com/J-F-Liu/TodoList/tree/632f2edabf7c0be530287c880dbebca41fc8e722

**Comment by FadySamirSadek** [comment]
PR is welcomed

**Comment by wschwab** [comment]
@J-F-Liu Are you still working on this?

**Comment by wschwab** [comment]
I'm interested in taking this on -  does anyone have any objections? I have a few questions, too.

**Comment by J-F-Liu** [comment]
@wschwab  Received no feed back of my PR.

**Comment by FadySamirSadek** [comment]
@J-F-Liu Sorry for that and I'll be reviewing it soon

**Comment by flashdesignory** [comment]
Marking this as completed, see https://github.com/tastejs/todomvc/pull/2202 and https://github.com/tastejs/todomvc/issues/2199
