### ISSUE TITLE
Domain name has expired, the website is down

### ISSUE THREAD

**Issue by nmoreaud** [tastejs/todomvc#1964]
We can't browse the website http://todomvc.com anymore, it is down

NOTICE: This domain name expired on 2/23/2019 and is pending renewal or deletion.
Welcome to todomvc.com
This Web page is parked for FREE, courtesy of GoDaddy.com.
Visit GoDaddy.com
Search for domains similar to
todomvc.com
Is this your domain?
Let's turn it into a website!
Would you like to buy this
domain?
$0.99* .COM
THE domain at THE price.

*Restrictions apply. See website for details.
Copyright © 1999-2019 GoDaddy, LLC. All rights reserved. Privacy Policy

**Comment by passy** [comment]
Woops, that's not ideal. @addyosmani? :)

**Comment by FadySamirSadek** [comment]
@nmoreaud @passy  Addy just renewed the domain for 5 years and the site should be back in less than 24 hours

**Comment by nmoreaud** [comment]
The website is available again. Nice ! Thanks

**Comment by FadySamirSadek** [comment]
@nmoreaud Thank you so much for notifying us
