### ISSUE TITLE
Vue.js example duplicates keys

### ISSUE THREAD

**Issue by gzalo** [tastejs/todomvc#1965]
I've found a bug that causes errors similars to "Duplicate keys detected: '2'. This may cause an update error." when atempting to run the code with the latest version of vue.

The issue happens when removing todo items, since the ids of the older items aren't updated, adding a new item might result in duplicated indices.

Steps to reproduce:
-Delete every item
-Add 2 items
-Delete the first item
-Add 1 item

Now both items have the same id property:

![a](https://i.imgur.com/wioq87j.png)

**Comment by DimaMaster149** [comment]
In order to avoid this you should always increase your id.
Looks like now your new id return from an expression similar to todos.length + 1.

**Comment by gitraj666** [comment]
I would like to contribute and fix this issue
