### ISSUE TITLE
Svelte example

### ISSUE THREAD

**Issue by himynameisdave** [tastejs/todomvc#1975]
[Svelte](https://svelte.dev) is starting to take off more and more, and considering it's now very stable and ready for production use (and has a growing a community), I think it would be an ideal candidate to add to TodoMVC (I'm actually a little surprised that it's not already here).

They've just released Svelte 3, and the core concept behind this "framework" is that it isn't really a "framework" at all -- it's a lot closer to a "compile-to-JS" solution than a traditional framework like React.

I've already used it for small personal projects, and I'd love to help contribute a TodoMVC example, just let me know if it is something worth adding here and point me to where to get started. 👍  Thanks

Here is a good overview of [the design goals and motivations behind Svelte](https://svelte.dev/blog/svelte-3-rethinking-reactivity).

**Comment by piotrku** [comment]
Great idea! I was surprised not to find it here too :)

**Comment by diogocorrea** [comment]
They have this example: http://svelte-todomvc.surge.sh/
I think it would be nice to have this in the https://todomvc.com too.

**Comment by justingolden21** [comment]
Surprised in 2021 a framework as popular as svelte isn't here

**Comment by justingolden21** [comment]
+1 to this in 2022. I can make one and add if if the repo owner is interested

**Comment by sebastianrothe** [comment]
See #2101

**Comment by flashdesignory** [comment]
closing as completed by https://github.com/tastejs/todomvc/pull/2194
