### ISSUE TITLE
Use .focus() instead of .select()?

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#203]
I can't remember why we started using .select() in the first place, but @IgorMinar has a point:

> because when I doubleclick on a item I typically want to change only a small part of it. select() highlights the whole text and forces me to deselect it. if I do want to select the whole thing I can just triple click on the item and then I'll get this behavior.

I think we should change it back.

**Comment by arthurvr** [comment]
> Emberjs

Seems to be working correctly for me. Can you confirm that, @sindresorhus?

**Comment by arthurvr** [comment]
Ticked ember, then.

**Comment by arthurvr** [comment]
I never noticed it back then, but since when I ticked the ember app and removed the dropped apps, this can be closed :) Yay!

**Comment by sindresorhus** [comment]
🎉🎉🎉
