### ISSUE TITLE
Add TODOs badge

### ISSUE THREAD

**Issue by patrickdevivo** [tastejs/todomvc#2099]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/tastejs/todomvc)](https://www.tickgit.com/browse?repo=github.com/tastejs/todomvc)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for new contributors to find areas of code to improve.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/tastejs/todomvc)](https://www.tickgit.com/browse?repo=github.com/tastejs/todomvc)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by sindresorhus** [comment]
Thanks for the suggestion but we're going to pass on this.
