### ISSUE TITLE
React Examples are trying to fetch a non existing JS File

### ISSUE THREAD

**Issue by r-sreesaran** [tastejs/todomvc#2132]
Once the React todo mvc App is started, try refresh the page. 
There is request sent to get learn.js. This results in 404. 

- [02/Nov/2020 11:12:11] "GET / HTTP/1.1" 200 -
- [02/Nov/2020 11:12:11] code 404, message File not found
- [02/Nov/2020 11:12:11] "GET /learn.json HTTP/1.1" 404 -
- [02/Nov/2020 11:12:32] "GET / HTTP/1.1" 200 -
- [02/Nov/2020 11:12:32] code 404, message File not found
- [02/Nov/2020 11:12:32] "GET /learn.json HTTP/1.1" 404 -

The following is the trace from console. 

1) Is the wrong request made or is the file missing 

Thanks
R.Sreesaran

**Comment by flashdesignory** [comment]
The updated React version resolves this issue.
