### ISSUE TITLE
React Philosophy link doesn't work

### ISSUE THREAD

**Issue by mariiakornieva** [tastejs/todomvc#2146]
The link to React Philosophy on the page https://todomvc.com/examples/react/#/ no longer works.

<img width="1197" alt="Screenshot 2021-05-31 at 4 08 21 PM" src="https://user-images.githubusercontent.com/18334687/120198222-8b838780-c22a-11eb-9d3a-b6128670e06a.png">

Right now the link goes to https://www.quora.com/profile/Pete-Hunt/Posts/React-Under-the-Hood, which is not found (404 received).

I believe the new link to Pete Hunt's "React: Under the Hood" article is: https://petehuntsposts.quora.com/React-Under-the-Hood.

**Comment by flashdesignory** [comment]
This has been addressed in the new React pr that was merged: https://github.com/tastejs/todomvc/pull/2202
