### ISSUE TITLE
Update the broken link to Philiosophy behind react

### ISSUE THREAD

**Issue by siraj-samsudeen** [tastejs/todomvc#2181]
Source Page: https://todomvc.com/examples/react/#/

Existing link 
[Philosophy](http://www.quora.com/Pete-Hunt/Posts/React-Under-the-Hood)
New Link 
[Philosophy](https://petehuntsposts.quora.com/React-Under-the-Hood)

If there is a way to send a pull request, please let me know and I can create one...

**Comment by VivekBaldha0712** [comment]
@siraj-samsudeen  I would like to take this task. Will you please assign to me

**Comment by flashdesignory** [comment]
This has been addressed in the new react pr that was merged: https://github.com/tastejs/todomvc/pull/2202
