### ISSUE TITLE
Add sidebar to Ember example

### ISSUE THREAD

**Issue by flashdesignory** [tastejs/todomvc#2255]
Some newer examples did have a missing sidebar, which most of them were added back in this pr: https://github.com/tastejs/todomvc/pull/2254

Could we bring back the sidebar for the Ember example as well?

https://todomvc.com/examples/emberjs/todomvc/dist/

@NullVoxPopuli - is this something that you might be interested in adding? 😄

**Comment by flashdesignory** [comment]
An example can be found here: https://todomvc.com/examples/knockoutjs/

It's part of the todomvc.com website and just gets injected in your build. 
It just shows up if you run the todomvc.com website locally, and won't affect the todomvc build. 

couple steps needed:

1. npm install todomvc-common
2. inject the css somewhere: <link rel="stylesheet" href="node_modules/todomvc-common/base.css" />
3. inject the js file somewhere: <script src="node_modules/todomvc-common/base.js"></script>
4. update this file as needed: https://github.com/tastejs/todomvc/blob/master/learn.json

To preview, you'd need to run the todomvc website from the root. 

That's pretty much it. Happy to help / review prs. 
This would be super helpful 😄

**Comment by SparshMadaan** [comment]
Hi flashdesignory,this issue is still open . I'm happy to contibute if this still open .

**Comment by flashdesignory** [comment]
I'll refer to @NullVoxPopuli, if offloading is desired 😄

**Comment by NullVoxPopuli** [comment]
oh sorry, yes I keep forgetting about this work -- @SparshMadaan if you want to PR -- I'm more than happy to review!

**Comment by SparshMadaan** [comment]
@NullVoxPopuli I'm beginner in open source and I do some little development project can you please let me know how to run this code in my local machine beacause npm start beacuse I made the changes but not able to see .

**Comment by NullVoxPopuli** [comment]
Do you have errors anywhere?

**Comment by SparshMadaan** [comment]
@NullVoxPopuli Thanks Buddy !
