### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#254]
As discussed in #200 and #134 we are going to require framework submissions to come with unit tests. We'll provide a Mocha testsuite by default, but each framework is free to choose another if that's their best practice.

We already have a good start with the [Mocha tests](https://github.com/addyosmani/todomvc/tree/ea6780dfccf1865c3029ed1f31e4f77fd25637a2/dependency-examples/emberjs_require/js/app/specs) @stas created for us in the Ember+RequireJS app.

Todo:
- Review the above unit tests and check if something is missing
- Make it more generalized and boilerplaty
- Needs documentation on how to implement it in new frameworks
- Figure out which frameworks that should use this boilerplate and which should use something different

**Comment by FadySamirSadek** [comment]
Closed as out of datee
