### ISSUE TITLE
Clarify the contributing guidelines for different languages

### ISSUE THREAD

**Issue by berdario** [tastejs/todomvc#347]
Preamble: _I somewhat recently started to learn Clojure, I stumbled upon Todomvc and I realized there was no ClojurescriptOne example_

_I said to myself: "this might be the occasion to get first hand experience with that framework!"_

I read the contributing guidelines, and the app specification, and then... I realized that buried in the wiki there's indeed an already working CJOne example

I looked at the related pull request https://github.com/addyosmani/todomvc/pull/232

(there' also https://github.com/addyosmani/todomvc/issues/207 )
and in both cases, the request is denied on the basis that "it's not  Javascript"

but then, the GWT and Dart apps have been happily accepted

@sindresorhus says that you _stretch the "JS requirement in some cases"_, and 

> TodoMVC is about giving a taste of various JavaScript MV frameworks, something this isn't.

I looked at the GWT https://github.com/addyosmani/todomvc/pull/103 and Dart https://github.com/addyosmani/todomvc/pull/295 pull request:
for GWT, the issue of "not being javascript" wasn't raised at all... for Dart @addyosmani went as far as asking on the Dart mailing list for someone to implement it

it's your project, so it's fine if you have some other criteria on which you discriminate... like "notability" or "relevance for our target community", but I'd prefer that you would clearly and explicitly state them in the guidelines

Thanks :)

**Comment by nithindavid** [comment]
Hi @berdario ,
Can you close this issue if you think it's fixed ? 

Thanks 🐱
