### ISSUE TITLE
switch from HTML id attributes to class attributes

### ISSUE THREAD

**Issue by petermichaux** [tastejs/todomvc#348]
HTML id attributes are used for finding items in TodoMVC. This means that two to-do interfaces cannot appear in a single page. I think a test of a well written widget is that the UI can be duplicated in a page with both UIs observing the same model and seeing the UIs stay in sync. This is not possible when using id attributes. I've run into this as a real requirement and it taught me that using class attributes is sufficient and better.

Can TodoMVC switch from using id attributes to class attributes?

**Comment by arthurvr** [comment]
This issue has been open for long, let's start doing stuff :) I can start working on some of this.
 
>  Create a base2.css based on the original with just classes. Also try to fix any other idiosyncrasies with the template while we're at it.

I think it would be fine to just have both classes and ids in `todomvc-app-css/index.css`? I mean, I don't think we really need a second file for this. Once we have all examples on classes, we can totally remove the ids.

**Comment by sindresorhus** [comment]
@arthurvr My plan is to simply use semver. https://github.com/tastejs/todomvc-app-css is currently using ID's, but a 2.0 version of it could use classes. That way it would still work for older apps, but have a sane base for new apps. This was mostly blocked on my never finished redesign, which is now done. So I think we can get this started. Can you move this issue over to https://github.com/tastejs/todomvc-app-css ?
