### ISSUE TITLE
TypeScript app

### ISSUE THREAD

**Issue by addyosmani** [tastejs/todomvc#359]
@sindresorhus I've just pushed into https://github.com/addyosmani/todomvc/tree/typescript my first take on refactoring the Microsoft TypeScript (and Backbone) app to fit our template. Here's how it used to look:

![](http://cl.ly/image/2T1L0H3k291C/Screen%20Shot%202012-12-24%20at%2014.13.24.png)

and here's how it looks now:

![](http://cl.ly/image/3t11260j2g27/Screen%20Shot%202012-12-24%20at%2014.11.55.png)

I have to admit, there is still a lot of work to be done to clean up the old format markup to fit the specs and of course add routing but I think it's enough for us to consider adding to Labs for 1.0.

What do you think?

**Comment by arthurvr** [comment]
>  Use the correct variables completed, title, active, etc. (currently, done, contents, remaining)

Isn't `remaining` correct? https://github.com/tastejs/todomvc/search?p=2&q=remaining&utf8=%E2%9C%93

**Comment by sindresorhus** [comment]
@arthurvr I guess we haven't enforced it well enough, but [some apps do use `completedCount`](https://github.com/tastejs/todomvc/search?utf8=%E2%9C%93&q=completed&type=Code), and it's more consistent with the other use of the `completed` word, but it's such a nitpick I'm happy to overlook it.

**Comment by addyosmani** [comment]
Is it worth adding in a note somewhere about our flexibility on `completedCount`, or does it make sense to just consider how this is used compared to `completed` on a case by case basis?

**Comment by arthurvr** [comment]
> Is it worth adding in a note somewhere about our flexibility on completedCount, or does it make sense to just consider how this is used compared to completed on a case by case basis?

I don't really think that's needed, tbh.
