### ISSUE TITLE
Unminified vendor libs?

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#378]
Our current policy is to have vendor libs minified for performance and size reasons:

> Use minified version of third-party code and put it in the lib folder.

Today, most projects have a build system that concats and minifies the code anyway, and having unminified code, even for vendors libs, helps a lot when debugging.

I would like to change our policy to require everything to be unminified, rather than minified.

@addyosmani  What do you think?

**Comment by arthurvr** [comment]
I can't find any more examples still using minified versions, yay! Gonna do quick of a PR for the readme :)

**Comment by samccone** [comment]
I think this should be able to be closed right @arthurvr
