### ISSUE TITLE
Spine app - improve 'add todo' and routing logic

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#384]
Could be improved as described in #372:

> When a new todo is created the `create` and `change` events are dispatched. This executes `addNew` and because of a [possible bug](https://github.com/addyosmani/todomvc/blob/gh-pages/architecture-examples/spine/src/app.coffee#L30) I had to set `addAll` to [execute on `change`](https://github.com/addyosmani/todomvc/commit/c1cfbfa8cbc3b6b658985b458ff7327076d30d8d#L3R22). This is stupid, since addAll will overwrite everything addNew did, but that's the best solution I found at that time to support routing, since addAll is filtered.

**Comment by dmethvin** [comment]
I couldn't decypher the discussion here, but does it still apply for the current spine app? I fixed #795 a few days ago. Is this ticket about correctness, or just efficiency? If it's the latter then maybe a note could be added to https://github.com/spine/spine/issues/530 and this could be closed.

**Comment by FadySamirSadek** [comment]
Closed as out of date
