### ISSUE TITLE
Require readme

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#386]
I want us to require every app to come with a readme. This should also be created for existing implementations.

Todo
- [x] Create a readme for one of the popular frameworks we can use as an example and refer to in the app spec.
- [x] Update the app spec
- [x] Ping authors of existing implementations to submit a readme

The readme should contain:
- Title
- Short about the framework
- Short about the app
- How it was built.
- Resources: Some links to places you can read up on the framework and stuff.
- Credit

Anything more? Thoughts?

// @trek

**Comment by arthurvr** [comment]
If I find 10 minutes I will go through all the examples and check which ones need to be updated. I will ping the authors here.

**Comment by arthurvr** [comment]
Examples that still don't have a readme:

* `sapui5` (cc @schubertha)
* `lavaca_require` (cc @mutualmobile)

**Comment by arthurvr** [comment]
> `lavaca_require` (cc @mutualmobile)

@jeffla @kcharwood @larsacus @mristroph would anyone of you be interested in taking this one?

**Comment by larsacus** [comment]
![http://i.imgur.com/hnwy4hR.gif](http://i.imgur.com/hnwy4hR.gif)

I'm not sure what the context is here, but since this looks like web/lavaca stuff, I think @alexwasner should be able to get the right person to look at this.
