### ISSUE TITLE
Derby - 502 Bad Gateway

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#546]
http://todomvc.derbyjs.com/

Looks like it's down...

@absoludity

**Comment by samccone** [comment]
looks like it is up now @sindresorhus :)

**Comment by sindresorhus** [comment]
@samccone No, it just redirects to the website. It should go to the todo app.

**Comment by samccone** [comment]
oh crazy ok :) TIL

**Comment by arthurvr** [comment]
ping @nateps @bnoguchi - you guys have any idea? Please note that the derby example is removed from the site these days.


> If it's possible for the TodoMVC team to get access we would be happy to restart as needed, otherwise help from members of the current Derby team would be hugely appreciated.

That would actually be really handy. I mean, it's down since 2 years guys.

**Comment by arthurvr** [comment]
This has been broken for so long (together with the example being really outdated and unmaintained), time to (temporarily) drop this app?

**Comment by sindresorhus** [comment]
:+1: The maintainers of Derby doesn't seem to care.

// @ishbu

**Comment by arthurvr** [comment]
@sindresorhus Yeah, and besides from that: https://github.com/tastejs/todomvc/issues/593#issuecomment-134602313. @tastejs/owners Everybody alright with dropping?

**Comment by samccone** [comment]
👍 to drop ⚡️

**Comment by arthurvr** [comment]
Done :ballot_box_with_check:

**Comment by bnoguchi** [comment]
@arthurvr This seems reasonable to drop. I'm no longer working on Derby, but it continues to actively be developed and used in production.

**Comment by samccone** [comment]
@bnoguchi know anyone that would be interested in maintaining the todo example?
