### ISSUE TITLE
Update Derby app to 0.5.9

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#593]
http://blog.derbyjs.com/2013/06/04/derby-v0-dot-5-0/

**Comment by arthurvr** [comment]
>  Will submit a PR

@nateps Ping? You're still interested in taking this?

**Comment by arthurvr** [comment]
@nateps @absoludity Anyone willing to fix this?

Although, honestly, I think this is one of the examples that deserves (temporarily) being dropped. We haven't had an active maintainer in years, it's getting outdated, [and the app is down for over 2 years](https://github.com/tastejs/todomvc/issues/546). We already [removed](https://github.com/tastejs/todomvc/commit/7f59ef71a0b55fe70cc8a8c95a3d374a1894deca) it from the site a while ago. If somebody comes in to fix all these things we can always just add it back.

**Comment by absoludity** [comment]
Totally fine to close from my pov. I've not worked on (or used) derby for a couple of years, and I'm not in a position time-wise to be able to maintain the demo. Someone from the derbyjs community can resurrect it when that someone exists :) Thanks @arthurvr
