### ISSUE TITLE
Who uses TodoMVC?

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#594]
Inspired by grunt: https://github.com/gruntjs/gruntjs.com/issues/9

Would be nice to have a list of uses of the todomvc apps on the website. Frameworks, users, projects, etc.

Add your thing.

**Comment by xfq** [comment]
* Flux: https://facebook.github.io/flux/docs/todo-list.html
* Vue.js: http://vuejs.org/examples/todomvc.html

**Comment by addyosmani** [comment]
@arthurvr or @samccone want to look at adding these in a PR to the homepage footer as a forcing function for us getting a clean list together? @sindresorhus any opposition?

**Comment by samccone** [comment]
yeah seems like a reasonable thing, I am a bit confused on what "who uses todomvc" really means thought.

what do you guys think it means?

**Comment by arthurvr** [comment]
I think we should have these on the homepage, good idea Addy. Will see if I have some time to work on it. Do we want all of them on the home page, or a list of interesting ones? I would opt to do the latter.

**Comment by addyosmani** [comment]
I think we should just include a list of focused interesting ones. I consider things like WebKit/Apple using us in Speedometer to be worthy of inclusion. I know a bunch of folks, like Ember, use us in their official tutorials. Google uses TodoMVC all over the place (18 different projects last I checked, but we use it for codelabs and tutorials too). That said, I'm happy for someone more impartial to help decide what "interesting" could mean :)
