### ISSUE TITLE
Realtime: Addition of Sails.JS as a Realtime MVC framework.

### ISSUE THREAD

**Issue by dcbartlett** [tastejs/todomvc#598]
I'd like to propose the [Sails.JS](http://www.sailsjs.org) be added to todoMVC as a Realtime MVC framework.  Sails.JS is a newer Node.JS Framework built on proven code like express and socket.IO.   While still being new, Sails.JS packs quite a punch out of the box.  Sails.JS supports websockets via Socket.IO and has a RESTful JSON api that uses the same codebase out of the box.  Blueprints are another feature that makes Sails.JS one of the fastest frameworks to get started with.  With blueprints, all you need is a model, the framework will handle the controller, sockets, and api for you.  This isn't to say that you CAN"T write your own controllers and such, it just makes it easier and faster for you to get a simple API up and running.

When coupled together with front-end frameworks that take advantage of the websockets, Sails.JS can help you build a stunning fast front-end that use a back-end just as fast.

Lets discuss this and see what we think?

**Comment by Pierstoval** [comment]
Three years later, Sails have evolved to be a big and cool framework. Is there anyone wanting to do something with Sails for TodoMVC?
