### ISSUE TITLE
Benchmark suite for all TodoMVC implementations

### ISSUE THREAD

**Issue by petehunt** [tastejs/todomvc#703]
Hey all - are you interested in a standardized way to do benchmarks?

I understand that there are potentially some negative community implications (optimizing the code for perf rather than readability/real world usage) but there's already some perf-specific projects within TodoMVC and part of WebKit's performance suite includes TodoMVC.

If this is something that hasn't been discussed and you're interested in, my advice would be to just officially adopt WebKit's perf suite and provide a standard way to hook into it.

**Comment by MatheusRV** [comment]
Hey whats up? I want to help create something related if this
