### ISSUE TITLE
1.3 release

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#735]
Team

- [ ] Review which apps should be moved out of labs
- [ ] Let's also check if we want to keep all of the current examples.
- [ ] Get open PRs merged/closed
- [ ] Changelog
- [ ] QA check
- [ ] Draft blogpost

We should try to do this before Christmas.

**Comment by arthurvr** [comment]
>  Review which apps should be moved out of labs
 Let's also check if we want to keep all of the current examples.

We now have a separated issue about that. https://github.com/tastejs/todomvc/issues/845

> Changelog
 QA check
 Draft blogpost


Closing this issue as 1.3 released.
