### ISSUE TITLE
Editing is not cancelled on ESCAPE keypress

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#789]
The specification states that edits should be cancelled on escape:

> If escape is pressed during the edit, the edit state should be left and any changes be discarded.

The current implementations do not meet this requirement:
- [x] agilityjs
- [x] angularjs-perf
- [x] thorax_lumbar
- [x] flight
- [x] backbone_require
- [x] knockoutjs_require
- [x] closure
- [x] jquery
- [x] knockback
- [x] spine
- [x] ariatemplates
- [x] batman
- [x] ~~dermis~~
- [ ] dijon
- [ ] duel
- [ ] extjs_deftjs
- [x] kendo
- [x] olives
- [x] plastronjs
- [x] rappidjs
- [ ] serenadejs
- [x] somajs
- [x] thorax
- [x] typescript-angular
- [x] angularjs_require
- [x] backbone_marionette_require

**Comment by arthurvr** [comment]
I opened #1223.

**Comment by arthurvr** [comment]
pinging @podefr for the olives app. You interested in taking this one?

**Comment by podefr** [comment]
@arthurvr of course, will do, just need to other code review to go in first to build on solid grounds :)

**Comment by podefr** [comment]
@arthurvr I just created a PR to fix this issue #1287

**Comment by dprotti** [comment]
Closure impl seems to be working fine http://todomvc.com/examples/closure/#/

**Comment by arthurvr** [comment]
@dprotti Yep. Tests pass as well. Thanks for letting us know. I guess it was fixed but we just never ticked it on the list. Done now.

**Comment by arthurvr** [comment]
Pinging in the app authors and frequent contributors to see if we can push this issue forward. @eastridge @mkuklis @margaritis @loicknuchel @creynders @mckamey @brian428 @jnicklas Can y'all take a look?

**Comment by mckamey** [comment]
Sending a PR shortly.
