### ISSUE TITLE
Stapes app is completed broken!

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#808]
The current stapes app is completely broken. Fails every test!

- [ ] stapes
- [ ] stapes_require

Is there someone we could reach out to in order to get this fixed?

    (1275 of 1809) new issue: TodoMVC - stapes, Mark all as completed, should allow me to mark all items as completed
    (1276 of 1809) new issue: TodoMVC - stapes, Mark all as completed, should allow me to clear the completion state of all items
    (1277 of 1809) new issue: TodoMVC - stapes, Mark all as completed, complete all checkbox should update state when items are completed / cleared
    (1278 of 1809) new issue: TodoMVC - stapes, Item, should allow me to mark items as complete
    (1279 of 1809) new issue: TodoMVC - stapes, Item, should allow me to un-mark items as complete
    (1280 of 1809) new issue: TodoMVC - stapes, Item, should allow me to edit an item
    (1282 of 1809) new issue: TodoMVC - stapes, Editing, should hide other controls when editing
    (1283 of 1809) new issue: TodoMVC - stapes, Editing, should save edits on enter
    (1284 of 1809) new issue: TodoMVC - stapes, Editing, should save edits on blur
    (1285 of 1809) new issue: TodoMVC - stapes, Editing, should trim entered text
    (1286 of 1809) new issue: TodoMVC - stapes, Editing, should remove the item if an empty text string was entered
    (1287 of 1809) new issue: TodoMVC - stapes, Editing, should cancel edits on escape
    (1288 of 1809) new issue: TodoMVC - stapes, Counter, should display the current number of todo items
    (1289 of 1809) new issue: TodoMVC - stapes, Clear completed button, should display the number of completed items
    (1290 of 1809) new issue: TodoMVC - stapes, Clear completed button, should remove completed items when clicked
    (1291 of 1809) new issue: TodoMVC - stapes, Clear completed button, should be hidden when there are no items that are completed
    (1292 of 1809) new issue: TodoMVC - stapes, Persistence, should persist its data
    (1293 of 1809) new issue: TodoMVC - stapes, Routing, should allow me to display active items
    (1294 of 1809) new issue: TodoMVC - stapes, Routing, should allow me to display completed items
    (1295 of 1809) new issue: TodoMVC - stapes, Routing, should allow me to display all items

**Comment by arthurvr** [comment]
@hay Any status update?

**Comment by hay** [comment]
Nope, if you want you can remove it, and when i'll have the time i'll do a PR for a new version.
