### ISSUE TITLE
dojo does not hide the other todo elements when editing

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#815]
If you edit an item, notice that the competed checkbox is still visible.

test failure:

    TodoMVC - dojo, Editing, should hide other controls when editing

**Comment by arthurvr** [comment]
That tests seems to be passing for me at the moment. Can anyone confirm that? Manually it seems to work fine as well.

**Comment by arthurvr** [comment]
Yeah, it works fine now.
