### ISSUE TITLE
AngularJS Require - complete all checkbox has numerous issues

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#826]
test failures:

    TodoMVC - angularjs_require, Mark all as completed, should allow me to mark all items as completed
    TodoMVC - angularjs_require, Mark all as completed, should allow me to clear the completion state of all items
    TodoMVC - angularjs_require, Mark all as completed, complete all checkbox should update state when items are completed / cleared

**Comment by arthurvr** [comment]
All passing for me. Can one confirm?

**Comment by samccone** [comment]
I am seeing a new failure but unrelated
```
  1) TodoMVC - angularjs_require No Todos should hide #main and #footer:
     AssertionError: 0 items expected in the todo list, 1 items observed
```
