### ISSUE TITLE
Routing should default to 'all'

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#828]
When a todo app is initially opened, the 'all' route should be selected.

- [ ] sammyjs
- [x] plastronjs

test failures:

	TodoMVC - plastronjs, Routing, should highlight the currently applied filter
	TodoMVC - sammyjs, Routing, should highlight the currently applied filter

**Comment by arthurvr** [comment]
Plastronjs was removed recently: https://github.com/tastejs/todomvc/commit/c5ddf2144af0b120eb0f24adaff6935f822c1376.

**Comment by arthurvr** [comment]
Manually I confirmed sammyjs works fine, I guess we can close this issue as we anyways [don't run the tests for sammyjs](https://github.com/tastejs/todomvc/blob/c3c830453cf565dfbf779229e5943fa6c3ec8fb1/browser-tests/allTests.js#L21).

**Comment by samccone** [comment]
:+1:
