### ISSUE TITLE
typescript-backbone has incorrect HTML structure and completed item styling

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#830]
typescript-backbone has a nested `div` within the `li` element, and sets `/li/div[@class=done]`, which thwarts the tests and also incorrectly styles the app.

test  failures:

	'TodoMVC - typescript-backbone, Mark all as completed, should allow me to mark all items as completed / cleared',
	'TodoMVC - typescript-backbone, Item, should allow me to mark items as complete',
	'TodoMVC - typescript-backbone, Item, should allow me to un-mark items as complete',
	'TodoMVC - typescript-backbone, Item, should allow me to edit an item',

**Comment by arthurvr** [comment]
Fixed. Thanks @ColinEberhardt!
