### ISSUE TITLE
Durandal marking of item completion is strangely slow

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#831]
With durandal, when you mark an item as complete, it takes almost 1 second before the item state changes. To see this in action, mark an item as complete, then rapidly navigate to the '/completed' route. You will notice that the item you just marked is not present. Refresh the page and the item appears.

test failures:

```
'TodoMVC - durandal, Routing, should allow me to display active items',
'TodoMVC - durandal, Routing, should allow me to display completed items',
'TodoMVC - durandal, Routing, should allow me to display all items',
'TodoMVC - durandal, Routing, should highlight the currently applied filter',
```

**Comment by arthurvr** [comment]
ping @abhinavgujjar - interested?

**Comment by abhinavgujjar** [comment]
yeah -  will get on it tongight

**Comment by arthurvr** [comment]
ping @abhinavgujjar - still interested?

**Comment by arthurvr** [comment]
Given https://groups.google.com/forum/?fromgroups#!topic/durandaljs/_1MTnSZiuGU, shouldn't this app be deprecated in favor of the Aurelia one?

**Comment by FadySamirSadek** [comment]
Closed as out of datee
