### ISSUE TITLE
chapling brunch does not mark items as completed via the completed CSS class

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#832]
test failures:

	'TodoMVC - chaplin-brunch, No Todos, should hide #main and #footer',
	'TodoMVC - chaplin-brunch, Mark all as completed, should allow me to mark all items as completed',
	'TodoMVC - chaplin-brunch, Mark all as completed, complete all checkbox should update state when items are completed / cleared',
	'TodoMVC - chaplin-brunch, Item, should allow me to mark items as complete',
	'TodoMVC - chaplin-brunch, Item, should allow me to un-mark items as complete',
	'TodoMVC - chaplin-brunch, Item, should allow me to edit an item',

**Comment by arthurvr** [comment]
The main issue appears to be fixed in https://github.com/tastejs/todomvc/commit/79bba43d9c3e977d65ecf8f480e1a38eee039f3a.

```
   Mark all as completed
      ✓ should allow me to mark all items as completed (297ms)
      ✓ should allow me to clear the completion state of all items (329ms)
      ✓ complete all checkbox should update state when items are completed / cleared (363ms)
    Item
      ✓ should allow me to mark items as complete (284ms)
      ✓ should allow me to un-mark items as complete (283ms)
```
