### ISSUE TITLE
right-column popup too narrow

### ISSUE THREAD

**Issue by tomByrer** [tastejs/todomvc#850]
On the homepage, if you mouse over the right-hand column, the modal popups are more narrow.  [Reported before](https://github.com/tastejs/todomvc/issues/767).  Widening browser width does not help.

**Comment by radoneman** [comment]
Please see this fix 
https://github.com/radoneman/todomvc/tree/hotfix-right-column-popup-too-narrow

I'm a first timer :)

**Comment by arthurvr** [comment]
Looks like this is already resolved. (Ref https://github.com/tastejs/todomvc/pull/1519)
