### ISSUE TITLE
New solution in Ur/Web

### ISSUE THREAD

**Issue by achlipala** [tastejs/todomvc#912]
I've put together a quasi-implementation of the TodoMVC challenge problem in [Ur/Web](http://www.impredicative.com/ur/), which is a domain-specific language for web apps.  Here's a demo:
http://www.impredicative.com/ur/todomvc/

Do you think it might merit inclusion in an official TodoMVC release?

Ur/Web is quite different from mainstream frameworks, so I've had to deviate from parts of the specification, but the end-user experience within the page itself should be the same (modulo any remaining bugs), except that there is no persistent storage.  (The demo also currently requires the version of the Ur/Web implementation from [the working Mercurial repository](http://hg.impredicative.com/urweb).)

**Comment by FadySamirSadek** [comment]
Please reopen this issue if you're still interested in implementing this and make sure you're following [the new example guidelines ](https://github.com/tastejs/todomvc/blob/master/contributing.md#considerations-before-submitting-a-new-app)
