### ISSUE TITLE
new app: sirius.js

### ISSUE THREAD

**Issue by fntzr** [tastejs/todomvc#926]
Hi.
I wrote a m*c framework - [sirius.js](https://github.com/fntzr/sirius) it's a compiled from coffeescript.
I made a [todoapp](http://fntzr.github.io/sirius/todomvc/index.html) and now i would like to add my app into todomvc repository.
Thanks.

**Comment by samccone** [comment]
hi @fntzr thanks for opening the issue, we would love to see your framework mature a bit and get some users and applications built with it. 

When you feel like it has reached this point please feel free to open a PR with your implementation.
