### ISSUE TITLE
404 with learn.json in dev environments

### ISSUE THREAD

**Issue by MathieuLorber** [tastejs/todomvc#932]
The base.js script seems to call the learn.json by using the complete page URL + the simple string "learn.json" when it's not used since todomvc.com . This obviously does not work with local servers launched for local development. This is not a huge problem but it generates a surprising error for which the developer is not involved while he's working on a project...

**Comment by MathieuLorber** [comment]
Issue still open, should I close it ?

**Comment by samccone** [comment]
Now there is a nice console message when it is unable to load it in dev envs letting people know what to do to fix it.

![screen shot 2015-03-10 at 12 30 45 pm](https://cloud.githubusercontent.com/assets/883126/6579567/5545f41a-c721-11e4-8ea6-48293220e1d8.png)

I think we can close this issue now.
