### ISSUE TITLE
Redundant suspicious calls in `Ember.Route.setupController`

### ISSUE THREAD

**Issue by PavelBugaevskiy** [tastejs/todomvc#940]
The problem is, a closure in setupController method is getting called more times than expected after a route change. Is it ok?

Modify *router.js*
```Javascript
	Todos.TodosCompletedRoute = Ember.Route.extend({
		setupController: function () {
			var todos = this.store.filter('todo', function (todo) {
++				console.log( 'Checking a statement');
				return todo.get('isCompleted');
			});

			this.controllerFor('todos').set('filteredTodos', todos);
		}
	});
```

Refresh a browser. Add some todos. Complete few of them. Switch few times between `All |  Active | Completed`. Again, complete few todos. Witness a redundant console.log calls.

Video demonstration: https://yadi.sk/i/xKB9AB7BVSJcs

Tags: Ember.js / JS

**Comment by arthurvr** [comment]
I guess this was fixed in https://github.com/tastejs/todomvc/commit/e238042285540d60c09e7575b65d96518ba5445a#diff-55f2e5cd32b5e316ccd1932569194262L34. Can you confirm it works as expected at the moment? Sorry for getting back at you late!
