### ISSUE TITLE
Make TodoMVC more useful by adding more complexity

### ISSUE THREAD

**Issue by ericandrewlewis** [tastejs/todomvc#947]
Recently, I heard Yehuda Katz say about TodoMVC, "At the simplicity level that it's at, basically every one is the same" ([see here at 11:13](https://teamgaslight.com/training/classroom#/courses/4/chapters/27)).

This led to [a twitter conversation](https://twitter.com/wycats/status/488124985760706561), where Yehuda suggested that an app with at least 6 pages with some nested content is necessary to illustrate the architectural differences between JS MV\* frameworks.

I suggest we make TodoMVC more complex to meet this goal. Perhaps adding People in to app, who can be assigned tasks.

That way, there will be a few pages(routes):

/ - list of todos
/people/ - list of people
/people/1/ person view, including details about the person as well as tasks assigned to them

This may be a separate project, but I'm posting here to illicit feedback from the core TodoMVC team.

**Comment by addyosmani** [comment]
Please pardon the (ridiculous) delay on my part responding to this. If you're still interested, I would comment on one of the threads over at https://github.com/tastejs/TasteApp/ and we could probably take it from there :)
