### ISSUE TITLE
Exoskeleton throwing Uncaught TypeError

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#949]
If you enter more than one item to the exoskeleton app it throws the following:

TypeError: undefined is not a function
todomvc.com/labs/architecture-examples/exoskeleton/js/collections/todos.js:32

**Comment by samccone** [comment]
Looks like this is no longer happening
![screen shot 2015-03-11 at 10 15 57 am](https://cloud.githubusercontent.com/assets/883126/6598090/a501943a-c7d7-11e4-87c0-5d55e0aabcae.png)

closing (:
