### ISSUE TITLE
Fix bugs in Polymer implementation

### ISSUE THREAD

**Issue by addyosmani** [tastejs/todomvc#952]
Too wide:

![](http://i.imgur.com/cmaOYLz.png)

Routing and persistence aren't working:

![](http://i.imgur.com/lIl6rs7.png)

**Comment by arthurvr** [comment]
> I've fixed these two issues but discovered there's now an issue with our styling in Firefox. I need to dig into why that's having problems.

ping @addyosmani ;)

**Comment by arthurvr** [comment]
The app was recently rewritten so closing this.
