### ISSUE TITLE
Haskell client side web framework: hplayground. Request for inclusion

### ISSUE THREAD

**Issue by agocorona** [tastejs/todomvc#954]
The code:
           https://github.com/agocorona/hplay-todo

Running:
           http://mflowdemo.herokuapp.com/todo.html

The hplayground git site:
           https://github.com/agocorona/hplayground

Some little bugs remain.

hplayground is a haskell framework that compiles to JavaScript (or to HTML directly) using a Haskell to JavaScript compiler.

hplayground code has full reinversion of control. The code look like a console application with no event handlers. It is oriented towards rewrites of the HTML.DOM rather than to achieve dynamic behaviours by means of changing class attributes and hiding elements. therefore the dynamic effects, like edition of entries etc are done in such a way. The CSS reflect these changes too.

**Comment by arthurvr** [comment]
Hey! Thanks for reaching out and sorry for the delayed response.

We had a brief chat about this and our conclusion was the the framework and its community aren't yet mature enough to include a new example for it. We'd like to see some more usage of it in the wild and see its community mature, when you feel like it reached that point, ping us and we'll reconsider :dancer:
