### ISSUE TITLE
React example is broken

### ISSUE THREAD

**Issue by balupton** [tastejs/todomvc#962]
http://todomvc.com/architecture-examples/react/

Screenshot: https://www.dropbox.com/s/9pxxslkpj2lvcl3/Screenshot%202014-08-06%2011.51.43.png

Chrome Version 35.0.1916.114 on OSX

**Comment by muhammadhassan** [comment]
It is still broken on Safari and Chrome on Mac OS X
http://todomvc.com/examples/react/

I got this error (on both Safari 8 and Chrome 41)
[Log] message.name run true (contentscript.js, line 90)
[Warning] You are using the in-browser JSX transformer. Be sure to precompile your JSX for production - http://facebook.github.io/react/docs/tooling-integration.html#jsx (JSXTransformer.js, line 318)
[Error] Error: Parse Error: Line 2: Unexpected token !
    at http://todomvc.com/examples/react/

<!--
                  ^
	transformCode (JSXTransformer.js, line 142)
	run (JSXTransformer.js, line 187)
	check (JSXTransformer.js, line 242)
	loadScripts (JSXTransformer.js, line 295)
	runScripts (JSXTransformer.js, line 324)

It works fine on FireFox

**Comment by samccone** [comment]
Seems to be working for me ...

**Comment by muhammadhassan** [comment]
What version of browsers are you using? Did you tried incognito?

**Comment by arthurvr** [comment]
Working for me.
