### ISSUE TITLE
For consideration: WinJS app implementation

### ISSUE THREAD

**Issue by jayrenn** [tastejs/todomvc#975]
Hello,

Would there be interest in a [WinJS](http://try.buildwinjs.com) app implementation? Let me know!

Thanks,
Josh

**Comment by arthurvr** [comment]
> I would be interested in a WinJS implementation. Could you talk a little bit about the current userbase for the project and how widely WinJS is used in the web development community? How does it differ from some of the other frameworks we see today?

I'm going to close this as we never really got answers for those questions. We can consider reopening when we have the info we need :)
