### ISSUE TITLE
Reagent ClojureScript version of TodoMVC inclusion request

### ISSUE THREAD

**Issue by yogthos** [tastejs/todomvc#985]
The code:
https://github.com/holmsand/reagent/tree/master/examples/todomvc

Running:
https://rawgithub.com/yogthos/reagent-todomvc/master/todomvc.html

Reagent site:
http://reagent-project.github.io/

Reagent on GitHub
https://github.com/reagent-project/reagent

Reagent provides a minimalistic interface between ClojureScript and React. ClojureScript is compiled to JavaScript using Google closure library and Reagent. In my opinion, Reagent provides a very simply and intuitive API for working with React and adds clean data binding using atoms.

**Comment by samccone** [comment]
@yogthos would you like to open a PR? seems like #1053 means like it will be merged :ship: :v:

**Comment by yogthos** [comment]
@samccone excellent, I can definitely do that :)

**Comment by samccone** [comment]
:boom:

**Comment by arthurvr** [comment]
Fixed in https://github.com/tastejs/todomvc/commit/e714fd00c49996c96edaa7b68641e3f54b1dc6dc
