### ISSUE TITLE
The framework names 'jiggle' when switching tabs

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#987]
This is due to changes from #984 (which I really like by the way!)

When switching between the tabs I am seeing quite a bit of unsightly 'jiggle'. Probably best described by a video:

https://www.youtube.com/watch?v=NegRjF4qc94

This was recorded with Chrome 36.0.1985.143

**Comment by arthurvr** [comment]
I don't seem to be noticing this anymore. Is this still an issue?

**Comment by ColinEberhardt** [comment]
The frameworks no longer slide into place so this is no longer an issue :-)
