### ISSUE TITLE
The framework tabs are not working on Safari

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#988]
This is due to changes from #984, On Safari (Mac, 7.0.3) the tabs are not hidden:

![screen shot 2014-08-27 at 14 45 46](https://cloud.githubusercontent.com/assets/1098110/4060556/a836d51a-2df0-11e4-9d92-f65c1b865bf2.png)

Failures from the Safari log
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (platform.js.map, line 0)
[Error] Error: Assertion failed (platform.js, line 12)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (platform.js.map, line 0)
[Warning] Invalid CSS property declaration at: * (tweet_button.1409007440.html, line 1, x3)
[Warning] Invalid CSS property declaration at: * (follow_button.1409007440.html, line 1, x3)
```

**Comment by arthurvr** [comment]
This appears to be fixed (for me at least)?

**Comment by addyosmani** [comment]
What version of Safari were you testing in?

**Comment by arthurvr** [comment]
Safari 8

**Comment by arthurvr** [comment]
If somebody can confirm this is fixed in Safari 8, we can close the issue as [we only support latest Safari](https://github.com/tastejs/todomvc/blob/master/contributing.md#browser-compatibility)?

**Comment by ColinEberhardt** [comment]
Yes, this is working fine for me on Safari 8.0.4

**Comment by samccone** [comment]
:dancer:
