### ISSUE TITLE
Quotes not rendered in Safari

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#989]
Relating to #984 - quotes are not rendering properly in Safari:

![screen shot 2014-08-27 at 14 55 48](https://cloud.githubusercontent.com/assets/1098110/4060699/f86ff830-2df1-11e4-9fa9-bb2d65cfc3ec.png)

Sorry for all the bug reports :-(

**Comment by samccone** [comment]
Seems to be rendering correctly now...

![screen shot 2015-03-10 at 11 09 09 am](https://cloud.githubusercontent.com/assets/883126/6577662/e87ed4b0-c715-11e4-982b-ce0a3be45553.png)

**Comment by arthurvr** [comment]
Yup, perfectly looks fine now.
