### ISSUE TITLE
somajs_require implementation doesn't work with automated tests

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/todomvc#999]
Previously somajs_require was broken, but is now fixed :-) see #819

However, the tests still fail intermittently. For some reason when the todo items are added to the list it sometimes fails to register the enter keypress. As a result, multiple todo items end up concatenated together.

**Comment by arthurvr** [comment]
I tested this in multiple browsers and everything seems to pass. Can somebody confirm?

**Comment by ColinEberhardt** [comment]
Just re-ran the tests, and all 29 passed. Looks like this issue is closed :-)

**Comment by samccone** [comment]
:dancer:
